### ISSUE TITLE
trailing newline on rendered list elements disrupts layout

### ISSUE THREAD

**Issue by simonmichael** [jtdaugherty/brick#10]
The right-padding issue I noticed on #7 was because my rendered list elements had a trailing newline. In this situation the row ends with an ellipsis, and an enclosing element's width is disrupted on that line. Eg instead of
```
|                        |
|    E                   |
|                        |
```
you see
```
|                        |
|    E…|
|                        |
```
Perhaps it should always strip trailing newlines, I expect it will be a common mistake.

**Comment by jtdaugherty** [comment]
A while back I split up the string and text widget functions into single- and multi-line variants.  I noticed that in cases where you just want to display short strings with no newlines, we were paying a performance penalty because of all of the line processing that `str` is doing.  I was hoping that we could avoid this by having special constructors for those cases, but from this issue and from my own experience I'm now pretty sure it isn't worth the benefit since it's too easy to get this wrong.

I've removed the multiline variants in 1950bc01deb72492b9d01f309cdc575530fd45c1 so now `str` and `txt` behave as before and deal with newlines gracefully.
