### ISSUE TITLE
Is there a way to nest Lists?

### ISSUE THREAD

**Issue by diegospd** [jtdaugherty/brick#110]
I was trying to implement some kind of tree browser using nested lists, but I get an error `tried to embed an infinite-height widget in vertical viewport` when I call `renderList` on a sublist.

**Comment by jtdaugherty** [comment]
Lists are designed to accommodate items with a fixed height, and all items in a list must have the same height (hence the integer parameter to the list constructor). Both of these restrictions make it possible to use Lists with arbitrarily many elements without paying an O(n) performance penalty. Since it's commonly the case that these restrictions aren't problematic, that makes them a relatively small price to pay for the huge performance gain.

You could avoid those restrictions by implementing your own "list-like" widget (i.e. don't use brick's List at all) but that'd be a lot of work. You could also do what you want by thinking of List just as a presentation widget on top of a more detailed structure. In this case you could write a function
```
data ListItem =
  ListItem { treeDepth :: Int
           , nodeLabel :: String
           , ...
           }
treeToList :: Tree -> ListItem
treeToList t = ...
```
to do a traversal of your tree (whenever it changes, say) to build the corresponding list of tree nodes to be presented in the brick List. That way each can still have equal/fixed height (say, 1 row per node) and you can save information about the tree traversal (such as node depth) in the `ListItem` and use that to render the tree items in the List so that they actually appear to be tree-shaped. Does that make sense?

**Comment by diegospd** [comment]
Sure it does. It's even easier to handle the relevant events that way. Thanks for the tip!
