### ISSUE TITLE
Question: undo/redo for Edit Widget ?

### ISSUE THREAD

**Issue by clojj** [jtdaugherty/brick#112]
Hi,

Is undo functionality on brick's roadmap ?
If not, where do you see it... in Edit.hs itself or as an app-specific thing ?

Strategy: keep a list of (undoable) events in memory (?)

**Comment by jtdaugherty** [comment]
Brick's editor is really intended to just provide the most basic editing interface to permit user input; more sophisticated editors should probably not be based on it just because the data structures it uses aren't going to be suitable for editing, say, large files or doing syntax highlighting.

With that said, I think your idea of the strategy to use is pretty common, which is to express each editing operation as something that is invertible, and then undoing an operation just means applying its inverse edit.

If you really want this in Brick's editor then I would be open to considering patches for it! Even better, if you wrote your own package that provided an "improved brick editor" then I'd love to see that. But doing this in Brick isn't part of my long-term strategy.

If you'd like to pursue this yourself then we can leave this ticket open and discuss further. Otherwise, please close this ticket unless there is more I can do.

**Comment by clojj** [comment]
Thanks for these infos

**Comment by clojj** [comment]
Your sure that the existing Editor (using text-zipper) is not fast enough for syntax-highlighting normal-sized source-code ?
I am a bit surprised by that.. also there is brick's rendering cache which should help (?)
(my intent would not be editing large log-files or stuff like that)

**Comment by jtdaugherty** [comment]
The current editor wouldn't really get in the way of syntax-highlighting, but it is not the most appropriate way to represent the text to allow for that kind of manipulation. The text-zipper data structure is also not appropriate for large-scale editing; there are many other approaches for text editor data structures that should be explored for writing a "real" editor.

But yes, if you do end up making something of your own, I'd be interested to see how it turns out!
