### ISSUE TITLE
Bounded channel is missing essential operations

### ISSUE THREAD

**Issue by Tuplanolla** [jtdaugherty/brick#115]
Since moving from `Control.Concurrent.Chan.Chan` to `Brick.BChan.BChan`,
I can no longer use broadcast channels with Brick.
It would be very useful to have `dupBChan :: BChan a -> IO (BChan a)` and
`newBroadcastBChan :: IO (BChan a)`.
If adding the operations to `BChan` is not possible,
perhaps `Brick.Main.customMain` should be written
in terms of a channel type class instead of a concrete `Chan` or `BChan`.

**Comment by jtdaugherty** [comment]
I don't know anything about how your application is designed, but you can always use `Chan`s in whatever configuration you want and just have a thread that transfers values from your `Chan` to the `BChan`. Consequently I'm not convinced that the `BChan` API needs to change since you have that freedom.

**Comment by Tuplanolla** [comment]
Being able to implement a work around for an issue
is not really compelling argument for not taking care of it.
It is certainly possible to spawn a thread
to move values from one channel to another,
but why do all the unnecessary copying and scheduling if it is avoidable?

**Comment by jtdaugherty** [comment]
I suggested an alternative approach because:
* I don't agree that `brick` should expose channel duplication or broadcast functionality specifically.
* I'm not confident that adding the requested functionality to `BChan` is even meaningful or safe considering its bounded, blocking nature.
* The requested functionality is already provided elsewhere, so nothing is preventing you from getting what you need.
* In my opinion it is a *better design* to separate the rest of the application's channel management semantics from the bounded brick channel because it makes it clear how that semantic boundary (i.e. unbounded vs. bounded) is managed explicitly.
* Under the hood, `BChan` uses `TBQueue` which does not support the requested operations.

I understand that the requested changes would make the API more convenient for you. In general I am a big advocate of making APIs more convenient for users, and I have put a lot of work into brick to make that so.
