### ISSUE TITLE
Tearing on resize in urxvt

### ISSUE THREAD

**Issue by JacksonGariety** [jtdaugherty/brick#120]
The `HelloWorldDemo` doesn't have this issue, and neither do the Vty demos. It seems to occur with programs that do not use `simpleMain` and it seems only to occur with the `urxvt` and `rxvt` terminal emulators. `xterm` and `st` do not have this issue.

1. launch `Urxvt` or `rxvt`
2. launch a brick demo program that uses `defaultMain`
3. resize the window a bit and see graphic tearing
4. resize the window to 0x0
5. resize the window and notice that there is no graphic tearing

It's curious that resizing to 0x0 resolves the issue. Interesting bug I think; thought I'd share.

**Comment by jtdaugherty** [comment]
I don't have access to `rxvt`, so I'll ask a co-worker to try this later. (Or you could somehow make a video of it and link that here.) For what it's worth, I suspect this has more to do with the terminal emulator implementation than anything else, but we probably get a stream of resize events during a terminal resize and that would trigger a long sequence of redraws. Does the application at least draw properly once resizing has stopped?

**Comment by JacksonGariety** [comment]
@jtdaugherty yes. Once the resize has stopped brick draws everything correctly. I decided to submit the issue because it resolves itself only after resizing down to zero in either direction. Brick does something special in this case in that instead of sending a `(width, height)` to `lookupEvent` it sends `Nothing`. That's curious because I'd expect it to send `(0, 0)`.

Thanks for the help with my minor issue!

**Comment by jtdaugherty** [comment]
Do you mean `lookupViewport` or `lookupExtent`?

Also, can you provide a minimal demonstration program that has this behavior so I can test it?

**Comment by JacksonGariety** [comment]
It's easily visible with vertical borders.

```
import Brick
import qualified Brick.Widgets.Border as B

ui :: Widget ()
ui = B.vBorder

main :: IO ()
main = simpleMain ui
```

P.S. I did mean `lookupExtent`.

**Comment by jtdaugherty** [comment]
The terminal I use, iTerm2 (OSX), also exhibits this behavior. But the behavior isn't a bug; it's a consequence of the terminal trying to be "smart" about wrapping text.This also happens if you run `vim`: on startup, all unused rows have a lone `~` present. Resizing the terminal causes those to fly all over the place because the terminal treats the contents like lines of text to be wrapped. For applications like `vim` or most `brick` programs, that will result in this erratic behavior during resize. Does that make sense?

**Comment by jtdaugherty** [comment]
Also, on the topic of the disappearing extent: `lookupExtent` will return `Nothing` when the named extent wasn't rendered at all. I haven't checked the code, but I would expect the renderer to *only* record non-empty extents. You can interpret a `Nothing` to mean that the requested extent just wasn't rendered, probably because its parent didn't have enough room or was itself not rendered (in this case due to not having enough room to render anything at all).

**Comment by jtdaugherty** [comment]
I also think the reason that getting to zero rows and columns improves the tearing behavior is because the line-wrapping done by the terminal (that causes the tearing) does better when there is less to draw (less to poorly wrap in our case) and then as the terminal grows bigger, the wrapping effect is not as apparent.

**Comment by JacksonGariety** [comment]
Alright, I'm willing to close this as a terminal quirk.

Thanks for taking a look!
