### ISSUE TITLE
Expose the "Internal" modules

### ISSUE THREAD

**Issue by jfischoff** [jtdaugherty/brick#125]
I understand the desire to have internal modules, however exposing so that users can optional important them, with the understanding that they are taking their lives in their own hand might, might be better than the alternative. 

For instance, if a user needs something to be exported that is in an internal module (see issue #124), the user is forced to fork the package, which is a worse outcome for the user then having to update their code if the internal module changes (they are now maintaining a forked package that they have to patch in addition to updating their own code if the internal module changes enough).

My proposal is to document that the modules are internal and that version number scheme is meaningless when it comes to the modules. Other packages have taken this success and I find it preferable to forking.

**Comment by jtdaugherty** [comment]
I'm hoping that resolving #123 and #124 will make this unnecessary. In general the internal modules are hidden precisely because they make it easy to tell when the public-facing API needs improvement, and if I expose those then I will never be able to tell whether the API is adequate because users will be able to "import around the problem."

As a result I'm not willing to expose internal modules - but I *am* totally happy to consider situations that would suggest that the exported API needs to be tweaked.

**Comment by jfischoff** [comment]
A fair point. I have a counter, you can learn that this is the case when users publish dependent packages that show this or when they tell you. 

The users that report issues with the API I would wager are more likely to do so regardless. The users that will not report issues, will just not use the package.

**Comment by jtdaugherty** [comment]
> A fair point. I have a counter, you can learn that this is the case when users publish dependent packages that show this or when they tell you.

This assumes I'll notice, which I might not. If users have to come to me and discuss the situation, there are two outcomes: the API changes because it needed to support something new, or the user learns that the API already does what the want, and they go about their business. :)
