### ISSUE TITLE
Q: is it possible to word-wrap content string based on available rendering width?

### ISSUE THREAD

**Issue by Wizek** [jtdaugherty/brick#127]
I was a bit surprised to see that when I use `str` (with a String that is longer horizontally than the box it was in) the end of it got clipped instead of being wrapped to a new line. I've tried to search both on hackage and here on GitHub for a way to have wrapping based on words or at least characters, but didn't find anything specific, only that there is a way for me to manually query the renderer for the available width.

Is this functionality available in the `brick` package? Or is it up for the users of the library to write these kinds of wrapping functions themselves? And if so, did someone perhaps already write such a function they could share?

**Comment by jtdaugherty** [comment]
The reason `str` doesn't do this automatically is because I wanted `str` to be a simpler primitive that could be used to *build* a word-wrapping implementation, and also because word-wrapping is not necessarily always desired--we don't want to pay a performance hit in cases where we don't care about wrapping--so having `str` do that implicitly would mean the user has less control over the library.

However, you're absolutely right that this would be useful, and I usually end up implementing it in applications that I make. Right now it isn't in the library because every time I end up writing it in other settings, it's tailored enough to the specific application that there isn't a sufficiently generic version that I've felt would fit in.

The only implementation for this that I have on hand is for word-wrapping Markdown ASTs, which is probably a bigger hammer than you are looking for. In any case it is here:

https://github.com/matterhorn-chat/matterhorn/blob/master/src/Markdown.hs

I'd be happy to have a basic implementation of this in the library so long as it was clear that users wanting to do more (such as highlight certain substrings) would need to find a way to do that on their own.

**Comment by jtdaugherty** [comment]
I've created a ticket to remind myself to add a basic word-wrapping primitive to the library, so I'm going to close this - please feel free to follow #128. I'll get to it in the next few days.
