### ISSUE TITLE
Add basic word-wrapping string primitive

### ISSUE THREAD

**Issue by jtdaugherty** [jtdaugherty/brick#128]
Often even the most basic word-wrapping primitive would be very helpful, so this ticket is for implementing one:
```
strWrap :: String -> Widget a

txtWrap :: T.Text -> Widget a
txtWrap = strWrap . T.unpack
```
(See also #127.)

**Comment by jtdaugherty** [comment]
Take a look at the new functions `strWrap` and `txtWrap` in `Brick.Widgets.Core` on the `master` branch, as well as the new `TextWrapDemo` demo program.

**Comment by Wizek** [comment]
Thanks @jtdaugherty it works wonderfully in my use case.

2 notes of minor importance:

- I am concerned when I see multiple `reverse`s on a `String`, e.g. in `reverseBreak`. Do you have a similar concern about its performance? Or would it be premature optimization at this point in time? Maybe we can take a look at it once it does become a performance issue for one of us, or someone else reports it?

- I tried some edge cases on the demo, e.g. shrinking the terminal to have very small width, and I noticed extra new lines appearing. E.g. the extreme case of having only 2 columns available shows

  ```
  He

  wo

  Th
  ```

  for me, and instead I thought I'd see:

  ```
  He
  wo
  Th
  ```

  or perhaps

  ```
  He
  ll
  o,
   w
  or
  ld
  !
  ```
  
  Are you perhaps open to the idea of having automated unit tests which could list and check all the common and edge cases such a function is expected to handle? E.g. with `hspec`: 

  ```
  wordWrap 2 "Hello, World! This" `shouldBe` "He\nWo\nTh"
  ```

With all that said, these are merely suggestions/questions of low importance from my vantage point, since the main use case for me is already fulfilled. Thank you again for providing an implementation, and doing so as quickly as you did.

**Comment by jtdaugherty** [comment]
* I do have concerns about performance for this, but as with all performance concerns I want to wait until it actually manifests for someone. (So often the real performance problems lie elsewhere.) I'd have concerns even beyond use of reversals, such as doing these operations on linked lists at all. In addition, I'm still convinced that although this is useful functionality, for many applications it won't be adequate because `String` won't be the underlying data type anyway (such as in my other case, `matterhorn`, where the data to be wrapped is a Markdown document), so I see the performance risk as being lower because of that, too. Still, if it becomes a serious issue for someone, I'm happy to revisit it.

* I'm definitely open to tests. The edge case you gave should be better-behaved - this is what I get for borrowing someone else's implementation. :) But what I'd like even more is if this functionality was in its own library, with tests included. I did it this way because I'm time-constrained, but I might have time this weekend to make a package. (I don't see any on Hackage that provide this as standalone functionality.)

**Comment by jtdaugherty** [comment]
FYI, I've uploaded a new package:

http://hackage.haskell.org/package/word-wrap

and now `brick` uses `word-wrap` as of https://github.com/jtdaugherty/brick/commit/974453c55c1b0b5abfd5aebc2da356f312e07974.
