### ISSUE TITLE
Question/idea: Would it be possible for Brick to do lazy rendering?

### ISSUE THREAD

**Issue by Wizek** [jtdaugherty/brick#129]
I mean something along the lines of:

```hs
#!/usr/bin/env stack
-- stack --resolver lts-8.20 script

{-# language TypeApplications #-}

module Main where

import Brick
import System.IO.Unsafe
import Control.Concurrent

main :: IO ()
main = do
  list1 <- take 4 <$> simulateSlowEval
  list2 <- take 4 <$> simulateSlowEval

  simpleMain $ emptyWidget @ ()
    <=> (str $ show list1)
    <=> (str $ show list2)

simulateSlowEval :: IO [Int]
simulateSlowEval = go 1 where
  go n = do
    rest <- unsafeInterleaveIO $ go $ n + 1
    threadDelay 200000
    return (n : rest)
```

As it stands, it seems the renderer waits for the whole scene to arrive at normal form, and I wonder if it would be possible/easy/desirable to be able to start rendering at WHNF too. I can imagine various degrees of laziness:

### A) Fully strict rendering
  
  As it is today

  1.
      ```


      
      ```
  1.
      ```
      [1,2,3]
      [1,2,3,4,5]
      Done
      ```

### B) Per-Widget-based lazy rendering
  1.
      ```

      
      Done
      ```
  1.
      ```
      [1,2,3]
      
      Done
      ```
  1.
      ```
      [1,2,3]
      [1,2,3,4,5]
      Done
      ```
      
### C) Serial lazy rendering

  1.
      ```
      [

      
      ```
  1.
      ```
      [1,
      

      ```
  1.
      ```
      [1,2,
      

      ```
  1. ...
      
### D) Concurrent lazy rendering

  1.
      ```
      [
      [
      Done
      ```
  1.
      ```
      [1,
      [1,
      Done
      ```
  1. ...

I think option D could be the most desirable.

Also, so far the GUI frameworks I've tried with Haskell, to my surprise, all demanded rendering to be fully strict. Brick could be the first one (that I know of at least) that supports this feature natively.

What do you think?

**Comment by jtdaugherty** [comment]
I think using laziness this way as a program feature would make such programs monstrously difficult to write, understand, maintain, and get right. I think that using a custom event channel to explicitly update your application state and draw the picture you want is the approach that I prefer. That way you actually have *more* control, because you can implement a wider array of incremental state changes than would be possible via carefully-controlled laziness. (Not to mention that this latter approach would have better memory characteristics.)

**Comment by jtdaugherty** [comment]
(With that said, if you have a specific objective and would like to discuss it, I'd be happy to take a look and determine whether it can be accommodated by the library!)
