### ISSUE TITLE
Brick.Types.Internal not on Hackage

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [jtdaugherty/brick#131]
Hello again! I'm exploring the demo programs. Sometimes I ask GHCI for information about BrickEvent, and it refers me to Brick.Types.Internal. Should that be on Hackage? (I downloaded the source and I see that the file appears to be marked up with Haddock.)

**Comment by jtdaugherty** [comment]
`Brick.Types.Internal` isn't on Hackage because it's a hidden module, which is deliberate. However, anything in that module that you get ahold of in GHCI will also be re-exported by `Brick.Types`, which *is* exposed and is included in haddock documentation on Hackage. There's Haddock in the internal module because I document things. :)

The `n` type variable in both mouse event constructors refers to the resource name of the clicked widget. So, for example, if you have a drawing
```
clickable FooName $ str "Click me!"
```
then when the user clicks on any part of that string, you'll get a `MouseDown` event with `n` set to `FooName`.

**Comment by jtdaugherty** [comment]
(I'm going to close this since I don't see an action to take here, but please feel free to e-mail me or join the brick-users list if you want more help!)

**Comment by JeffreyBenjaminBrown** [comment]
Aha! Thanks!

**Comment by JeffreyBenjaminBrown** [comment]
I had one remaining question: Lots of the types in Brick appear to have a parameter called `n`. Should I assume wherever I see an `one that it means the same thing, a widget name?

**Comment by jtdaugherty** [comment]
I just released `0.21` that has an improved haddock for those constructors, by the way.

**Comment by JeffreyBenjaminBrown** [comment]
Sweet! I'll download the latest.

Is "n" better than "name"? If I understand correctly, there's no type constraint or other kind of context letting the compiler understand that those "n" values are similar; it's just up to the user to know what the author meant.

**Comment by jtdaugherty** [comment]
> Is "n" better than "name"?

By this are you asking about what makes a more readable type signature?

> If I understand correctly, there's no type constraint or other kind of context letting the compiler understand that those "n" values are similar; it's just up to the user to know what the author meant.

The `n` type is actually plumbed throughout the entire library and types, and `n` is always used to mean the same thing, i.e., `n` is always required to match (e.g. `App s e n`, `FocusRing n`, `BrickEvent e n`, and so on). So in that sense, the compiler will absolutely enforce that they are the same `n`, whichever type that might be. I'm not sure if this answers your question, though.

**Comment by JeffreyBenjaminBrown** [comment]
Cool! So how does that happen? (I'm sorry to be asking you general Haskell questions on this Brick-specific forum; if you prefer I can move this to one of the haskell mailing lists.)

Suppose I wrote a two line program:

```
data Foo n = Foo n
data Bar n = Bar n
```

Nothing would require those two `n` values to be similar. What causes the same meaning of `n` to be threaded throughout Brick? How does the compiler know, and how should a reader know?

**Comment by jtdaugherty** [comment]
Ah! I see what you're asking now.

It's true that, just given your code above, `n` can definitely be different for both `Foo` and `Bar`. We make them agree by using them both in a type, such as
```
someFunction :: Foo n -> Bar n -> ...
```
The fact that we have used `n` here is not important; what's important is that we use the *same type variable* in each spot where we require a match. So, the following are equivalent:
```
someFunction :: Foo n -> Bar n -> ...
someFunction :: Foo a -> Bar a -> ...
```
So:
 * The compiler knows because you told it, by using a type variable in multiple places within a type signature
 * The user should know by 1) reading the type signatures and 2) relying on the author of the code to use consistent type variable naming conventions.

**Comment by JeffreyBenjaminBrown** [comment]
Ah, that makes sense. So to make sure two functions f and g refer to the same n, the compiler and the human both have to just find a function that uses both of them, or a chain of functions that connects them.

`name` still seems like a more helpful term than `n` to me, but I hesitate to look a gift horse in the mouth; this library is wonderful.

**Comment by jtdaugherty** [comment]
> Ah, that makes sense. So to make sure two functions f and g refer to the same n, the compiler and the human both have to just find a function that uses both of them, or a chain of functions that connects them.

That's right - the specific type variable is not important globally (except for readability). It is just important as a signifier that some type needs to be provided, and it is used to ensure type resolution when more than one type references the same variable.

> `name` still seems like a more helpful term than n to me, but I hesitate to look a gift horse in the mouth; this library is wonderful.

The reason I don't use `name` is because 1) single-letter type variables make for more concise type signatures (imagine seeing `name` everywhere you see an `n` in Brick), 2) it's common Haskell style, and 3) the name of the variable doesn't often contain any information and using a single letter helps to remind the reader that we're making the thing using `n` polymorphic. It's very, very uncommon for Haskell codebases to use more than a single letter for any type variable, but it *is* common for APIs to use a consistent internal naming convention to aid the reader in tracking the meaning of the variable through the API.

**Comment by JeffreyBenjaminBrown** [comment]
I just started a discussion about this convention on haskell-cafe. I will send the link when it exists, if I remember. Thanks again for your help.

**Comment by jtdaugherty** [comment]
Thanks - I see the conversation now in the archives.
