### ISSUE TITLE
Border labels can get truncated

### ISSUE THREAD

**Issue by siddhanathan** [jtdaugherty/brick#135]
```haskell
module Main where

import Brick
import Brick.Widgets.Border

ui :: Widget ()
ui = borderWithLabel (str "Hello World!") (str "Content")

main :: IO ()
main = simpleMain ui
```

![screenshot from 2017-08-27 04-28-14](https://user-images.githubusercontent.com/933964/29748242-2b7573c4-8ae0-11e7-9c8d-1d71792a207e.png)

If this is the intended behavior, a warning in the documentation would be nice.

**Comment by jtdaugherty** [comment]
This is the intended behavior: if a border only has `N` columns to use, it only allocates `N-2` columns for the label widget, and `str` truncates its argument to fit in the available space (which is how all widgets are required to behave).

I'm happy to add a section to the user guide about this, since this is a general issue for *all* widgets, not just border labels. Would that work for you?

**Comment by jtdaugherty** [comment]
Thinking about this a bit more, the behavior of `border` does add an extra behavior that isn't obvious, which is that the border only takes up as much space as it needs to wrap its contents, which means that even if it *could* be bigger, it won't unless the contents *force* it to - namely, by using a `fill` or other space-filling widget.

So that means there's room for two updates: a general note about truncation due to the layout constraints every widget faces, and a specific note about the behavior of `borderWithLabel`.

**Comment by jtdaugherty** [comment]
The border documentation change is in https://github.com/jtdaugherty/brick/commit/231adfe276f90898c131943f5c6c79c0f46ff9d5.

**Comment by jtdaugherty** [comment]
The other change is in https://github.com/jtdaugherty/brick/commit/932f153be8a0786ba36537c0614c789f3429a122.

**Comment by jtdaugherty** [comment]
Please let me know if this addresses your concern. If so, please close this ticket. Thanks!

**Comment by siddhanathan** [comment]
Yes, that works. Thank you!
