### ISSUE TITLE
Suggestion about version numbering scheme for releases

### ISSUE THREAD

**Issue by hpdeifel** [jtdaugherty/brick#143]
Hi!

As a happy user of this library for [hledger-iadd], I wanted to say thanks for all the hard work that goes into this.

I have one question, though: Could you consider releasing API additions as minor instead of major versions? I'm using PVP-based upper bounds for the brick dependency, because there have been changes in the past that broke my build. However, with the current frequency of major version releases, it's hard to keep those bounds up to date. This is especially necessary, since stackage gives maintainers only a week or so to update dependency bounds for their package.

The PVP [allows]( https://pvp.haskell.org/#version-numbers) additions to the API to be released as minor versions and build failures can be quite easily avoided in this case by using qualified imports or explicit import lists.

[hledger-iadd]: https://github.com/hpdeifel/hledger-iadd/

**Comment by jtdaugherty** [comment]
> This is especially necessary, since stackage gives maintainers only a week or so to update dependency bounds for their package.

What happens if you miss this deadline?

**Comment by jtdaugherty** [comment]
@hpdeifel I'm still interested in the answer to my question above, but ultimately I must decline. My position is that this is really a problem for Stackage, since in my view a week is too tight a timeline and this is a policy choice they've made that I don't think should drive how people version their packages.

My other reason for declining is that I'd really rather not change version numbering semantics on `brick` now that the package has so many releases, and I'm partial to the scheme that I use. I realize I am not following the PVP exactly (I am versioning `brick` even more conservatively).

I recognize that this creates some friction for you -- and I'm sorry to hear it -- but I suggest you take up the Stackage update policy with the Stackage maintainers.

**Comment by JackKiefer** [comment]
I understand your position here, but to be honest it _would_ be nice to have API additions as minor versions. To answer your question, if the deadline is not met, then the package is disabled in Stackage and will not be included in any major releases until the issue is fixed. I was out of town for a bit and ended up missing just such a deadline, and due to some unfortunate timing `herms` is now not included in Stackage `lts-12`. We'll have to wait until the next LTS release. 

While your versioning philosophy has merit, conforming to the PVP would be a choice in the favor of your libraries' dependents, and I do humbly request that you consider it. :)

Thanks again for all your work! `brick` and `vty` are fine pieces of software that have been indispensable in our projects. :D
