### ISSUE TITLE
Brick.Widgets.List.listReplace has with no selection when used with listSelectedL

### ISSUE THREAD

**Issue by romanofski** [jtdaugherty/brick#146]
I've stumbled over this issue which seems to be maybe my fault instead of a bug, but I thought I'd raise it anyway. I'm using `listSelectedL` with `listReplace` to re-populate a list widget. We're repopulating the list widgets based on a search result which can be empty. In order to avoid the selection jumping around, I re-use the index from what was selected before with the `listSelectedL` lens.

However if the previously selected list was empty, the `listSelectedL` is `Nothing` and calling `listReplace` with a non-empty vector, but a `Nothing` value ends up with a list without a selection.

Is this intended? I'm asking, since I can't think of a good use case where you want to have a non-empty list without anything selected. Every idea I come up with seems contrived. Having said that, the code does the "right" thing, although a bit unexpected.

Code in question: purebred-mua/purebred#88 specifically [this](https://github.com/purebred-mua/purebred/pull/88/files#diff-17fe81b31dc7d22a8f09101721b8242dR334). Any ideas?

**Comment by jtdaugherty** [comment]
The reason to have a non-empty list with no selected element would be a case where you don't actually use the list for selection, just rendering things, in which case showing a cursor is misleading. Or a case where you do use it for selection, but the selection is modal. (And the alternative to getting that UI if a selection was *required* would be to hack your theme so that the list selection attribute was indistinguishable from the regular list attribute, and that's not very nice.) I can understand the confusion, though.

I think in this case it's up to your application to request a `Just` selected index on a `listReplace` if you know you're replacing with a non-empty list. If your previously selected index is `x :: Maybe Int`, you can just call `listReplace` with `x <|> Just 0`.

**Comment by romanofski** [comment]
Ah I thought of that use case but dismissed it. Good to know. Thanks for the hint :))

**Comment by jtdaugherty** [comment]
You're welcome!
