### ISSUE TITLE
Multiple selections in a list

### ISSUE THREAD

**Issue by romanofski** [jtdaugherty/brick#150]
I'd be keen to add multiple selections for the list type. A couple of questions tho:

* Should it be implemented in a new widget (e.g. MultipleSelectionList) instead of the standard list? (Not sure here, since it might already work out by adjusting the existing list)
* Data type to store the selection? (Vector holding the indexes?)

Maybe there is more, but I thought I'd rather raise the issue first, before I start hacking.

**Comment by jtdaugherty** [comment]
Interesting!

Before I go into detail on those questions, can you describe how you would want this to work from a user's perspective? I ask because it might be possible to do this with a normal list and a little bit of application-side hacking.

For a multiple selection list I can imagine it being useful for, say, a file list where you need to select multiple files to attach to an e-mail, say. In that use case the user would use a single cursor to navigate the list and toggle the selection of a given entry before moving to other entries. Does that match what you have in mind?

**Comment by jtdaugherty** [comment]
In case my description does match what you want, I've modified `ListDemo.hs` to do this: https://gist.github.com/jtdaugherty/8c3eed3c4dae9e1c177886f96b5a31c3

The key here is that whether an item is selected in the list is just about the user's cursor position, and I can't think of how there could be more than one of those. But whether list items are "selected" in the sense of multiple selection is a matter of *state*, and in that modified version of the demo I've encoded that using an extra `Bool` in each list element. You can `diff` that version of `ListDemo.hs` against the one for `0.30` to see the changes.

**Comment by romanofski** [comment]
First of all sorry for not providing a good use case. You guessed absolutely right. We also want to select multiple mails and apply actions on them as described in purebred-mua/purebred#5.

... and yes, *facepalm* why have I not thought of this before. Of course, that makes sense. Perhaps I got confused with `listSelected` being exposed from the data type, without thinking that the selected state can easily be kept in the list as a tuple.

Many thanks @jtdaugherty !

**Comment by jtdaugherty** [comment]
No problem - I'm glad that approach works for you. The list selection is more about the selected index of the cursor, and beyond that it's up to the application to decide how to represent other kinds of list state. Good luck!
