### ISSUE TITLE
Layered `suspendAndResume`

### ISSUE THREAD

**Issue by angerman** [jtdaugherty/brick#151]
While playing with the forms api and still trying to find the right balance for my dialog, I wonder if we could have a layered suspend and resume. He idea is basically what @andrevdm suggested (and uses in andrevdm/hpass) just more native.

I believe the core idea here is to treat a dialog (or any form actually) simply as a new application. And then using suspend and resume to run the new application using the return value from Halt. This basically gets me pretty close to the Signatur I had in mind to begin with:

```
dialog :: InitialState -> FinalState
```

It also decouples the form logic from the application neatly.

However SuspendAndResume essentially drops the current app completely. Is rather have its picture retained as the bottom most layer and draw the “new” application on top. For interactivity purposes, I might want to keep drawing the “suspended” application though (e.g. a clock in the top right corner).

As such the hypothetical function should ideally just suspend the event handling, make the “new/temporary” application the event handler and resume the old suspended application once the “new/temporary” appliction halts.

**Comment by jtdaugherty** [comment]
That's an interesting proposal, and one I'm giving some thought.

Have you tried other approaches and found them objectionable? For example, this can be done right now by doing something like this:
* putting a `Form` in your application state
* adding a value of type `data Mode = Main | ShowingForm` to your application state
* when the mode is `Main`, show the main UI
* when the mode is `ShowingForm`, draw both the main UI and the form using layers
* use events in both modes to transition between them (and update the application state from the form state) as appropriate

One of the complications that arises for something like what you described is deciding how to deal with asynchronous non-input events (e.g. those coming over a custom event channel due to network traffic, say). If the underlying (calling) application is paused, those events pile up and can cause serious trouble. Using the approach I describe above still gives you the chance to handle those events even while the form is being drawn.

**Comment by angerman** [comment]
I’ll try to write some more comprehensive answer when I’m back home. I’m generally not much in favor of keeping global state around.

Ideally the suspendAndResume similar functionality would provide some form of event filter combinator, that would allow me to specify which events to “steal/transform” from the original app. I tried to illustrate the concurrent events topic with the clock, which was rather poor :-)

**Comment by jtdaugherty** [comment]
My worry about a general function to do this is that in order to give the user enough control over dealing with all possible behaviors, the API might have to be pretty tacky. I think I understand what you're looking for conceptually, though, and it's something I've dealt with in some applications.

To ensure that our discussion is as productive as possible, let's stay away from specific proposals/solutions here until the underlying concerns are agreed upon. That way we can put off worrying about *how* we're going to handle this until we are both sure we agree on *what* we are handling and *why*.

With that said, it sounds like putting an extra field in your application state is something you'd like to avoid. (It's not truly global, but I take your use of "global" to mean "in the application state of the calling application.") Put another way, it sounds like you are looking to improve the separation between the calling application of some event-driven workflow and the state that the workflow manages. Is that a good summary?

**Comment by angerman** [comment]
Alright, so I'm home now.
> - putting a Form in your application state

Yes, this is something I'd like to prevent, as the Form is not really part of my Application State (to me). Right now I have a `_dialog :: Maybe (From DialogInfo AppEvent Name)` in my application state, which feel (to me) just wrong. It does allow me to render the form if it's Just there. But the on/off via Maybe still feels very hacky; and it's also some form which is in my state now, instead of *just* the state of the form (we need this to keep form internal state...)

> - adding a value of type data Mode = Main | ShowingForm to your application state
> - when the mode is Main, show the main UI

Again, this kind of drags the Logic about the Form *into* the application. Whereas to me the Form should be mostly just a function.  How that arrives at obtaining the values (via user interaction, or some other computation) should not be of concern to my application.

> - when the mode is ShowingForm, draw both the main UI and the form using layers

This would definitely give me the layers I want, and allow event dispatching, it just couples the application and the form very tightly.  If I want to reuse the same form for multiple different parts of my app, I need to keep that "which part am I looking at right now" state somewhere, and I'd rather not have to do any bookkeeping of that state manually.

> - use events in both modes to transition between them (and update the application state from the form state) as appropriate

Yes. This is a concern!

**Comment by angerman** [comment]
So *what* do *I* want from this?
- Decouple my application.
- Allow me to compose multiple applications.
- Layer stacked applications on top of each other.

To be quite honest, I have not yet worked with any
(T)UI toolkit that would allow me to do just this.  I
have however tried to build similar concepts for iOS
and macOS (not always successfully though).

Again, IMO a dialog or form is just a function that
takes an initial state and returns a final (updated state).
If the form *may* return a value, the final state is a Maybe.

If this is decoupled from my main application, I could also
build a library of utility forms, that could be used trivially
in any other application.

It would not solve the monoidal widget composability issue
though (focus rings, ...). But at this level of applications, as
layers that seems less of a concern right now. As such I'd
prefer to tackle that separately.

**Comment by jtdaugherty** [comment]
Yeah, we're in agreement about some of the fundamentals: decoupling is good and reusability is good.

I've done some exploratory coding to see what this would take. What it comes down to in the current design is that the only way to do this is to have an event handler transition to control a new `App`. For that to work, input events must go to the new application only (which is reasonable, given the desired behavior). But it means that *custom* events of type `e` for the original application must continue to arrive, queued in the bounded channel, until the sender of those events blocks. It isn't possible to "keep running" the calling application underneath the new one because the call to the new application must provide a state transformation `s' -> s -> s` to take the final result of the form (say) of type `s'` and transform the calling application's state of type `s` and continue running. If we leave the underlying application running, this needs to turn into a new mechanism: the calling application must *asynchronously* run the new application and its halting state must be delivered to the caller asynchronously. That means `brick` needs to maintain an application stack and decide how to spread events over the stack. For example, resizes always need to go to all apps in the stack, but keyboard inputs need to always go to the top of the stack. And policies on how to deliver custom events will necessarily vary, so there is not One Right Way to do that.

What I concluded is that the current design would have to be entirely overhauled to accommodate this for various reasons, and that it would make reasoning about the programs monstrously difficult. The `App` abstraction is close to what would be needed for this, but it's not really intended to be chained/layered.

I agree that if it *could* be layered in the way you describe, that'd be pretty cool! But at the same time, I'm concerned that 1) overhauling the library to support this would take a lot of time, 2) it would result in breaking API changes for all existing brick applications, and 3) it still has some unanswered (and, I think, intractable) design questions that would compromise what has so far been a relatively straightforward API for dealing with control flow and events. One of the trade-offs of the current design is that while it requires the state to contain all the things the application will ever need, it tends to be very straightforward to understand how a brick program works. Composability boundaries have to be drawn in slightly different places than one might like (such as exposing a list of `s -> FormFieldState s e n` rather than as a `Form`, or exposing event handlers like `handleFormEvent` that still need to be dispatched to in the right spot).

With all of that said, I'm not opposed to having something like this in principle; I just don't think it's in the cards right now. If someone else came up with a proposal and/or patches for this, I'd be happy to consider it.

**Comment by angerman** [comment]
Thanks for trying this out. I agree that a rewrite would be very expensive especially as brick works for many as is already.

Couldn't we just try to build this on top of brick? And assume that there is a stack of Applications?
That of course raises some questions about the types through. As we have `App s e n`, and while I can imagine some transformation from `e1` to `e2`, and maybe even a lens for `s1` to `s2`, I don't see how the `n` could be unified. They seem to be rather application local to me. As such the stack would need to be built out of `StackableApp s e` erasing the `n` parameter.

Let's assume we have `StackableApps s e = [StackableApp s e]`.
- Rendering would be concatination of the layers.
- Event Dispatching is tricky, and would likely need an exclusivity filter (e.g. stop forwarding events that match this filter to the apps in the stack below. Mostly keyboard/Mouse event's I would imagine); multiplexing all other events across the stack. Maybe we'd want to also have an inclusivity
filter, such that the application can decide not to listen to events from it's parent application. But then again this might be part of the `e1` to `e2` transformer.

Now I would envision there to be a new primitive `push` (instead of `suspendAndResume`) that would take an `App s e n`, an event transformer `e1 -> e2` and a lens `s1 -> s2` where `e1`, and `s1` are the events and states of the parent application; `e2` and `s2` are the states of the `push`ed Application.

Now if the `push`ed application is `pop`ed (e.g. `halt`ed). It would use the lens to update the state in the parent application, and the stack is shrunk.

There is however one rather nasty problem, that is if the parent application concurrently updated the state the child application uses. I am willing to just ignore this case and put the burden on the developer to make sure that there are no data race conditions.

Any obvious issues I might run into, when trying to implement this?

**Comment by jtdaugherty** [comment]
> Couldn't we just try to build this on top of brick?
> They seem to be rather application local to me. As such the stack would need to be built out of StackableApp s e erasing the n parameter.

A big challenge with implementing this will be dealing with the resource name type of the different applications, and thus dealing with events. The resource name type is essentially local, but it is used throughout the brick core rendering loop which controls the terminal context, delivers events to the application, etc. The resource name type is used to report rendering extents, for example, which will be crucial for proper functioning of any app in the stack. But in a stack setting, the name types will differ, and the brick rendering engine needs to be aware of that type in order to maintain the extent information during rendering. So this might be the biggest obstacle to implementation.

> Let's assume we have `StackableApps s e = [StackableApp s e]`

I don't think we can construct that list, because the types will end up getting chained (not all child apps will use lenses into the top-level application's state). In general we'd have something like a parent app with state type `s` that calls child `C1` with state type `s2`, which could further call child app `C2` with state type `s3`. So if we have an application stack, I suspect only a GADT could be used to represent that and maintain the type information.

> Event Dispatching is tricky, and would likely need an exclusivity filter (e.g. stop forwarding events that match this filter to the apps in the stack below.

I'm really not keen on the idea of doing any event filtering as part of the API. I agree that if there's a transformer between event types, let that be the transformer's job. In other words, if the user is going to get into trouble, let it be because of their own code. :)

> Now if the pushed application is poped (e.g. halted). It would use the lens to update the state in the parent application, and the stack is shrunk.

This gets into the point I mentioned about whether the pushed application is run synchronously or not. If it's asynchronous, the parent keeps running and would need to get an event notifying it that the child is done. If it's synchronous, the approach you describe could work.

> There is however one rather nasty problem, that is if the parent application concurrently updated the state the child application uses.

This should just be ignored by the design. If the user *really* wants to do this, let them make the child application state a thing full of `TVar`s or other concurrency-friendly primitives that the parent also has access to. The worst that could happen then is deadlock. :)

> Any obvious issues I might run into, when trying to implement this?

One is that the parent application *must* be canonical when it comes to constructing the Vty library handle. Right now an app can be launched with `customMain` which gives it the ability to provide its own Vty handle constructor, but that won't be possible in a stacked application scenario where the terminal is already under control of the parent application. So this "push" operation needs to behave more like `simpleMain` where no custom control over the Vty handle is permitted. Furthermore, `EventM` exposes the current Vty handle to event handlers, and I'm inclined to say that it should *not* be possible for a child application to access that handle at all, since it could disable terminal modes crucial to the parent application's proper functioning.

**Comment by angerman** [comment]
I still have this on my mind. I haven’t been able to actually find a good solution yet.

Let’s close this for the time being and reopen once I have a plan :-)

**Comment by jtdaugherty** [comment]
That works for me. Thanks!
