### ISSUE TITLE
availHeight ctx includes border

### ISSUE THREAD

**Issue by jsynacek** [jtdaugherty/brick#152]
Consider the following:
``` haskell
module Main where

import Brick
import Brick.Main
import Brick.Widgets.Border

ui = Widget Greedy Greedy $ do
  ctx <- getContext
  let h = availHeight ctx
  render $ border $ vBox $ str <$> ["str widget " ++ n | n <- show <$> [1..h-2]]

main = simpleMain ui
```

Notice the `h-2` in the list comprehension. That still results in all the available space filled, instead of leaving two empty spaces, because the border is counted in. I know that if `border` goes before `Widget Greedy Greedy`, the available space is returned correctly, but I wonder. Is this something that can be "fixed"? I guess it shouldn't count the border if that's possible.

**Comment by jtdaugherty** [comment]
This is due to a bug in the test program: the problem is that the rendering context for `ui` uses all available screen height (`h` in this case), but `border` already does what you want (it restricts the height and width of its child by two in each dimension). The fix is to ask for the rendering context *in the place where it is needed*, i.e.,

```haskell
module Main where

import Brick
import Brick.Main
import Brick.Widgets.Border

ui :: Widget ()
ui = Widget Greedy Greedy $ do
      ctx <- getContext
      let h = availHeight ctx
      render $ vBox $ str <$> ["str widget " ++ n | n <- show <$> [1..h-2]]

main = simpleMain (border ui)
```
That program has the expected behavior, i.e., that `h-2` results in leaving some space. Since the `border` just wraps around the result, the entire bordered box is just two rows shorter than the terminal window. You can make the inner box use all available space (after the `border` constraint is applied) by just using `h` instead of `h-2`.

**Comment by jtdaugherty** [comment]
(If that addresses your problem, please close this ticket to let me know!)

**Comment by jsynacek** [comment]
Yes, thank you for the explanation.
