### ISSUE TITLE
Should editor support cancel operation and remove input?

### ISSUE THREAD

**Issue by romanofski** [jtdaugherty/brick#153]
For most use cases I've used the `Brick.Widgets.Edit` so far is for single line edits. Yet I wonder if it should be possible to cancel the input and delete what was typed.

Example:
* Editor contains an e-mail address
* User types in an additional address (or multiple) and realizes they're all wrong
* User presses Escape to avoid the entered text from being preserved

At the moment every character is entered and preserved. I suppose a scenario like the above would need some form of submitting/applying the entered text which is perhaps tricky with a multi-line editor.

I think if I want to support this case at the moment I'd have to keep a separate editor state in order to commit the entered text upon key press. If that would be supported by a brick widget, it would be more convenient  and perhaps even useful for forms.

**Comment by jtdaugherty** [comment]
I can absolutely see that kind of workflow being important, but I don't think it belongs in the built-in editor widget. In my view, this is application-specific functionality; whether such "cancel and return to previous state" behavior is appropriate will vary, and I'd rather not have the built-in editor function in a way that makes other applications accidentally provide a behavior they might not want. I'd also prefer not to add more behaviors to the editor that require configuration (which this would if it is potentially undesirable and also variable).

You might consider taking a look at [the new Forms API](https://hackage.haskell.org/package/brick-0.32.1/docs/Brick-Forms.html) if you haven't yet, since it would actually automate this to some degree, at least when it comes to distinguishing between a form's initial state and its current state, while giving you the chance to decide when to "commit" changes. I'd also be happy to assist with a non-Forms approach, too.

**Comment by romanofski** [comment]
@jtdaugherty Thanks for the clarification.

**Comment by jtdaugherty** [comment]
You're welcome - let me know if I can help!
