### ISSUE TITLE
Cursor Location and Wrapping

### ISSUE THREAD

**Issue by smallhadroncollider** [jtdaugherty/brick#155]
If I have an 80 character long string and I use `strWrap eightyCharacters` I lose the ability to place the cursor accurately with `showCursor`.

Say I want to place the cursor on the last character of the string. If I do `Location (80, 0)` it will come out on the first line 80 characters along. But depending on how the lines get broken up the final character could be on any line and position.

I don't have access to the newly wrapped string (do I?), so I can't break it with `lines` and then work out the position that way.

**Comment by jtdaugherty** [comment]
It's true that with `strWrap` you don't have access to the wrapped string, but if having access to the wrapped version would make things easier, then that can be done just by calling the wrapping routine yourself and then using `showCursor` on the appropriate line, e.g.,
```
import Text.Wrap
import Brick.Widgets.Core
import Brick.Types

wrapWithCursor :: Text -> Location -> Widget n
wrapWithCursor theText loc =
  Widget Greedy Fixed $ do
    ctx <- getContext
    let theLines = txt <$> wrapTextToLines defaultWrapSettings (ctx^.availWidthL) theText
        physicalLoc = ... -- Translate loc (in terms of non-wrapped text) into a wrapped version
        showCursorOnLine n ls = ... -- wrap the appropriate line with showCursor
    in vBox $ addCursorToLine n theLines
```

Now, doing it that way will still probably be painful as you have to figure out how to manage the cursor position in the presence of wrapping (i.e. you have to maintain a logical cursor position that the user controls, then translate that to physical at wrapping time). Doing that would entail wrapping the user's cursor line separately to track how it gets broken up to figure out which wrapped line should have the cursor, which I didn't do in the simpler example above.

Another approach you might consider would be to use an `Editor` widget, because it takes care of all of that stuff. A big difference is that an `Editor` doesn't wrap -- it scrolls instead -- so it'd result in a pretty different UI. But it supports a lot of Emacs/Readline-style editing keybindings out of the box, and it means you wouldn't have to deal with figuring out where to put the cursor.

Let me know if that helps!

**Comment by jtdaugherty** [comment]
(Above code example updated to fix a mistake.)

**Comment by smallhadroncollider** [comment]
I think for now I'll use my existing wrap code, might try and get it working as above at a later point.

Thanks.

**Comment by jtdaugherty** [comment]
Okay. Good luck!
