### ISSUE TITLE
Flashes of the terminal using `suspendAndResume`

### ISSUE THREAD

**Issue by smallhadroncollider** [jtdaugherty/brick#158]
I'm using `suspendAndResume` to write out to a Markdown file. This happens fairly regularly, but because of the way `suspendAndResume` works it briefly flashes up whatever was in the terminal before the app loaded. This can be quite unpleasant if it happens frequently.

Is it possible to have an option (`pauseAndResume`?) so that during IO the app just continues showing the app, instead of flashing up the terminal?

(PS - very close to getting Taskell working as before using Brick - has tidied the code up quite a bit and I think it could be even tidier after a refactor - thanks!)

**Comment by smallhadroncollider** [comment]
Sorry, just noticed that I can use `liftIO` inside `EventM`!

**Comment by jtdaugherty** [comment]
I'm glad you worked it out. `suspendAndResume` is for situations where you want to stop the Brick rendering / event loop and let some other application take over the terminal. For example, that's how [the matterhorn chat client](https://github.com/matterhorn-chat/matterhorn) invokes `$EDITOR` to let you edit your current chat message, and how it invokes terminal web browsers interactively. Conversely, it is indeed appropriate to use `liftIO` in your event handlers but two rules apply:
 * Blocking event handlers will cause the UI to be unresponsive since no redraw or event will be handled until your handler is done, so consider running your IO in a thread if it's long-running or resource-intensive.
 * Any `stdout` output produced in an event handler will poison the screen and cause artifacts.

**Comment by jtdaugherty** [comment]
(See also https://github.com/jtdaugherty/brick/blob/master/docs/guide.rst#id9)

**Comment by smallhadroncollider** [comment]
Thanks. I might look into threading at some point - for now it's fast enough not to be a problem.

The documentation is actually really clear about the uses of `suspendAndResume` and `liftIO` - I think I was just a littler overwhelmed initially and, still being new to Haskell, was just trying stuff out. As my knowledge of monads increases Brick starts to make more and more sense!

**Comment by jtdaugherty** [comment]
> Thanks. I might look into threading at some point - for now it's fast enough not to be a problem.

I mention threading not because of performance, but concurrency (blocking event handlers).

**Comment by smallhadroncollider** [comment]
Ah, yes, I see the difference.

I added a `forkIO` to my `writeFile` method, so hopefully that should do it?

**Comment by jtdaugherty** [comment]
That would be enough to prevent a long-running write from blocking your redraw, but:
* What happens if the thread raises an exception?
* What happens if the user triggers that *same* event again *before* that thread is done running?

**Comment by smallhadroncollider** [comment]
Good points. I'll need to do some more research into this stuff! Lots to learn still.
