### ISSUE TITLE
Size of widget in viewport

### ISSUE THREAD

**Issue by goodsoft** [jtdaugherty/brick#169]
I'm trying to implement a log widget which automatically scrolls to bottom when new messages arrive.
If user scrolls up manually, it should stop automatic scrolling until user scrolls all the way to the bottom.

To detect if user has scrolled all the way to the bottom, I add viewport's height to `vpTop` and compare the result with amount of log lines.
The problem is, I have to count log lines for this, which I want to avoid, because some log entries can be multiline, and I want this code to be re-used for other widgets.
I tried getting that widget's extent info, but it seems to be cropped to viewport and doesn't give any new info.

So am I missing something, or there really isn't any way to get uncropped height of widget in viewport?

**Comment by jtdaugherty** [comment]
This is a great question. There are a number of issues to consider here. As for your original question, the way to get the uncropped height of a viewport's contents is to wrap your contents in a custom widget that renders the contents and gets the height of the resulting image. An example of something similar to this is [hCenter](http://hackage.haskell.org/package/brick-0.36/docs/src/Brick.Widgets.Center.html#hCenter), which calls `render` to render the child widget being centered and then gets the child's width using
```
rWidth = result^.imageL.to imageWidth
```
Although this will allow you to get the dimensions of your viewport contents before they have been cropped, this won't be enough to implement a generic "scroll-to-the-end" viewport like you are describing because the viewport metadata accessible at the time of rendering (such as `vpTop`) is stale: it is the version as of the previous rendering, before any `EventM` scrolling requests have been processed.

In general, what you want to do is not possible with viewports, and it is also not going to perform well. Viewports require that the entire contents be rendered (i.e. your *entire* log) and then a window into those contents is managed by the viewport. This definitely seems conceptually like what you want, but the problem is that rendering Vty images is somewhat expensive, so this approach will not work well for large viewport contents.

The best way to handle this is to render your log message list from the bottom up, one (multi) line entry at a time, until you run out of room, and then stop. I've used this approach in the Matterhorn chat client, for example, which has the same needs:
* Render enough messages to fill the screen, most recent at the bottom
* When the user scrolls, let the user's scroll position determine the messages shown

This requires two modes:
* In "normal" mode, you just render entries bottom-up as described above.
* In "scrolling" mode, the messages *are* rendered in a viewport so the user can scroll.

This furthermore has some other implications:
* Scrolling keys like Page Up etc. need to "enter" scrolling mode by setting a flag in the application state.
* Some key like Esc needs to exit scrolling mode and return to normal mode.
* Since in scrolling mode the entries need to be rendered in a viewport, this *is* the time to render them all, and in this case use of the `cached` combinator will help with performance, with corresponding cache invalidation elsewhere.

I'm happy to write up a demo program that shows all of this in action, but I won't have time for that for a few days, probably. In the mean time I wanted to at least give you this overview of the problem.

**Comment by goodsoft** [comment]
Thank you for your elaborate answer, this answers my question.

I have read through related issues (#45, #97) and the Matterhorn code, so I have a general idea of your solution.
Though, I'm trying to avoid two scrolling modes (too many other modes in the app already), so I'll probably go with my initial solution and `cached` combinator.

**Comment by jtdaugherty** [comment]
Okay. Great!
