### ISSUE TITLE
Allow using custom FocusRing in Form

### ISSUE THREAD

**Issue by goodsoft** [jtdaugherty/brick#179]
I'm trying to show two separate forms with shared `Tab` cycle on one screen, and also include unrelated button widgets in the cycle.
As I see now, each form uses its own `FocusRing`, which can't be overriden and doesn't allow "escaping" the cycle.
It would be nice if I could create my own `FocusRing` with all needed widgets, and feed it to both forms.

**Comment by jtdaugherty** [comment]
Since focus rings are pure, it wouldn't be possible to get what you want by giving a focus ring to each form. Each form updates the focus ring (purely-functionally) in its event handler, so each form would have its own view of the focus ring rather than mutating a shared mutable data structure.

> I'm trying to show two separate forms with shared Tab cycle on one screen, and also include unrelated button widgets in the cycle.

For Brick's purposes, the definition of a "form" is "all the widgets that need to be related together in a tab cycle," with some helper code to do rendering, event dispatching, and input validation. I recommend merging this all into one `Form`, and then look at making a new button form field implementation so that your buttons are part of your form like everything else. The form API exposes enough functionality to implement custom form field types. I don't know how you want to lay your form out, though, so it might be difficult to get this to look the way you want. (Note that this approach does not preclude you from still using the two separate forms in other parts of your interface; that's just a matter of passing different subsets of form fields to `newForm` and modeling a corresponding form state.)

Put another way, if your application needs a different form abstraction, it might be necessary to implement your own. Brick forms are intended to satisfy the use case I described above with certain degrees of freedom but that might not be a good fit for your purposes.

Another more extreme option is to just not use forms, and just implement this directly. It's possible you could still re-use the form field state management functionality without using a `Form` itself, but some re-implementation of some of the Form internals will be necessary with this approach.

**Comment by goodsoft** [comment]
I was going to handle focus change myself, but, oh well, will resort to reimplementing form myself.
Too bad `renderFormFieldState` is not exported :(

**Comment by jtdaugherty** [comment]
I could export that - it would certainly seem to help, provided you're willing to handle event dispatching yourself, too.

**Comment by goodsoft** [comment]
Yeah, it would help a lot, I wouldn't need to copy-paste it in my project then :)
Thanks!

**Comment by jtdaugherty** [comment]
That's now done in `0.37.1`.

**Comment by goodsoft** [comment]
Thanks a lot!
