### ISSUE TITLE
How to put border over several checkboxes?

### ISSUE THREAD

**Issue by ChShersh** [jtdaugherty/brick#190]
I would like to draw a layout where I have several groups of checkboxes. To make visual representation of my TUI nicer, I would like to group checkboxes with the help of some border. So I want to draw something like below:

```
---Group 1---
| [ ] Foo 1 |
| [ ] Bar 1 |
-------------

---Group 2---
| [ ] Foo 2 |
| [ ] Bar 2 |
-------------
```

I see that `@@=` operator composes, but it can put only single `FormFieldSet` into the border:

https://github.com/jtdaugherty/brick/blob/618b00a8b120bdc647fbf7583891abf31808cea1/programs/FormDemo.hs#L73-L75

Is there any way to group multiple checkboxes inside border?

**Comment by jtdaugherty** [comment]
The forms API isn't intended to support this kind of presentation, unfortunately. With care, though, you could do it with joinable borders, if it is really important to you to get this working. I wouldn't recommend that approach, though, because it's going to be a mess. In case it would help, though, here's a modified version of the bundled `FormDemo.hs` that does this for a pair of adjacent fields.

[FormDemo.hs.txt](https://github.com/jtdaugherty/brick/files/2454134/FormDemo.hs.txt)
