### ISSUE TITLE
Export fields of `Form` data type

### ISSUE THREAD

**Issue by ChShersh** [jtdaugherty/brick#200]
In my use case I want to manipulate the state inside `Form` directly (to clear input fields or to fill them on-the-fly according to the content of other fields). I would really appreciate if `brick` can give such opportunity to users!

Current workaround is to get state from `Form` using `formState` function and then calling `newForm` again but this has at least one drawback: current focus is lost (and there's no way to set current focus of `Form` as well).

**Comment by jtdaugherty** [comment]
I can see why that would be useful. As far as the specific proposal is concerned, exposing the state isn't enough, because the fields get *built* from the state when you call `newForm`: that's how they get initialized. Even if you were to modify the form state `s` yourself, it would then be out of sync with the field states, and any changes to the form caused by input event handling would clobber your state changes.

The important thing here is that the field states are consistent with the underlying form state. Right now that is internally managed and is not exposed. I could expose a "smart" transformation that had a type signature like
```haskell
mapForm :: (s -> s) -> Form s e n -> Form s e n
```
that would internally take care of synchronizing the fields, but the only way to do that is to rebuild the fields from scratch, and that's equivalent to calling `newForm`.

Which brings me to another thought: would it be enough to just make it possible to set the form focus on a form? That way you can call `newForm` and then focus as you see fit. Granted, that approach (and the one outlined above) also suffer from another issue, which is that other state (such as editor cursor positions in editor fields) is lost, but without exposing a nastier API, there's no way around that.

I also need to mention that the form API is not intended to be all things to all use cases, and while I *am* happy to extend it in ways that make sense, there might come a point for some use cases where the form abstraction I've provided is just too simplistic. Just something to keep in mind.

Let me know if you think that exposing a function like `setFormFocus :: n -> Form s e n -> Form s e n` would help in your situation.

**Comment by jtdaugherty** [comment]
I've just uploaded `0.41.4` which includes `Brick.Forms.setFormFocus`. Thanks!
