### ISSUE TITLE
abstract list widget over container type

### ISSUE THREAD

**Issue by frasertweedale** [jtdaugherty/brick#201]
There are use cases (and I have one) where it would be useful to have the List widget use an underlying type other than `Vector`.  For example:

- lazily loading the list contents (e.g. long list that is expensive to generate); something like a `[Vector a]` would be better (linked list of chunks like `Data.ByteString.Lazy`).

- long lists where a lot of inserts/deletes occur (e.g. with `Vector`, `listInsert` and `listRemove` are *O(n)*); a tree structure such as `Data.Sequence.Seq` would be better

By abstracting brick's `List` implementation over the container type, we can let the user choose the implementation that works best for their use case.

If you agree this would be good, I am happy to do the work.

Some initial thoughts about how to do it:

- add a type class for `splitAt`, with constraint on `listRemove` and `listInsert` (not all applications need these behaviours so it's not really a problem if it's awkward to implement for some types)

- `drawListElements` relies on `length` which defeats the "lazy load" use case.  So I'd have to find a workaround for that.

- several other functions also use `length`; if these can't be easily worked around then it will suffice to document that the function forces the "spine" of the container.

- a lot of functions will grow `Foldable`/`Traversable` or `Semigroup`/`Monoid` constraints as needed.

**Comment by jtdaugherty** [comment]
I can definitely understand the appeal in having something like this.

The issue you mention about `length` is rather fundamental to what makes Brick's `List` perform well regardless of the number of elements in the underlying vector, so a workaround would have to take care of the performance concern some other way. The most important property of the `List` rendering function is that it renders at most `2 * N` list elements, where `N` elements are enough to fill the available space (depending on the item height given to the list constructor). That, combined with a clever Vty image translation, makes `List`s work in Brick viewports efficiently.

I don't feel especially good about trying to make list work well for lazy structures as long as the user doesn't use the API incorrectly (forcing, as you say). That, along with the length issue in the drawing function, bring me to conclude that this is probably a case where making a Brick built-in satisfy more use cases is not worthwhile. As tempting as it might be to assume that I made Brick's built-in widgets for all possible situations, that's not true, and there are definitely going to be times when re-implementing your own using a data structure that is better suited to your needs will be necessary. I definitely want to make sure that doesn't have to happen in the most common cases, which is why I made `List`, `Form`, `Dialog`, etc. But they are also really intended to be proofs of concept: if your needs are more sophisticated, then an implementation of a new type of state, event handler, and rendering function are definitely in order. And then my hope is that the library makes that relatively painless.

I say all of this to set the expectation that there is probably a limit to how generalized I think it makes sense to make the built-in widget types. In some cases it might be better to make a third-party `brick-betterlist` package or contribute a new module to the library. However, if you want to work on a patch, I'd be grateful for your time and I'd be glad to look at it. Some conditions of satisfaction for me include:

* The current data type API for lists is unchanged. (So if the `List` type variables change, it needs to be renamed and a new type synonym for a `List` in terms of `Vector` needs to be supplied.)
* The current user-facing function API is still supported, or if not, it is changed only minimally.
* The asymptotic performance of the list rendering function does not worsen.
* The degree to which direct mutation of a `List`'s underlying sequence is allowed to break `List` record-keeping is minimized, or at least very well documented. For example, if the `List` contains book-keeping metadata that needs to be consistent with the underlying sequence type, that needs to be abstracted away well enough that it's hard to get them out of sync due to e.g. direct transformation of the sequence through a lens. This is already slightly problematic with `List` and I don't want that to worsen either.

**Comment by frasertweedale** [comment]
Roger, thanks for setting expectations.  I'll chip away at it and hopefully have something for you in the next couple of weeks.

**Comment by frasertweedale** [comment]
@jtdaugherty I've made good progress and would like you review the work so far.  It is a WIP commit; expect a higher standard of documentation and commit message if you decide the changes are worth including in *brick*.

See commit: https://github.com/frasertweedale/brick/commit/e66ebeb055bdff0de96ee228d2232623bb337b31.

Notes:

- The `Split` type class provides `splitAt` for supported container types.  In the current patch only `V.Vector` has an instance in `Brick` itself.

- `Split` type class constraint was required for many more functions than expected.  On the plus side, it lets us avoid `length` in many cases, including `drawListElements`.

- AFAICT the asymptotic performance when using `V.Vector` as container is not changed in any possible use case.  If you have doubts, let us discuss.

- There is no worsening of the `List` record-keeping situation, that I can see.  Some operations are simplified based on use of total `slice` method from the `Split` type class.

- The general intuition is: if we can split the underlying sequential container structure around the focus, and if we can work with the "tail" lazily, then for most `List` operations we can get lazy loading.  Operations that force `length` are mentioned in the haddock.  I have tested it in *purebred* with a lazy vector type (see https://github.com/purebred-mua/purebred/commit/b67fb10464f38ad531e197b9d645ea3626bc4805).  It works.

- Let me know if any of my changes need further explanation i.e. that ought to have accompanying commentary in the source code.

- The `List'` data type name is a placeholder.  Let me know what you'd like.

- I'm ambivalent about whether to ship the abstract stuff in a separate module (e.g. `Brick.Widgets.List.Generalised` or whatever).  What would you like?  I see the benefits/drawbacks as:

  - We can keep `Brick.Widgets.List` API exactly unchanged, offering a type synonym (`List n e = List' n V.Vector e`) and less polymorphic versions of the generalised types as implemented in my patch.  A small amount of additional work,

  - or keep a single module, with more general types and both the `List'` type and `List` synonym.  In which case I'll enhance the haddock to mention the less polymorphic, `V.Vector`-based types.  Less code overall but perhaps a bit less user-friendly.

I'm pretty happy with this, and I don't think it's an especially intrusive change.  I hope we can work to land this in brick, as a separate module if desired.  Look forward to your feedback!

**Comment by jtdaugherty** [comment]
Great, thanks! I will look at it as soon as I have some time (probably in the next few days).

**Comment by frasertweedale** [comment]
@jtdaugherty FYI I have a new commit, based on top of https://github.com/jtdaugherty/brick/pull/205.
It is here: https://github.com/frasertweedale/brick/commit/7871536ca2f7c6a8c714f9ebdca3c0e3afbaa349

**Comment by jtdaugherty** [comment]
@frasertweedale I've left some comments, but overall it looks great to me. Thank you for writing this up!
