### ISSUE TITLE
Can not readLine

### ISSUE THREAD

**Issue by Kaligule** [jtdaugherty/brick#21]
brick causes some strage behaviour whith stdin
In this program (only little different from the hello world example) I read a String from stdin and display it.

```haskell
module Main where
import Brick.Widgets.Core (str)
import Brick.Main (simpleMain)
    
main :: IO ()
main = do
  --text <- return "Hello world"
  text <- getLine
  simpleMain . str $ text
```

No big deal, right?
Wenn I do 
```bash
ghc -threaded hello.hs
./hello
> hello you
```
everything works nicely ("hello you" is displayed).
But for
```bash
ghc -threaded hello.hs
echo "hello you" | ./hello
```
which should provide the same result, an error occurs (which wasn't noticed at compiletime, this never happend to me before): 
```
hello: getTerminalAttributes: illegal operation (Inappropriate ioctl for device)
```

I don't get problems when replacing the ```simpleMain . str``` with ```putStrLn```, so I guess this is a problem of brick. I am running ghc 7.10.2 on an Arch Linux and tried xterm, urxvt and termite (all with the same result.
Any idea what happens here?

**Comment by jtdaugherty** [comment]
I think the issue here is that invoking a program with standard input from the terminal is *not* the same as invoking a program with a pipe redirection.  In the former case, `stdin` is a file descriptor from the terminal that supports different `ioctl` system calls (such as the ones needed by `vty`), while the file descriptor opened by the shell for the pipe redirection is not a terminal device and will not support the same `ioctl` operations.  In the redirection case you get the error about an unsupported `ioctl` as a result.

**Comment by jtdaugherty** [comment]
Here is something that sheds a little light on what I'm talking about:

http://unix.stackexchange.com/questions/68712/how-to-detect-if-a-program-is-not-run-from-a-terminal

**Comment by jtdaugherty** [comment]
Here's another:

http://unix.stackexchange.com/questions/157852/echo-test-stty-echo-stty-standard-input-inappropriate-ioctl-for-device

**Comment by jtdaugherty** [comment]
So, to sum up: this isn't a `vty` or `brick` problem; it's purely a consequence of using a pipe where none should be used because `vty` (and therefore `brick`) programs expect `stdin` to be a terminal.

**Comment by Kaligule** [comment]
I see that this sort of thing could happen in a nonpure world of bash. Thanks for pointing that out. I am going to search for a workaround.

**Comment by simonmichael** [comment]
@Kaligule did you find a workaround ? We'd like to make this work:
```
$ cat some.file | hledger-ui -f-   # 1. take initial input from stdin
# 2. continue in normal interactive mode
```
I guess some shuffling of file handles could do it.

**Comment by Kaligule** [comment]
@simonmichael I never found a way to make it work, sorry.

**Comment by qcc-na** [comment]
@Kaligule @simonmichael  @jtdaugherty 
I'm super late to the party here but I found a way past this for anyone running into this who is willing to use `customMain` instead of `simpleMain`.   `customMain` allows you to override the underlying VTY configuration and give it the handle of the controlling terminal even when input originally comes from a pipe.  

Reading stdin using `getContents` will put the handle into a semi closed state.  Just read it, then close the handle.  After this, using `System.Posix.Terminal` , you can make a call to `getControllingTerminalName` then open that descriptor using `openFd` in the `System.Posix.IO.ByteString` module, and then pass that descriptor to `inputFd` on the VTY value passed to `customMain`.

Here is a crude example that requires the `unix`, `brick`, `vty`, `bytestring` packages:

You can test this with your shell: `$ echo 12345 | YourApp`

```
module Main where

import           Brick
import           Brick.BChan
import           Control.Monad
import qualified Data.ByteString.Char8 as C
import           Graphics.Vty
import           Graphics.Vty.Config
import           System.IO
import           System.Posix.IO.ByteString
import           System.Posix.Terminal
import           System.Posix.Types

data AppState = AppState String
type ResourceName = ()

main :: IO ()
main = do
  stdin' <- getContents
  print stdin' -- no lazy plz
  _ <- hClose stdin
  terminalName <- getControllingTerminalName
  terminalFd <- openFd (C.pack terminalName) ReadOnly Nothing (OpenFileFlags False False False False False)
  channel <- newBChan 1000
  initialVty <- buildVty terminalFd
  _          <- customMain initialVty (buildVty terminalFd) (Just channel) app (AppState stdin')
  return ()
  where
    buildVty :: Fd -> IO Vty
    buildVty terminalFd' = do
          vtyCfg <- standardIOConfig
          v      <- mkVty $ vtyCfg { inputFd = Just terminalFd' }
          when (supportsMode (outputIface v) Mouse) $ setMode (outputIface v) Mouse True
          when (supportsMode (outputIface v) BracketedPaste) $ setMode (outputIface v) BracketedPaste True
          return v

app :: App AppState e ResourceName
app = App draw neverShowCursor handleEvent startEvent attributeMap

draw :: AppState -> [Widget ResourceName]
draw (AppState stdin) = [ str stdin ]

handleEvent :: AppState -> BrickEvent ResourceName e -> EventM ResourceName (Next AppState)
handleEvent s e = continue s

startEvent :: AppState -> EventM ResourceName AppState
startEvent = return

attributeMap :: AppState -> AttrMap
attributeMap = const $ attrMap Graphics.Vty.defAttr []
```
