### ISSUE TITLE
Rendering a list with a separator correctly

### ISSUE THREAD

**Issue by mpickering** [jtdaugherty/brick#216]
I am trying to use `renderList` to render a list which has a `hBorder` between each element. Everything works fine apart from when the item is selected the border is also highlighted, I'm trying to stop the border being highlighted. 

It seemed that `forceAttr` was the right function to do this but the list still gets rendered using the selected style.

```
renderNote :: Bool -> IssueNoteResp -> Widget n                                 
renderNote _ i =                                                                
       vLimit 6 $ ignoreSel B.hBorder <=> body        
   where                                                                         
     -- Stop the border rendering in the selection                               
     ignoreSel = forceAttr "default"  
```

How can I overwrite the style properly to highlighting the border?

**Comment by mpickering** [comment]
I couldn't get it to work having it in the attribute map or not in the attribute map. I tried both ways.

**Comment by jtdaugherty** [comment]
I was able to get the desired behavior with `forceAttr listAttr` (the latter being from `Brick.Widgets.List`). Does that work for you?

**Comment by jtdaugherty** [comment]
(This assumes `listAttr` has been mapped in the attribute map.)

**Comment by mpickering** [comment]
Thanks, works for me. If you can think of a better way to achieve this then I would be glad to hear it but I couldn't think of anything that was as easy.

**Comment by jtdaugherty** [comment]
I think that's the best way. The `renderList` function [uses a default attribute for the selected item](http://hackage.haskell.org/package/brick-0.45/docs/src/Brick.Widgets.List.html#local-6989586621679330708) and the way to override that is to use `forceAttr` to prevent the renderer from falling back to other attributes (`listSelectedFocusedAttr` or `listSelectedAttr`, then `listAttr`, then the map's default attribute). Using `listAttr` as I did above at least ensures that your `hBorder`s will look the way you want if you change the `listAttr`.

Since it appears you have what you need, I'll close this, but feel free to re-open if I misunderstood or if something else comes up. Thanks!

**Comment by jtdaugherty** [comment]
Also: https://github.com/jtdaugherty/brick/commit/77293b548d27fe46d2b115d50f9743a821468df2
