### ISSUE TITLE
The contents of Editor's line is not refreshed when typing

### ISSUE THREAD

**Issue by amkhlv** [jtdaugherty/brick#218]
I wrote a minimal example of using the `Brick.Widgets.Edit` Editor:

[https://github.com/amkhlv/brick-example/blob/master/app/Main.hs](https://github.com/amkhlv/brick-example/blob/master/app/Main.hs)

But it does not seem to work... When I am typing the text, it does not appear in the Editor's input line.
However, in the end, after I press `Esc` , the text which I typed (``blindly'') __is__ printed correctly.
So, it seems that the widget is not auto-refreshed...
Am I doing something wrong?

**Comment by jtdaugherty** [comment]
The issue is that while you *do* properly dispatch the event to your state in `appEvent`, thereby updating the state of `cmdLine`, you don't actually use that state when rendering:
```haskell
com :: WEdit.Editor String Name
com =  WEdit.editor CommandLine (Just 1) ""

drawUI :: St -> [T.Widget Name]
drawUI st = [WEdit.renderEditor (str . unlines) True com]
```
The code above calls `com` to *build a brand-new editor state on each redraw*, hence the apparent lack of updates. The right code is
```haskell
drawUI :: St -> [T.Widget Name]
drawUI st = [WEdit.renderEditor (str . unlines) True (st^.cmdLine)]
```

**Comment by jtdaugherty** [comment]
This would also have been made apparent by building with `-Wall`, since `st` was unused in `drawUI`.

**Comment by amkhlv** [comment]
Ah, thank you! 
Yes, now it works!

**Comment by jtdaugherty** [comment]
Great!
