### ISSUE TITLE
listElementsL is not the right way to modify the contents of a list

### ISSUE THREAD

**Issue by mpickering** [jtdaugherty/brick#219]
I tried to use `listElementsL` to modify the contents of a list but the index into the vector can become out of bounds if you use it to reduce the number of elements in the list. I expected to find a function which did some more careful bounds checking when the internal list was updated. 

I don't think it should be exported from the API for this reason as the failures could be quite subtle.

In my application I defined the safe(?) and simple:

```
setListElements :: t e -> L.GenericList n t e - L.GenericList n t e             
setListElements els l =                                                         
   set L.listElementsL els                                                       
     . set L.listSelectedL (Just 0) $ l 
```

**Comment by jtdaugherty** [comment]
The function `listReplace` does such checking, so you might consider using that. Since `listElementsL` is a generated lens, I can't add Haddock for it as far as I know. I could add a safety note elsewhere in the documentation, though. I do think `listElementsL` is a fine way to modify lists if the caller understands what it does, so I'm not going to remove it from the exported API - but I definitely understand that this bit you and that at the very least the risk should be spelled out somewhere.

**Comment by jtdaugherty** [comment]
No problem - even I had to go hunting for `listReplace`. :) Its name does not really suggest that it's good for this, but I probably couldn't think of a better one at the time.
