### ISSUE TITLE
Change color of subset of text in widget?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [jtdaugherty/brick#232]
Based on [this issue](https://github.com/jtdaugherty/brick/issues/181) I suspect what I'm asking about is possible but I haven't figured it out. Suppose I wanted, for instance, to write all of a paragraph's hyperlinks in blue text, without wrapping each hyperlink in its own sub-widget. Can it be done?

**Comment by jtdaugherty** [comment]
I don't understand how the linked issue is related to the question here. Can you say a bit more about what you have tried and why it did not give you the result you wanted, etc.?

**Comment by JeffreyBenjaminBrown** [comment]
I'm drawing rectangles with static (not editable) text. I want some of the characters to be a different color. I have been using `Brick.Widgets.Core.str :: String -> Widget n`. I'll clearly have to change that, because the `String` type does not describe character color. I see that there's also `txt :: Data.Text.Text -> Widget n`, so if I could figure out how to encode color in a `Data.Text.Text` type, I'd be good -- but I haven't figured out how. Embarrassingly, after some reading around it's still not clear to me whether Unicode encompasses color.

**Comment by jtdaugherty** [comment]
Take a look at these resources:

https://github.com/jtdaugherty/brick/blob/master/docs/guide.rst#appattrmap-managing-attributes
https://github.com/jtdaugherty/brick/blob/master/docs/guide.rst#how-attributes-work
https://github.com/jtdaugherty/brick/blob/master/programs/AttrDemo.hs

**Comment by omelkonian** [comment]
I think the problem @JeffreyBenjaminBrown is pointing out it that it is always necessary to wrap your `String`/`Text` in a `Widget` to do styling, i.e. in order to use attributes you need to first use `Core.str`.

This is quite tedious and inefficient in some cases (e.g. when doing syntax highlighting in a programming language and you display large programs of that language), but I do not see any easier way to do this...

**Comment by jtdaugherty** [comment]
@omelkonian we'll see what @JeffreyBenjaminBrown says about whether that's his problem, but in the mean time, if efficiency is a great concern then one can always use [Brick.Widgets.Core.raw](http://hackage.haskell.org/package/brick-0.47/docs/Brick-Widgets-Core.html#v:raw) to embed a `Vty` `Image` directly. That will be faster if otherwise the image would have been made by a large collection of Brick strings. It has disadvantages, which is why it isn't the recommended approach, but it is provided since in some cases it makes the most sense.

**Comment by JeffreyBenjaminBrown** [comment]
I'm comfortable with attributes, and I'm not overly bothered by wrapping each newly-styled section of text in its own widget. The puzzle is that I need to somehow concatenate those widgets into a paragraph that wraps around the screen.

`strWrap` turns a list of characters into a `Widget` by wrapping them around the screen. If there some kind of `widgetWrap` function that did the same thing to a list of widgets, I'd know what to do. Does such a thing exist?

**Comment by jtdaugherty** [comment]
There is nothing in the library that wraps widgets. In general, because of how wrapping can interact with other application concerns during wrapping, that's an application-specific abstraction. I've had to implement it in other applications, and the wrapping is usually necessarily so interleaved with other concerns that I've never found a way to abstract it enough to generalize.

**Comment by JeffreyBenjaminBrown** [comment]
Interesting. So suppose one were implementing that kind of widget-wrapping. The widget `w` includes two words, "bark meow". If you detect that "meow" would spill off-screen if it were rendered on the same line as "bark", then you split the widget into two, and place the "meow"-containing widget on the next line. Correct?

If that's right, how do you determine whether a widget would be spilling off-screen?

**Comment by jtdaugherty** [comment]
First, I suggest we think of this as text wrapping, not widget wrapping, since widgets can be more than one line high and that will complicate the logic unnecessarily if your goal is to wrap text.

When I've done this I've done something like:

* Tokenize the input, for some definition of "token", usually splitting on whitespace. In this stage whitespace chunks must be preserved so they can be reintroduced. So must line breaks.
* Given a line width W, a list of input tokens T, and a current line accumulator L:
  * Take a token A from T.
  * If adding A to L would make it wider than W, either truncate (if that's your policy) or leave the token behind and start a new line, and repeat the procedure. If the token is a whitespace token, consider whether to bother adding it to the end of the current line, again considering its impact on the current line's length.
  * Otherwise append A to L and repeat the procedure.
  * If the token is a newline, start a new line.

As far as how to determine what W is, [the rendering context](https://github.com/jtdaugherty/brick/blob/master/docs/guide.rst#using-the-rendering-context) has that information.

Does that help?

**Comment by JeffreyBenjaminBrown** [comment]
It looks extremely helpful. I might not be able to try it out until the weekend. Thanks, Jon!

**Comment by jtdaugherty** [comment]
I go by Jonathan - but you're welcome! And please update here if you need anything else.

**Comment by JeffreyBenjaminBrown** [comment]
> I go by Jonathan

Roger :)

In the [rendering context docs](https://github.com/jtdaugherty/brick/blob/master/docs/guide.rst#using-the-rendering-context), the following exampmle:

```
myFill :: Char -> Widget n
myFill ch =
    Widget Greedy Greedy $ do
        ctx <- getContext
        let a = ctx^.attrL
        return $ Result (Graphics.Vty.charFill a ch (ctx^.availWidthL) (ctx^.availHeightL))
                        [] []
```

would not compile for me until I added a few arguments to `Result`:

```
myFill :: Char -> Widget n
myFill ch =
    Widget Greedy Greedy $ do
        ctx <- getContext
        let a = ctx^.attrL
        return $ Result (Graphics.Vty.charFill a ch (ctx^.availWidthL) (ctx^.availHeightL))
                        [] [] [] B.empty
```

**Comment by jtdaugherty** [comment]
Thanks, I'll update that!

**Comment by JeffreyBenjaminBrown** [comment]
Thanks, Jonathan!

The code I described in my previous comment illustrates how to get the rendering context from within a `RenderM` monad. I've grepped for "RenderM" in the Brick source code and it's barely present, particularly in a user-facing manner. Is `getContext` something that can only be used when making your own custom `Widget`, or is it something I could use, say, to determine the width available to an `hBox` before filling it?

**Comment by JeffreyBenjaminBrown** [comment]
After reading around in Vty more it looks just as easy to use `string`, `horizCat` and `vertCat` from `Graphics.Vty.Image`, to get the same effect that I would using stuff built into Brick.

**Comment by jtdaugherty** [comment]
`RenderM` is the monad in which rendering occurs. It's only user-facing if you're writing custom widgets. And yes, `getContext` is only usable there. You could look at the implementation of e.g. `txtWrap` for inspiration on how the context is used.
