### ISSUE TITLE
Right side of a custom `Widget` is too far to the left when in an `hBox`, but not otherwise.

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [jtdaugherty/brick#234]
(Context: This follows on the heels of [another issue](https://github.com/jtdaugherty/brick/issues/232) about changing text color in a widget, which became about wrapping a widget. The full code is available from [the Hode/ subfolder](https://github.com/JeffreyBenjaminBrown/hode/tree/d5e429b890f248bd8ce54ef1b5e5e81d8a0d3fa2/Hode) of the latest [branch of the Hode project](https://github.com/JeffreyBenjaminBrown/hode/tree/d5e429b890f248bd8ce54ef1b5e5e81d8a0d3fa2). (Those links are to a specific commit; I'll try to remember to update the links if I update the branch.) It's got very few dependencies, so `stack ghci` should load it pretty fast.)

I wrote some code that defines a `String`-like type that can have different attributes (Graphics.Vty.Attr values) along different portions:

```
type AttrString = [(String, V.Attr)]
```

and then a function which wraps an `AttrString` around the space allocated to the resulting `Widget`:

```
attrStringWrap ::  AttrString -> Widget n
attrStringWrap ss =
  Widget Greedy Fixed $ do
    ctx <- getContext
    let w = ctx^.availWidthL
        i :: V.Image = linesToImage $ toLines w ss
    return $ Result i [] [] [] B.empty

  where

  linesToImage :: [AttrString] -> V.Image
  linesToImage = let g (s,a) = V.string a s
    in V.vertCat . map (V.horizCat . map g)

  -- | PITFALL: `toLines` soes not consider the case in which a single
  -- `String` is too big to fit on one line. 
  -- In that case its right side will be truncated.
  toLines :: Int -> AttrString -> [AttrString]
  toLines maxWidth = reverse . map reverse . f 0 [] where
    f _       acc               []                  = acc
    f _       []                ((s,a):moreInput)   =
      f (length s) [[(s,a)]] moreInput
    f lineLen o@(line:moreOutput) ((s,a):moreInput) =
      let newLen = lineLen + length s
      in if newLen > maxWidth
         then f (length s) ([(s,a)]     :o)          moreInput
         else f newLen     (((s,a):line):moreOutput) moreInput
```

Then I wrote an abstract drawing function

```
showTwoAspects :: forall a b n.
     (b -> Widget n)
  -> (a -> b) -- ^ shows one aspect of an `a`
  -> (a -> b) -- ^ shows another
  -> [a]      -- ^ what to show
  -> Widget n
showTwoAspects b2w showLeft showRight =
  vBox . map showRow
  where
    showRow :: a -> Widget n
    showRow a = hBox [ b2w $ showLeft a
                     , b2w $ showRight a ]
```

If I provide `attrStringWrap` as the first argument to `showTwoAspects`, I get strange behavior: The text wraps correctly within the allocated space, but that space only occupies about half of the width of the screen, whereas I expected it to run all the way to the right.

If I change the definition of `showTwoAspects` so that it does not use an `hBox`, and does not draw the left portion, the behavior is as expected. `showOneAspect` does that:

```
showOneAspect :: forall a b n.
     (b -> Widget n)
  -> (a -> b) -- ^ ignored
  -> (a -> b) -- ^ shows an aspect of a
  -> [a]      -- ^ what to show
  -> Widget n
showOneAspect b2w _showLeft showRight =
  vBox . map showRow
  where
    showRow :: a -> Widget n
    showRow a = b2w $ showRight a
```

All the code described above is at `Hode.Lib`. Some functions that demonstrate how `showOneAspect` succeeds and `showTwoAspects` fails can be found at `Hode.Test`. An alternative (but as far as I can tell, equivalent) definition of `attrStringWrap`, and corresponding tests, can be found at `Hode.Test2`.

**Comment by jtdaugherty** [comment]
> If I provide attrStringWrap as the first argument to showTwoAspects, I get strange behavior: The text wraps correctly within the allocated space, but that space only occupies about half of the width of the screen, whereas I expected it to run all the way to the right.

This is almost certainly because your horizontal size policy for `attrStringWrap` is `Greedy` where it should instead be `Fixed`. `hBox` will allocate equal space to two children both with a `Greedy` size policy. If one is `Fixed` and the other is not, the `Fixed` child renders first to determine the space left to the `Greedy` child.

**Comment by jtdaugherty** [comment]
You might have trouble if you use `Fixed` if there is enough text in the left column, though: if there is enough to take up all available horizontal space then the right column of the `hBox` will effectively *not get rendered at all*. The `Greedy` policy is probably the right policy to use (judging by the library's `txtWrapWith`), so I think the question is probably more about how you want your layout to work in the presence of that.

What I'm wondering is: what kind of UI layout are you trying to achieve, where this text wrapping occurs within that? It seems like you have the wrapping itself implemented well enough, so this isn't really about that. Are you looking for a two-column layout?

**Comment by JeffreyBenjaminBrown** [comment]
It's ... solved? Updated (subfolder of) repo [here](https://github.com/JeffreyBenjaminBrown/hode/tree/d5e429b890f248bd8ce54ef1b5e5e81d8a0d3fa2/Hode).

`Brick.Core.txtWrapWith` is defined as `Widget Greedy Fixed x` for a certain `x`. When I changed my `attrStringWrap` implementation to instead use `Widget Fixed Greedy`, it does what I was hoping for. Which is wonderful ... but what's going on? As far as I can tell, my `attrStringWrap` widget behaves just like `strWrap` (the specialization of `textWrapWith` that I'm familiar with), so shouldn't it use the same policy?

> Are you looking for a two-column layout?

Roughly, yes. The left hand side is currently a single column, but will eventually be a collection of columns. The right hand side displays a tree. A row consists of one node from the tree, paired with some numbers describing that node. Each number gets displayed in one of the columns. The columns are fixed width, and the tree nodes take up the majority of the screen.

> hBox will allocate equal space to two children both with a Greedy size policy.

That's not what I'm seeing -- the left-side widgets take as little space as possible to render, just enough to display the number, whether I use `Widget Fixed Greedy` or `Widget Greedy Fixed`. In one case the widget on the right uses roughly half the remaining space, and in the other case it uses all of it. But both left and right widgets are the same `attrStringWrap` widget, just given different data.

**Comment by jtdaugherty** [comment]
> That's not what I'm seeing -- the left-side widgets take as little space as possible to render, just enough to display the number, whether I use Widget Fixed Greedy or Widget Greedy Fixed.

Screenshots would be helpful for reference; I don't have time to build your application and run it, and I also don't have time to look at the code, so I'd like to stick to just small functions to isolate the issues we're discussing.

But to be clear, the size policy used is a *description* of the behavior of the widget, meaning that if you declare a Greedy horizontal policy, that means other widgets can assume that the body of the widget actually behaves that way. If all you do is render a number, then yes, there will be no appearance of greed in the horizontal dimension because the widget body is not rendering its content in terms of the available width. Does that make sense? So in other words, the Greedy/Fixed values are *hints*, nothing more, and those hints need to be consistent with the widget's rendering behavior.

**Comment by jtdaugherty** [comment]
> Brick.Core.txtWrapWith is defined as Widget Greedy Fixed x for a certain x. When I changed my attrStringWrap implementation to instead use Widget Fixed Greedy, it does what I was hoping for. 

And this does what you want because of how it affects `hBox`, and nothing more. But it only appears to work: a `Fixed` horizontal policy for text wrapping will be the wrong hint for the reason I described above about not rendering a second column at all in a two-column layout, *provided that the left column has enough text to fill the width of the `hBox`*, due to how the `hBox` layout algorithm works. To wit: try `wrap "Foo bar baz" <+> wrap "Blah"` in an area no wider than 11 columns. The `Blah` will not appear *at all* if `wrap` declares a `Fixed` horizontal policy because the left hand widget gets rendered first and *any available space* (then 0 columns) is allocated to the right side.

**Comment by JeffreyBenjaminBrown** [comment]
I've whittled the demonstration down to 45 lines of code (minus import statements, comments, pragmas, empty lines.) in a single file, attached below. But first, the pictures you requested:

The function `test` takes two `Brick.Types.Size` arguments, and a third argument that effectively says, for each row, whether to render both sides or just the right side. If both are rendered, they are wrapped together in an `hBox`; if just one is rendered, it is not so wrapped.

The order of the two `Size` arguments corresponds to their order in `Brick.Types.Widget` -- horizontal first, vertical second.

`test Fixed Greedy showBothSides` draws what I want:

![test Fixed Greedy showBothSides](https://user-images.githubusercontent.com/8900687/59554603-10583680-8f6b-11e9-86f7-0afbece0a094.png)

`test Greedy Fixed showBothSides` is just like the previous command, but with the size arguments swapped. It is what I was initially trying, and corresponds to how the `Size` arguments are used in `Brick.Widgets.Core.txtWrapWith`. It causes the widgets on the right side of the `hBox` to wrap before reaching the right side of the screen:

![test Greedy Fixed showBothSides](https://user-images.githubusercontent.com/8900687/59554609-2108ac80-8f6b-11e9-8f5c-95b9eb4535ca.png)

Notice in the previous image that the total amount of horizontal space allocated to the right side is roughly equal in the two rows. In the second row, which has a longer string to show in the left cell, the boundary of the right cell is closer to the right side of the screen.

If I show only the right side,  the size policy doesn't seem to matter; these two commands:

```
test Fixed Greedy showRightSide
test Greedy Fixed showRightSide
```

both give the same result -- they both wrap around the full length of the screen as hoped for:

![test Greedy Fixed showRightSide](https://user-images.githubusercontent.com/8900687/59554616-4ac1d380-8f6b-11e9-9610-e82ef4e4ad60.png)

```haskell
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TupleSections #-}

module Hode.Simpler where

import           Lens.Micro
import           Brick.Util (on)
import           Brick.Types hiding (render)
import           Brick.Widgets.Core
import qualified Brick.BorderMap as B
import qualified Brick.Main      as B
import qualified Graphics.Vty as V


-- | Like `String`, but font can vary across it.
type AttrString = [(String, V.Attr)]

-- | Something to display
type Row = ( [String]    -- ^ shown on the left
           , [String] ) -- ^ show on the right

test :: Size -> Size
     -> (Size -> Size -> [Row] -> Widget ())
     -> IO ()
test s t render = B.simpleMain $ render s t rows

showRightSide, showBothSides :: Size -> Size -> [Row] -> Widget ()
showRightSide = showRows False
showBothSides = showRows True

showRows :: Bool -- ^ Whether to show left side. (Right side always shows.)
         -> Size -> Size -> [Row] -> Widget ()
showRows showLeft s t = vBox . map showRow where
  toAttrString :: V.Attr -> [String] -> AttrString
  toAttrString a = map (, a)
  showRow :: Row -> Widget n
  showRow (l,r) = let w = attrStringWrap s t
    in case showLeft of
         True  -> hBox [ w $ toAttrString (V.red `on` V.blue) l
                       , w $ toAttrString (V.blue `on` V.red) r ]
         False ->        w $ toAttrString (V.blue `on` V.red) r

rows :: [Row]
rows = [ (["10"],  replicate 32 " Hi! " )
       , (["123456789012345"], replicate 18  " What's up?  ") ]

attrStringWrap ::  Size -> Size -> AttrString -> Widget n
attrStringWrap hSize0 vSize0 content =
  Widget hSize0 vSize0 $ do
    ctx <- getContext
    let w = ctx^.availWidthL
        i :: V.Image = linesToImage $ splitLines w content
    return $ Result i [] [] [] B.empty
  where

  linesToImage :: [AttrString] -> V.Image
  linesToImage = let g (s,a) = V.string a s
    in V.vertCat . map (V.horizCat . map g)

  -- | PITFALL: Does not consider the case in which a single token
  -- does not fit on one line. Its right side will be truncated.
  splitLines :: Int -> AttrString -> [AttrString]
  splitLines maxWidth = reverse . map reverse . f 0 [] where
    f _       acc               []                  = acc
    f _       []                ((s,a):moreInput)   =
      f (length s) [[(s,a)]] moreInput
    f lineLen o@(line:moreOutput) ((s,a):moreInput) =
      let newLen = lineLen + length s
      in if newLen > maxWidth
         then f (length s) ([(s,a)]     :o)          moreInput
         else f newLen     (((s,a):line):moreOutput) moreInput
```

**Comment by jtdaugherty** [comment]
I really appreciate you going to the trouble of getting these screenshots and outlining the various cases and behaviors. What I'm still confused about is what behavior you want that you are not getting. You may be saying that, but if so, I can't tell for all of the other detail.

Based on the comments in this ticket, I'm not sure whether you understand what the size parameters do and how they govern the box layouts. That could probably be helped by better documentation, but creating an *even more minimal* demonstration program that exhibits the behavior you consider undesirable or unexpected would help me spot the place where either you are misunderstanding or the library has a bug. If the problem you're having stems from the size parameters and the box layout algorithm, then it ought to be possible to write a *very* small program that shows *one* behavior that is the undesirable one, along with a clear description of what would be desirable. And if that's true, the program should not have to do anything with wrapping at all to illustrate the problem.

So it would be helpful for me at this point if you could provide:

* a concise, high-level explanation of what you want to accomplish, *not* including any information about what you have tried or whether it worked, and
* an essential demonstration of where the library is making it hard or impossible to get what you want.

**Comment by jtdaugherty** [comment]
@JeffreyBenjaminBrown this has been idle for a bit so I wanted to check - is this still something you want to pursue?

**Comment by JeffreyBenjaminBrown** [comment]
Sorry for going AWOL -- I'm taking a little break from the project. I'll be back in a week or two. Thanks!

**Comment by jtdaugherty** [comment]
Thanks for the update. I just wanted to make sure we were keeping this moving.

**Comment by JeffreyBenjaminBrown** [comment]
> What I'm still confused about is what behavior you want that you are not getting. You may be saying that, but if so, I can't tell for all of the other detail.

At this point I've got the behavior I want, I think, by setting both size parameters to Fixed. I just want to understand why that works. Quoting `Brick.Types`:
```
Fixed widgets take up the same amount of space no matter how much they are given (non-greedy).

Greedy widgets take up all the space they are given.
```

The first picture I sent, with `hSize == Fixed` and `vSize == Greedy`, does what I want: it takes up all the horizontal space available, and no more, and it extends vertically only as far as necessary. But that seems like what you would get with `hSize == Greedy` and `vSize == Fixed`, not vice-versa.

(I didn't draw this, but `hSize == vSize == Fixed` gives exactly the same behavior, and moreover I can scroll across it vertically in a viewport, so that's what I've ended up using.)

**Comment by jtdaugherty** [comment]
> Fixed widgets take up the same amount of space no matter how much they are given (non-greedy).
> Greedy widgets take up all the space they are given.

Unfortunately this is not exactly right, but it is close. A better way to put this would be

> Widgets with a `Fixed` policy are declaring that they will use no more than the available space given. Widgets with a `Greedy` policy are declaring that they will use all available space given.

In particular, these hints control how the `hBox` and `vBox` combinators render their children, and that is the *only* place in the library where the hints are used. And because the box combinators use those hints to do layout, there is more to the story, because the box layout combinators do different things depending on whether their children exhibit different combinations of hints. Lastly, the hints are just hints: the widgets that declare those hints are not in any way forced to abide by them, so they can be wrong, and they can lead to (sometimes) surprising or (sometimes) correct behavior depending on the situation. My aim is for the [user guide](https://github.com/jtdaugherty/brick/blob/master/docs/guide.rst#id20) to document this and more, so I hope the section I've linked to here does indeed help. And I can improve the description in the Haddock, too.

In your case, it is probably safe to use `Fixed` for both hints, but there may be situations where that does not yield the layout you want, because the box combinators render `Fixed`-hinted children *before allocating space for `Greedy` ones*, meaning that if your text wrapping uses all available space, there will be zero columns left for the other children (which IIRC you even saw early on in this ticket). That's why `Greedy` is probably going to be the right horizontal hint in the long run; the thing about a `Greedy` child is that if you dislike that behavior then you can always `hLimit` it under the conditions where it's objectionable, thus turning it into a `Fixed`-width box element of the desired width. All of this is why the library's `txtWrapWith` uses `Greedy` for its horizontal hint.

**Comment by JeffreyBenjaminBrown** [comment]
Man, complex stuff.

> Widgets with a Greedy policy are declaring that they will use all available space given.

If that's true, why is it that when I create a `vBox` with two vertically-greedy widgets, they both are displayed? Shouldn't the first one to display use up all the space?

> Greedy is probably going to be the right horizontal hint in the long run

That's what I thought too, and the first thing I tried. But when I use `hSize = Greedy` and `vSize = Fixed`, I get my second picture, in which the text-wrapping boxes are only about half the width of the screen, and leave a lot of space on the right side.

**Comment by jtdaugherty** [comment]
> If that's true, why is it that when I create a vBox with two vertically-greedy widgets, they both are displayed? Shouldn't the first one to display use up all the space?

Because it says *space given*, and the `vBox` only gives each one half the available space when both children are `Greedy`. This is also why you got the behavior in your second picture.

**Comment by jtdaugherty** [comment]
Also, another clarification: a box allocates space to its children equally if they're all `Greedy`, and I said "half" above but it is actually `1/n`th of the space for `n` children, with half being the case for two children.

**Comment by JeffreyBenjaminBrown** [comment]
> a box allocates space to its children equally if they're all Greedy

With `(hSize, vSize) == (Fixed, Greedy)` I get the first picture, which gives more space to the second item than the first.

> This is also why you got the behavior in your second picture.

I still don't understand. The second picture is what comes from `(hSize, vSize) == (Greedy, Fixed)`. Why does it leave empty space on the right?

**Comment by jtdaugherty** [comment]
> I still don't understand. The second picture is what comes from (hSize, vSize) == (Greedy, Fixed). Why does it leave empty space on the right?

I'm trying to work through this without going back to your original code, because there is too much there for me to use it to explain what is going on. I want to stick to the simplest possible case. So first, ignore the vertical size hint. It is not having an effect on this behavior since we're talking about an `hBox`. Second, I'll outline the box layout algorithm and see if that helps you understand the outcome you're getting:

Horizontal box layout for child widget list CS in an area of width W:
* Let (F, G) = partitioning of CS into all of the widgets with a `Fixed` horizontal size hint and `Greedy` hint, respectively.
* Let FI = the Vty image renderings of F, with the first allowed to be W columns wide, the second W - (width of the first), etc.
* Let R = the remaining amount of space in W left over after subtracting the widths of FI, i.e., W - SUM(map imageWidth FI). This can be zero if all of the fixed-sized widgets consumed all of the available space. In this sense Greedy can be thought of as "low priority" - use all of whatever is left after rendering Fixed children.
* Let K = R / LENGTH(G), i.e., an even distribution of remaining width for all of the greedy widgets.
* (**) Let KI = the Vty image renders of G, with each allowed to use K columns of space.
* Let FINAL = the images KI and FI rearranged so that they appear in the order in which the widgets were provided to the box function.
* Return concat FINAL (i.e. horizontal Vty image concatenation in this case).

It is important to point out that in the bullet labeled `**`, the resulting widgets are *expected* to use the available space they're given (because of the Greedy hint they advertise), and if they don't, the entire box will not use W columns.

**Comment by jtdaugherty** [comment]
I hope that the outline above also helps illustrate why a single widget's hints are only important because of how they interact with the box layout algorithm in the presence of another widget.

**Comment by jtdaugherty** [comment]
I also thought it might be helpful to illustrate the behavior that I think you're seeing by working through a small concrete example.

Let's say you have a function `f` that just renders a string, *but* it advertises a `Greedy` horizontal hint.
```haskell
f :: String -> Widget n
f s = Widget Greedy Fixed $ do
    render $ str s
```
And then let's say you want to render `myUI`:
```haskell
myUI :: Widget n
myUI = f "0123456789" <+> fill 'X'
```
Let's assume that the terminal width is 50 columns. The `hBox` proceeds as follows:
* Both children are `Greedy`, so divide up the available space (50 / 2 = 25) and render each child with 25 columns' available width.
* Horizontally concatenate the results.

Now because `f` renders its contents irrespective of the available width, the result of rendering `f` will always be at most 10 columns. But we gave it 25, so 15 columns are unused. When the `fill` is rendered, it will fill 25 columns (and whatever rows) with `X`. The resulting concatenation will be 25 + 10 = 35 columns wide, leaving 15 columns of unused space on the right side of the fill. The broken contract here is that `f` *should always return something that is exactly as wide as it was allowed to be*, so in this case, 25 columns. Usually that is resolved by adding padding (in this case, `f` should pad the result of rendering the `str`).

This discussion has made me realize that while the `Greedy` hint for the library's `txtWrapWith` function is right, the implementation of `txtWrapWith` does not actually obey the contract above. It does not apply padding in the event that it was given more room than was needed for its text content. So that's worth fixing!

**Comment by jtdaugherty** [comment]
Relevant to my last comment: https://github.com/jtdaugherty/brick/commit/926d317c46b19d4e576748891a1702080287aa03

**Comment by jtdaugherty** [comment]
See also https://github.com/jtdaugherty/brick/commit/8e7c4a99ebdbf903a720bf0730659e13f612be11

**Comment by jtdaugherty** [comment]
@JeffreyBenjaminBrown I'm going to close this due to staleness. Please feel free to re-open if this becomes a hot topic for you again.
