### ISSUE TITLE
strWrap causes an exception when used to wrap an Editor in renderEditor

### ISSUE THREAD

**Issue by ta0kira** [jtdaugherty/brick#235]
I'd like to have both word-wrap and dynamic sizing with an `Editor`.

Exception when attempting to render using `strWrap . unlines` (for an `Editor String n`):

```
***Exception*** tried to embed an infinite-width or infinite-height widget in 'Both' type viewport Label "Edit Note"
CallStack (from HasCallStack):
  error, called at src/Brick/Widgets/Core.hs:1039:25 in brick-0.47-HSnX4JuZmLyGL3hPAGNs0u:Brick.Widgets.Core
```

This exception happens even if the text buffer is empty.

I don't get the exception if I apply `hLimit` after `strWrap` in the render function, but that fixes the size independently of the terminal size, and it also has very strange effects on the cursor.

I've also tried `hLimitPercent 100`, which gets rid of the exception but then wrapping doesn't actually happen.

The issue might be that the viewport in `renderEditor` always uses `Both`.

(It's also interesting that this exception _doesn't_ occur with `str . unlines`; the width of `strWrap x` should probably be `<=` the width of `str x`. That might be a second issue?)

**Comment by jtdaugherty** [comment]
Thanks for the report!

> I'd like to have both word-wrap and dynamic sizing with an Editor.

This will require making your own editor implementation. The alternative is a trick hack approach that would probably be to wrap the text while it is being edited, and that depends on knowing the editor width (which can't be known in advance unless you constrain it yourself). I don't recommend this approach, though - it's going to be too brittle. Besides, it violates the cursor maintenance assumption I'll mention below.

> Exception when attempting to render using strWrap . unlines (for an Editor String n):

This is because the editor uses a viewport with the `Both` type, as you have already found, and `strWrap` is unconstrained horizontally (on purpose). The requirement being violated here is that you can't use a viewport with horizontal scrolling (as in the `Editor` case) with content with infinite width (as in the `strWrap` case due to its `Greedy` horizontal size hint). This is also why you get the exception regardless of the content; the issue is that the viewport widget cannot reliably lay out its content if it cannot measure its width (and the `Greedy` size hint on `strWrap` means that the width is dependent on the available width, and that width here is effectively unlimited).

> I don't get the exception if I apply hLimit after strWrap in the render function, but that fixes the size independently of the terminal size, and it also has very strange effects on the cursor.

Yeah, that makes sense; I didn't document these kinds of details well enough, but the editor's rendering function should essentially preserve the structure of the rendered text line-by-line and column-by-column if the cursor logic is to be maintained. The use of `hLimit` avoids the exception because it turns `strWrap`'s `Greedy` hint into a `Fixed` hint (see the `hLimit` source) but has effects on the cursor because the editor assumes it knows the text layout and by limiting and then wrapping, you've changed the text layout *at render time*. That change in layout is not communicated back to the event handler for the editor's cursor movement, which is where the layout of the text needs to be known to determine proper cursor movement.

> It's also interesting that this exception doesn't occur with str . unlines

This is because `str` uses `Fixed` for both its size hints, so the viewport can reliably determine the resulting image's size to know how to scroll it.

> the width of strWrap x should probably be <= the width of str x

Whether this should be true depends on the rendering context. `str` will truncate its content if asked to draw in an area that doesn't fit the text. `strWrap` will wrap, but also truncate, depending on the situation. I'm not sure if that is a good response to this comment, though.

**Comment by ta0kira** [comment]
It sounds like wrapping also wouldn't be straightforward with a fixed-width version of the same `Editor`. Is the main issue separating this from the wrapping of static text the handling of the cursor, or the handling of input events in general?

**Comment by jtdaugherty** [comment]
The main issue is the former: the editor needs to know the visual layout of the text to make sense of cursor movements, and that means that the rendering needs to match what is known at event handing time.

**Comment by jtdaugherty** [comment]
Hi @ta0kira - it's been a few weeks and I wanted to check on this ticket. Is there still something outstanding we need to discuss further?

**Comment by ta0kira** [comment]
I think this is resolved. Thanks!

**Comment by ta0kira** [comment]
Hi @jtdaugherty,

I finally got around to creating an editor widget with line wrapping. I'm reopening this issue just for visibility purposes, in case you (or others) have any comments. Feel free to close this again.

The repo for the editor is here: https://github.com/ta0kira/wrapping-editor.

**Comment by jtdaugherty** [comment]
That's great, @ta0kira! Just one observation: it's a little strange but the links to Brick in your README link to the Brick User Guide, rather than the GitHub repo main page. Was that deliberate?

**Comment by jtdaugherty** [comment]
Also, I added a link to your project from the Brick README.

**Comment by jtdaugherty** [comment]
One more thing: the README says "a simple text-editing widget for fixed-size fonts" which makes it sound like a *font editor*, not *an editor that displays text in a fixed-width font manner*, i.e., a terminal.

**Comment by ta0kira** [comment]
Thanks! I updated my project description and the links to Brick.

Feel free to close this issue again unless you want to continue the discussion here.

**Comment by jtdaugherty** [comment]
Okay, will do. Thanks for letting me know about your project!
