### ISSUE TITLE
Implementing a search-as-you-type

### ISSUE THREAD

**Issue by chrisdone** [jtdaugherty/brick#239]
Is there an example of a search-as-you-type?

I took a crack at doing it with a text editor plus a list editor, but found there wasn't an obvious path of how to update the results in the list editor when the user types. I seemed to be steered in the direction of making a `newForm` every time, because I didn't see a way to update a form's state directly, and a list editor's list of elements is informed by its state. However, is that the proper way to do it? I tried something like this:

```haskell
form' <- Brick.handleFormEvent ev (stateInputForm state)
Brick.continue
  state
    { stateInputForm =
        maybe
          id
          Brick.setFormFocus
          (Brick.focusGetCurrent (Brick.formFocus form'))
          (makeInputForm (Brick.formState form') { inputFormCompletions = newCompletions })
    }
```

Which sort of works. But it seems like a bit awkward. Plus the having to remember to handle focus is also a bit worrying.

**Comment by jtdaugherty** [comment]
If you want to use the Form API to do this, then I think your approach (making a new form on every event) might be the only way. And as you have found, that suffers from some issues, since the form focus will get reset (so you'll need to call `setFormFocus`) and the widget states will get reset (such as editor input cursor position).

There isn't a way to update the form state directly because doing so would break the form logic; the form API maintains some metadata alongside the form state, and updating the form state could put it in disagreement with the metadata.

If it were me, I'd just not use the Form API for this at all. The Form API is provided as a convenience for simple forms, but it is not going to work for more complex use cases where more control is needed. I think this is one of those cases.

**Comment by jtdaugherty** [comment]
(Also, I would be happy to improve the Form documentation to more clearly outline the kinds of cases it's intended to make painless.)

**Comment by chrisdone** [comment]
OK, great. I was initially considering doing this widget manually, but I didn't want to reproduce already done work without trying with the form API. 

If that's your recommendation then I feel comfortable proceeding in that direction. :+1: 

Thanks! :metal:

**Comment by jtdaugherty** [comment]
Great!
