### ISSUE TITLE
Brick over a custom monad stack?

### ISSUE THREAD

**Issue by isovector** [jtdaugherty/brick#240]
I'd like to run `brick` over a set of effects managed by `polysemy`, but `brick` seems to be pretty baked into using `IO`. Is there some trick to getting a `EventMT` transformer?

**Comment by jtdaugherty** [comment]
Thanks for the ticket and for the patch!

I can definitely see the appeal in the change. Looking over the patch, the extra type variable in various places gives me some concern. Frankly I already thought the API was getting a bit unwieldy, and adding another type variable (sometimes multiple times in the same type) just makes that existing problem worse. That, combined with the fact that nobody else has requested this (and I have not needed it), lead me to be neutral or slightly opposed to this change, at least in its current form.

The only thing I can think of that would minimize the pain of this change would be to make it 100% non-breaking by renaming all involved types (e.g. `App`, `Next`, `EventM`, etc.) so that type aliases with the old names can be reintroduced and default `m` to `IO`. That would at least hide the extra type variable when the user doesn't care to provide it, and it would ensure that existing programs won't break if this gets introduced. I don't love the idea because it causes a proliferation of types and aliases that could get confusing, but I can't think of another way to reduce the impact of the extra variable in the case where `IO` is the natural choice of `m`. What do you think?

**Comment by isovector** [comment]
@jtdaugherty that sounds like a reasonable approach to me. I'd be happy to put in the type aliases if you'd be willing to merge such a thing.

**Comment by jtdaugherty** [comment]
Looking over the patch again with this in mind, it looks like the types that would need portability aliases are `App`, `Next`, and `EventM`. (I'm not as concerned about this for the Forms module types.) `EventT` is probably a fine name for the underlying event monad type. I'm not sure about good choices for new names for `Next` or `App`.

Another thing I noticed is that the drawing function now builds its output widget list in `m`. Was that change necessary for your work?

Also, as far as other changes that I'd like to see in this patch at some point before merge:

* Please remove any Stack-related files.
* Please reinstate the demo programs in the `cabal` file. (I figure those are commented out just to get things building.)
* The exception-handling issue with `vty` shutdown that @kquick pointed out will also need to be resolved.

**Comment by jtdaugherty** [comment]
Other things that need doing, but that I am happy to take on myself later if this gets merged, are:

* Haddock updates.
* User Guide material on using a custom monad.

**Comment by jtdaugherty** [comment]
Since I don't like to leave tickets open and lingering indefinitely, I wanted to say that I feel like I've moved on from this particular change and am going to close this. I might be willing to revisit it in the future, and thank you @isovector for the patch and for the discussion.
