### ISSUE TITLE
Viewport rendering of large text is expensive

### ISSUE THREAD

**Issue by avdv** [jtdaugherty/brick#247]
Hi.

First, thank you for brick! I just had an idea / need for a command line tool, and in basically two evening sessions I was able to create an initial version, with my very limited Haskell knowledge.

This worked great, but now I hit a bit of a dead end, since when I try to display a 2.1 MB file in a `viewport`, wrapped inside a `str` widget, it turns out to be unusable, uses lots of memory and CPU and scrolling is not really possible.

I heard that String in Haskell is not really performant, so I went on and converted my code to use Data.Text and used the `txt` widget instead. Then, I learned that `txt` simple calls `str $ DT.unwrap dt`... :scream: 

It would be nice to have real support for Data.Text (and maybe Data.Lazy.Text) so that displaying a text in a viewport does not render all data before line wrapping and clamping the output to fit the dimensions.

Thank you!

**Comment by jtdaugherty** [comment]
Hi, I'm glad to hear that you're enjoying using brick.

This problem is not related to `txt` or `str`. It is actually because of the way `viewport` is implemented, and the fact that you are rendering something very large in it. The problem is that `viewport` is not intended to be used to render arbitrarily large content, and because it cannot be smart about rendering only what should be visible, it renders *everything* and then crops. This means that *every* rendering of your UI renders the *entire* 2.1 MB file and then crops the result down to size, and that is going to behave exactly as you describe.

I haven't done a good job of calling this behavior out to warn people about it. There are a couple of ways to deal with this. The easiest by far is to just use render caching to cache the contents of the viewport so that the behavior I described is entirely eliminated. For details on that, please see [this section of the User Guide](https://github.com/jtdaugherty/brick/blob/master/docs/guide.rst#the-rendering-cache). The short version is:
```haskell
viewport ... $
cached SomeName $
txt $ ...
```
That approach won't work if your viewport contents change often, such as when implementing a text editor. In that case my advice is to not use `viewport` at all, because it was never intended for that (and implementing something like a text editor requires being smarter about the viewport than the `viewport` function allows for right now).

**Comment by avdv** [comment]
Thank you for your quick answer!

> This [...] is actually because of the way `viewport` is implemented, and the fact that you are rendering something very large in it. The problem is that `viewport` is not intended to be used to render arbitrarily large content, and because it cannot be smart about rendering only what should be visible, it renders _everything_ and then crops. This means that _every_ rendering of your UI renders the _entire_ 2.1 MB file and then crops the result down to size, and that is going to behave exactly as you describe.

Yeah, I even tried to adapt the implementation and copied the relevant code into my project. I don't need to do line wrapping, and that means I could simply skip to the right line first, and just use `height` lines of text that I just need to chomp to to right length. Seemed pretty straightforward, but therefore I would need access to `ScrollRequest`, which is internal.

> There are a couple of ways to deal with this. The easiest by far is to just use render caching to cache the contents of the viewport so that the behavior I described is entirely eliminated.

Oh, how could I miss this!

I tried it and it is indeed better :tada:, it takes around 4 seconds to display the initial first page of text...

**Comment by jtdaugherty** [comment]
> Seemed pretty straightforward, but therefore I would need access to ScrollRequest, which is internal.

`ScrollRequest` is only needed if you are using `viewport`. (And if you want to ask the renderer to scroll a viewport, you can use `Brick.Widgets.Core.visible` to do that.)

> I tried it and it is indeed better 🎉, it still takes around 4 seconds to display the initial first page of text, but it's fast afterwards.

Yeah, that makes sense. The first render is going to be very costly. This definitely suggests that a smarter implementation will only render enough lines to fill the available space. An easy way to do this is to maintain an application state field, say `scrollOffset`, that is manipulated by Up/Down arrow key presses. Then in your rendering function, get the height of the box that the text will go in and use that information along with your `scrollOffset` value to choose which lines to render. That will always be fast, provided your list of text lines can be indexed efficiently.

**Comment by jtdaugherty** [comment]
@avdv let met know if there is anything else you need. Otherwise, please close this if you don't need anything further. Thanks!

**Comment by avdv** [comment]
@jtdaugherty thank you very much for your input, and sorry for my late reply; I was on vacation and AFTK.

> `ScrollRequest` is only needed if you are using `viewport`

Yes, my (ambitious) plan was to reimplement the `viewport` function in terms of `Data.Text` (or even Data.Text.Lazy) instead of `String` to improve the speed and reduce the memory requirements for the most common use case(s). Do you think this would be feasible?

>  a smarter implementation will only render enough lines to fill the available space. An easy way to do this is to maintain an application state field, say `scrollOffset`, that is manipulated by Up/Down arrow key presses. Then in your rendering function, get the height of the box that the text will go in and use that information along with your `scrollOffset` value to choose which lines to render.

Thanks, I'll try to change my implementation.

**Comment by jtdaugherty** [comment]
> Yes, my (ambitious) plan was to reimplement the viewport function in terms of Data.Text (or even Data.Text.Lazy) instead of String to improve the speed and reduce the memory requirements for the most common use case(s). Do you think this would be feasible?

That is definitely feasible, especially if you don't worry about text wrapping. It would also be *vastly* simpler than the implementation of the `viewport` function, because you wouldn't have to worry about the size variation of child widgets. At worst you'd just need to deal with knowing the widths of every character in every line of text that you're going to show, to be sure you're truncating properly.

**Comment by avdv** [comment]
Thank you so much! I take it from here and report back if I hit a dead end.
