### ISSUE TITLE
Border broke due to emojis/wide characters in list mode

### ISSUE THREAD

**Issue by hyperreal-gopher** [jtdaugherty/brick#265]
I read [the section on wide characters](https://github.com/jtdaugherty/brick/blob/master/docs/guide.rst#wide-character-support-and-the-textwidth-class), but I think your borders might be broken if the line includes a wide character.

Here's a screenshot: https://cf.mastohost.com/v1/AUTH_91eb37814936490c95da7b85993cc2ff/fosstodon/media_attachments/files/004/026/057/original/f85ef423cb31c9f9.png

Thank you for your time!

**Comment by Garmelon** [comment]
This seems to happen with some emojis, but not all wide characters. Here is a very small test script:
```haskell
import Brick
import Brick.Widgets.Border

widget :: Widget ()
widget = vBox
  [ border $ str "📁"
  , border $ str "⼔"
  ]

main :: IO ()
main = simpleMain widget
```
![image](https://user-images.githubusercontent.com/11077553/75669800-95a78680-5c73-11ea-8010-97f8c922f1f1.png)

**Comment by Garmelon** [comment]
Since the guide says that brick relies on Vty's use of `utf8proc`, this is what utf8proc seems to think is the correct width:
```c
#include <stdio.h>
#include <utf8proc.h>

const utf8proc_int32_t FOLDER = 0x1f4c1;
const utf8proc_int32_t WIDECHAR = 0x2f14;

int main(void) {
  printf("Width of \xf0\x9f\x93\x81 is %i.\n", utf8proc_charwidth(FOLDER));
  printf("Width of \xe2\xbc\x94 is %i.\n", utf8proc_charwidth(WIDECHAR));
  printf("Width of A is %i.\n", utf8proc_charwidth('A'));
}
```
![image](https://user-images.githubusercontent.com/11077553/75671826-5b3fe880-5c77-11ea-86be-5d243d7c4cb9.png)

**Comment by Garmelon** [comment]
And a final test: Unsurprisingly, Vty reports the character widths incorrectly:

```haskell
import Graphics.Vty

printWidth :: Char -> IO ()
printWidth c = putStrLn $ "Width of " ++ [c] ++ " is " ++ show (wcwidth c) ++ "."

main :: IO ()
main = mapM_ printWidth ['📁', '⼔', 'A']
```
![image](https://user-images.githubusercontent.com/11077553/75673383-bfb07700-5c7a-11ea-83ef-a8eed6c8c3db.png)

Tested with vty 5.26.

**Comment by Garmelon** [comment]
Also, I didn't think of looking for a corresponding issue in the Vty repo first, so here it is: https://github.com/jtdaugherty/vty/issues/175. Looks like progress is being made and a solution is on the way. Nice :)

**Comment by jtdaugherty** [comment]
Thanks, everyone. Yes, to confirm: wide characters are *somewhat* supported, but the basis for that support depends on whether the *terminal emulator* and the application (in this case, Vty) agree on the character widths. In many cases, especially for characters added to Unicode more recently, they do not agree, and the amount of disagreement varies vastly from one terminal emulator to the next. The work on the Vty package is an attempt to improve (but probably not completely fix) that situation.

The screenshot posted at the top of this ticket is due to the wide characters causing a miscalculation and leading to pushing border characters off the screen. So it isn't about borders not supporting wide characters specifically.
