### ISSUE TITLE
Making strict widgets greedy

### ISSUE THREAD

**Issue by Profpatsch** [jtdaugherty/brick#27]
I’d like to make a list, like so:

```
124   foo
4324  bar
1     test
```

Padding just adds space to the side on each line, so the result becomes something like
```
124   foo
4324   bar
1   test
```

The idea is to make the left part greedy and then restrict its size.
My naive approach `((hLimit 10 $ (txt "124") { hSize = Greedy }) <+> txt "foo"` gives

```
124foo
…
```

It looks to me like it doesn’t make sense to reset `hSize` without re-rendering (what `hLimit` does).
How would I set a `txt` or `str` to greedy?
Does it even make sense to export the fields of `Widget`s?

**Comment by jtdaugherty** [comment]
The `hSize` field of a `Widget` just *describes* the behavior of that widget rather than *configuring* its behavior, so setting it will only change how containers behave when rendering that widget.  To actually get the behavior you want, you need to compose your string with a `fill` or `pad` operation so that extra spaces are rendered.  You're on the right track with `hLimit`, though - that (in effect) takes a greedy widget and makes it fixed, both by setting the `hSize` and by cropping the resulting limited widget.  Does that make sense?

Here is a way to do what you described.  Assuming you have a list with element type `(Int, String)` as depicted above, here is what your list item draw function would look like (without logic for handling the selection since I'm only trying to illustrate the widget composition):
```
drawElem :: Bool -> (Int, String) -> Widget
drawElem _sel (i, s) =
  -- The integer portion
  let intPart = str $ show i
      -- The integer portion, padded (so it is now "greedy")
      intPartGreedy = padRight Max intPart
      -- The width-limited integer portion
      intPartFixed = hLimit 10 intPartGreedy
      -- The string portion
      strPart = str s
      -- The whole thing
      final = intPartFixed <+> strPart
  -- Finally, we right-pad the whole thing so as to make the cursor
  -- attribute go all the way to the right hand side of the list.
  in padRight Max final
```

**Comment by Profpatsch** [comment]
Thanks, I missed the `Max` Constructor for `Padding`. How does `Pad Int` work, though? It looks to me like it simply adds spaces to the end.

**Comment by jtdaugherty** [comment]
Yes, you have it right. The integer argument specifies the number of rows or columns to pad.

**Comment by jtdaugherty** [comment]
If you decide that this approach works for you, please close the issue (or let me know what else I can do to help).
