### ISSUE TITLE
How to distinguish between Enter and Shift+Enter?

### ISSUE THREAD

**Issue by cblp** [jtdaugherty/brick#274]
When I press Enter with or without modifier keys, my app always gets `EvKey KEnter []` without any modifiers.

**Comment by jtdaugherty** [comment]
It would seem that some `Shift-Enter` and `Ctrl-Enter` both vary by terminal, where they are supported at all. Here is some information:

https://stackoverflow.com/questions/598113/can-terminals-detect-shift-enter-or-control-enter

My terminal (iTerm2 on macOS) sends `Enter` for all modifiers except `Meta`, for which `vty` detects `Meta-Enter`.

The short answer to this is: it would seem that it is not possible to support this key combination in `brick` and `vty` because it is not supported consistently across terminals. However, if you want `brick` (or any `vty`-based application) to recognize this key combination *and* your terminal sends a unique escape sequence for it, then you *can* get `vty` to recognize that sequence by configuring the Vty input config to map that sequence to `Shift-Enter`. That would work for you (and your terminal of choice) but if you're building software that you intend other people to use, they'll have to go through the same procedure to configure Vty. That might or might not be okay with you.

The procedure is described in some detail here:

https://github.com/matterhorn-chat/matterhorn/tree/develop#why-doesnt-matterhorn-support-my-desired-keybindings

Let me know how that works for you!

**Comment by cblp** [comment]
I use iTerm2 on a Mac, too. With default Option behavior, Vty receives Option+Enter as `EvKey KEnter []`. With Option emulating Meta, Vty receives `EvKey (KChar '\141') []`. Only with Option emulating Esc, Vty receives `EvKey KEnter [MMeta]`

**Comment by cblp** [comment]
Thanks!

**Comment by jtdaugherty** [comment]
Okay, great - does that mean you are able to move forward? Please let me know if there is more I can do to help, or close this ticket as a way of letting me know that you have what you need. Thanks!

**Comment by cblp** [comment]
Yes, I can reach what I want with reconfiguring iTerm2. Far from ideal, but I see nothing better.

**Comment by cblp** [comment]
Anyway, the problem is not in brick.

**Comment by jtdaugherty** [comment]
Okay, thanks for following up!
