### ISSUE TITLE
Smoothly switching between Apps

### ISSUE THREAD

**Issue by Yvee1** [jtdaugherty/brick#276]
Hello,

I have several different UIs which work differently so I essentially made all the UIs different brick applications. To switch between them I use the `suspendAndResume` function. This works well, the only caveat is that there is a slight flicker when switching UIs because one application is halted which shows the normal terminal for a moment, and then the other application starts. I'm also not sure whether the `suspendAndResume` function was made for this purpose of switching between different Apps. 

So my questions are: 
1. What is the expected way to implement different menus? Should all the different UIs be merged into one App with one large event handler and State?
2. Is there a way to prevent the flicker from occuring when doing `suspendAndResume`?

**Comment by jtdaugherty** [comment]
The `suspendAndResume` functionality was not quite designed to what you are using it for, although I can definitely see how it is a sensible thing to try. The flicker is due to the terminal state restore/save combo that happens in your case: on suspend, the terminal state is restored to its pre-application state briefly before another Vty handle is created by Brick.

As for your questions:
1. For now, given Brick's current design, I would recommend merging into one `App`. When I've done this, I've found it can work well to have an application "mode" (e.g. `data Mode = Main | SettingsMenu | ...`) that is used to dispatch to different drawing functions and event handlers. I have also wanted the design you are attempting to use -- one `App` for each logical bit of functionality -- and I've thought some about how Brick could be changed to support that better, but I have not made much progress. The key design issue I've run into is dealing with the change of state and event types between apps and dealing with the potential for events to get routed to different apps concurrently, as that needs to be supported in the general case. If it were simply a matter of "leaving" one app to "enter" another, that would simplify matters - but it would require some trade-offs that I'm not sure would be palatable. I do want to keep thinking about it, though.
2. The only way to prevent flicker would be to make it possible for the new `App`'s rendering loop use the same Vty handle as the initial `App`. I took a look at the code and it seems that's going to be tough to do, because Brick spawns a thread to manage events when it has control over the terminal. If it were to give away its Vty handle (that it uses for terminal I/O) to another `App`, that would mean giving the handle to another Brick rendering loop that would want to spawn its own thread to manage events.  That isn't possible for a bunch of reasons (such as the custom event type changing from one `App` to another, requiring a different event `BChan` and a thread for handling it).

**Comment by Yvee1** [comment]
Okay, thanks for the detailed explanation and swift response! I understand the issues, it's a pity that there is not a simple solution. I'll see if I can refactor my application into one app, using a `Mode` type like you suggested seems like a good idea. I suppose the issue can be closed then.

Thanks again

**Comment by jtdaugherty** [comment]
Okay. Thanks and good luck - please let me know if I can help further.
