### ISSUE TITLE
Confused about how greedy layout works

### ISSUE THREAD

**Issue by saurabhnanda** [jtdaugherty/brick#282]
I have a bunch of related questions.

- How do you make a `Widget` greedy in a given direction (horizontal / vertical)? I'm assuming it's done via `hLimitPercent` and `vLimitPercent`, but I may be wrong.
- If none of the "inner widgets" are explicitly setting fixed sizes, can you predict what the layout would be, just on the basis of the following code snippet:

```haskell
renderBrickApp :: AppState -> [B.Widget AppRef]
renderBrickApp appState =
  [ B.vBox
    [ B.vLimitPercent 30 $
      B.hBox
      [ B.hLimitPercent 50 $ internalWidget1 appState
      , B.hLimitPercent 50 $ internalWidget2 appState
      ]
    , B.vLimitPercent 70 $ internalWidget3 appState
    ]
  ]
```

Here's what I was expecting:

```
+------------------------------------------------------------------+
|                                |                                 |
| 30% of terminal height         |  30% of terminal height         |
| 50% of terminal width          |  50% of terminal width          |
|                                |                                 |
+------------------------------------------------------------------+
|                                                                  |
|                                                                  |
| 70% of terminal height                                           |
| 100% of terminal width                                           |
|                                                                  |
|                                                                  |
|                                                                  |
|                                                                  |
|                                                                  |
|                                                                  |
+------------------------------------------------------------------+
```

And here's what I got:

![Screen Shot 2020-08-17 at 1 55 12 PM](https://user-images.githubusercontent.com/28369/90374576-52aa6580-e091-11ea-839b-299c56a86ff6.png)

**Comment by jtdaugherty** [comment]
I'm not sure how I can answer your stated questions without first clearing up a misunderstanding: the `hLimitPercent` and `vLimitPercent` functions restrict the size of their argument widget *as a percentage of the size of the container of the hLimit/vLimit*, not the terminal window itself (unless `hLimitPercent` or `vLimitPercent` is the top-level widget.)

For example,

```haskell
hLimit 70 $ hLimitPercent 50 x
```

Here `x` will be given 35 columns in which to draw. The outer `hLimit` sets the container width to 70, and the inner `hLimitPercent` takes 50 percent of that.

Similarly in the vertical case:

```haskell
vLimit 30 $ vLimitPercent 10 x
```

Here `x` will be given 3 rows in which to draw.

In the specific case where the top-level widget is one of these, i.e., `appDraw = [vLimitPercent 50 x]`, then `x` gets 50 percent of the container height, which in this case is the terminal window height. Let me know if that helps and then we can see about whether your other questions have changed.

**Comment by saurabhnanda** [comment]
> I'm not sure how I can answer your stated questions without first clearing up a misunderstanding: the hLimitPercent and vLimitPercent functions restrict the size of their argument widget as a percentage of the size of the container of the hLimit/vLimit, not the terminal window itself (unless hLimitPercent or vLimitPercent is the top-level widget.)

The code snippet that I shared earlier, is the top-level widget that is being rendered. Its parent is the terminal directly, i.e. there is no `vLimit` on top of it.

After posting that snippet, I played around a little more and got the following to work...

```haskell
renderBrickApp :: AppState -> [B.Widget AppRef]
renderBrickApp appState@AppState{..} =
  [ B.vBox
    [ B.vLimitPercent 30 $
     -- this hbox is slightly different from what I have posted above.
     -- ultimately I needed three columns, not two. But the last column expands
     -- to take up the remaining space ONLY IF  hLimitPercent is removed from it.
      B.hBox
      [ B.hLimitPercent 30 $ innerWidget1 appUIState
      , B.hLimitPercent 25 $ innerWidget2 appUIState
       -- no hLimitPercent
      , innerWidget3 appUIState
      ]
       -- no vLimitPercent
    , innerWidget4 appUIState
    ]
  ]

```

... after which I got even more confused. Why does this work if the last element in an `hBox` or `vBox` is not limited in size?

**Comment by jtdaugherty** [comment]
The reason the new code snippet works better than the first is because, as you pointed out, some limits were removed. This comes down to understanding how Brick's rendering process works, which is *mostly* about understanding how `vBox` and `hBox` work. I'm going to explain it a bit here in this example, but if you haven't already, I strongly suggest you read [the section of the Brick user guide about this](https://github.com/jtdaugherty/brick/blob/master/docs/guide.rst#how-widgets-and-rendering-work) since I would like to see if that helps, and it's intended to be there to explain this.

When you put two things in a box (`vBox` or `hBox`), the box has to decide how to divide up its available space to the child widgets. So, if a `vBox` gets drawn in a 10-row-high region, for example, then `vBox [a, b]` has to decide how many of those 10 rows go to `a`, and how many go to `b`.
* If `a` and `b` are both *non-greedy*, then `vBox` will just render `a` first and give any of the remaining unused 10 rows to `b`'s renderer.
* If `a` and `b` are *both* greedy, then `vBox` will give 5 rows to each widget.
* If only one is greedy, then the *other* widget gets rendered first and the remaining rows go to the greedy widget.

Looking at your example here, if we have
```haskell
```

**Comment by jtdaugherty** [comment]
The reason the new code snippet works better than the first is because, as you pointed out, some limits were removed. This comes down to understanding how Brick's rendering process works, which is *mostly* about understanding how `vBox` and `hBox` work. I'm going to explain it a bit here in this example, but if you haven't already, I strongly suggest you read [the section of the Brick user guide about this](https://github.com/jtdaugherty/brick/blob/master/docs/guide.rst#how-widgets-and-rendering-work) since I would like to see if that helps, and it's intended to be there to explain this.

When you put two things in a box (`vBox` or `hBox`), the box has to decide how to divide up its available space to the child widgets. So, if a `vBox` gets drawn in a 10-row-high region, for example, then `vBox [a, b]` has to decide how many of those 10 rows go to `a`, and how many go to `b`.
* If `a` and `b` are both *non-greedy*, then `vBox` will just render `a` first and give any of the remaining unused 10 rows to `b`'s renderer.
* If `a` and `b` are *both* greedy, then `vBox` will give 5 rows to each widget.
* If only one is greedy, then the *other* widget gets rendered first and the remaining rows go to the greedy widget.

Looking at your example here, if we have
```haskell
vBox [vLimitPercent 10 a, b]
```
Then this means that `a` will get ten percent of the parent box height and `b` will get 90 percent. This is because `vLimitPercent` guarantees that `a` gets rendered first (by changing it from greedy to non-greedy) and then the remaining box space goes to the second child (which may or may not be greedy; it doesn't matter).

**Comment by jtdaugherty** [comment]
I wanted to also mention that the example above does not guarantee that `a` will always take up 10 percent of the available space; it only guarantees that it will get an opportunity to use that space. The final result still might be that 10 percent of the `vBox` is 10 rows, but `a` renders only one row high, resulting in `b` getting 90 percent plus 9 rows to work with. (This is why this is called `vLimitPercent`; it limits the available space.) If what you want is to guarantee a layout where the space is divided up into 10 and 90 percent chunks, `fill` is needed to "fill up" the space next to or above/below `a`, e.g.,
```haskell
vBox [vLimitPercent 10 (a <=> fill ' '), b]
```

**Comment by jtdaugherty** [comment]
@saurabhnanda Any update on whether the comments above helped you?

**Comment by jtdaugherty** [comment]
@saurabhnanda I'm going to close this due to inactivity, but please re-open if you'd like to resume the discussion. Thanks!
