### ISSUE TITLE
`EventM` is not a `MonadResource`

### ISSUE THREAD

**Issue by NorfairKing** [jtdaugherty/brick#285]
This means that I cannot acquire resources safely across multiple event handlings.
I just had to work around this in my app because it can switch between files and I need to make sure that all file locks are released before the app finishes.
This is important because I run Smos as part of a web service now, so the process doesn't end after I'm done with the brick app.
See https://staging.smos.online

**Comment by jtdaugherty** [comment]
I'm not sure this makes sense as part of the library. Was your workaround successful?

**Comment by NorfairKing** [comment]
https://github.com/NorfairKing/smos/commit/808a2cb7d924c15570ccec36b5f4cf159ec6cc4a#diff-6ce0ba6d7e74251aef125526cad7ae24R44

I had to use the `ResourceT` `InternalState` from the `Internal` module to do it.
It's "succesful" but really not nice.

**Comment by NorfairKing** [comment]
> This means that I cannot acquire resources safely across multiple event handlings.

This is the big deal, and something I think should definitely be supported.
If your actions create resources, the app should be able to clean them up before it finishes.

**Comment by jtdaugherty** [comment]
> If your actions create resources, the app should be able to clean them up before it finishes.

I agree with this statement, but I'm not really enthusiastic about supporting this in `EventM`. My recommendation is to handle resource allocation in a separate context, usually in another thread. The event-handling monad should be treated like an interrupt handler: do as little work as possible in order to return control to the rendering loop in order to minimize latency.
