### ISSUE TITLE
How to run send an Event again right after first render?

### ISSUE THREAD

**Issue by iyefrat** [jtdaugherty/brick#289]
The use case is that I want to change what is displayed as a function of the size of the widget, but to get this I need its extent. I can sort of get around this by saving the extent to state on the each tick, but this causes a small delay as I only have 1 tick per second. Do you know of a better way to do this?

Also on an unrelated note, would you be interested an a MR for more complex (backwards compatible) widget size rules? For example, a half greedy setting that is greedy up to the point where it needs to start adding whitespace, and then becomes fixed. I find myself wanting this when rendering data in columns.

**Comment by jtdaugherty** [comment]
> The use case is that I want to change what is displayed as a function of the size of the widget, but to get this I need its extent. I can sort of get around this by saving the extent to state on the each tick, but this causes a small delay as I only have 1 tick per second. Do you know of a better way to do this?

Unfortunately this information is only available if you have rendered the widget, so you have to use extents to get the size. The other option is not to let the widget size be dynamic, but to set it to your own fixed size. In that case you don't have to get an extent from the renderer.

> Also on an unrelated note, would you be interested an a MR for more complex (backwards compatible) widget size rules? For example, a half greedy setting that is greedy up to the point where it needs to start adding whitespace, and then becomes fixed. I find myself wanting this when rendering data in columns.

Before considering new size policies I would want to be absolutely sure you can't already accomplish what you want without them. Can you open a new ticket about that with an example of a layout you are wanting to achieve? In all likelihood I can help you get what you want using only what the library provides.

**Comment by iyefrat** [comment]
> Unfortunately this information is only available if you have rendered the widget, so you have to use extents to get the size. The other option is not to let the widget size be dynamic, but to set it to your own fixed size. In that case you don't have to get an extent from the renderer.

what I currently do is on ticks I save the extent to the state, so I can access the extent used in the last rendering (which is usually the same extent anyway). While writing this reply, I realized that I can pass the event channel along to the state and send it extra ticks when I render these types of widgets for the first time. There is a tiny delay due to the double rendering, but I assume this is the best I can do, unless you have a better idea.

>Before considering new size policies I would want to be absolutely sure you can't already accomplish what you want without them. Can you open a new ticket about that with an example of a layout you are wanting to achieve? In all likelihood I can help you get what you want using only what the library provides.

I will do this tomorrow as it is getting rather late, thanks in advance!

**Comment by jtdaugherty** [comment]
> There is a tiny delay due to the double rendering, but I assume this is the best I can do, unless you have a better idea.

If it is this important to know the size of the widget in question, another way you could do this is: rather than asking the Brick renderer how big the widget was in the last rendering (which may be stale by the time you use the extent information), you could:
* Get the Vty terminal handle with `Brick.Main.getVtyHandle` and use the Vty API to get the window size (`displayBounds $ outputIface handle`);
* Use the window size to infer the size of your widget, assuming you know the role it will play in the Brick layout;
* Use the widget size information as needed rather than using the widget extent info

**Comment by iyefrat** [comment]
This seems to not make that big of a difference timewise (and now that I'm trying again, the delay is nigh imperceptible in both cases), but on a theoretical level, why would this be faster? Maybe I implemented this wrong, but since `Brick.Main.getVtyHandle` returns an `EventM n Vty` I still need to generate it during one event and only use it during the next one, which is the same thing I was doing with extents.

**Comment by jtdaugherty** [comment]
My recommendation to use `getVtyHandle` is not due to performance (although it *should* be faster if it allows you to avoid an extra render); the reason is because it is going to get you the right answer, provided the assumptions I listed above are true, while using extents will always have the possibility of giving you the wrong answer if you are relying on an extent that was recorded before the UI was resized.

If you are using `getVtyHandle` to get a Vty handle, you should use it *right then*, not on the next event. That defeats the purpose of using it.

**Comment by iyefrat** [comment]
Just making sure I understand correctly, what you mean here is that I use `getVtyHandle` in the Event loop, save the `Vty` to the global state, and then use it in the widget drawing function? This means that we get the size for the current event, rather than the extent recorded at the last rendering, which will be one event behind.

It seems that on version 0.55 there isn't a way to get the `Vty` from within `RenderM` without manually saving it to the state first and giving the state as input to the widget drawing function, is this true? If I understand correctly #279 does add this information to the context.

**Comment by jtdaugherty** [comment]
> Just making sure I understand correctly, what you mean here is that I use getVtyHandle in the Event loop, save the Vty to the global state, and then use it in the widget drawing function? This means that we get the size for the current event, rather than the extent recorded at the last rendering, which will be one event behind.

Yes, that's right: although storing the `Vty` handle itself won't help you because you can't access some of its metadata outside of `IO`. You'll need to get the information from the handle in your event handler, then store that.

> It seems that on version 0.55 there isn't a way to get the Vty from within RenderM without manually saving it to the state first and giving the state as input to the widget drawing function, is this true? 

It sounds like you're asking about three things here, so I'll split them up: 1) the Vty handle can only be obtained from `EventM`, 2) any information obtained from that handle that is needed in your drawing function *must* be provided by putting it in your application state, and 3) a recent change did specifically add the *whole window* dimensions to the rendering context, but that is only available in `RenderM` when making a custom widget.

The whole window size *may* be enough for your purposes, or it may not. I couldn't say since I don't know what your situation is. But if you could infer what you need from that size based on what you know about your layout, then it could be enough right now without doing anything with the `Vty` handle and storing extra information in your application state.

**Comment by jtdaugherty** [comment]
@iyefrat Was my comment above helpful?

**Comment by iyefrat** [comment]
Sorry, I've been very busy the past two weeks, so although i've read your comment, i haven't had time to properly sit down and think about it and go over the documentation etc. I will write a proper response in a few days if all goes well.

**Comment by jtdaugherty** [comment]
Thanks, no hurry! I just wanted to check in.

**Comment by iyefrat** [comment]
Apologies for the long delay. Your reply answered all of the questions I have on this subject. Thank you!

**Comment by jtdaugherty** [comment]
Okay, great!
