### ISSUE TITLE
Doing I/O in RenderM?

### ISSUE THREAD

**Issue by depressed-pho** [jtdaugherty/brick#314]
Could you consider giving an I/O capability to `RenderM`? I know it's not a great idea to perform I/O in a renderer, but sometimes it is absolutely necessary. Let me explain my situation:

I'm currently developing a game which has an infinitely large 2D plane aka. "world". The world is lazily generated and saved on disk. To render some part of the world, a widget has to know which exact area is currently visible. This is only feasible in `RenderM` because the size of the widget can only be known in this monad. On the other hand, the contents in the visible area can only be obtained by doing an I/O because they are not always available in memory.

For now I'm using `unsafePerformIO` in `RenderM` as a workaround. It works, but is not a great thing to do in Haskell. It would be nice if `RenderM` allowed I/O just like `EventM` does.

**Comment by jtdaugherty** [comment]
Hi!

> This is only feasible in RenderM because the size of the widget can only be known in this monad.

The size of any widget can be obtained after an initial rendering using [extents](https://github.com/jtdaugherty/brick/blob/master/docs/guide.rst#extents). Have you tried that?

**Comment by depressed-pho** [comment]
Yes, I know that. But in my case that's not really suitable because my code is only going to be needlessly complicated.

**Comment by jtdaugherty** [comment]
Can you say a bit more about what you mean about complications?

**Comment by depressed-pho** [comment]
Okay. The world is split into chunks each covering 32 x 32 units. There is a player somewhere in the world whose position is represented in the world coordinates. The entire application is split into two parts: a game engine which handles the game logic part, and the UI part which handles terminal output and key inputs. In the UI part I have a data type `WorldView` which contains a reference to the game engine. I also have a function `renderWorldView :: WorldView n -> Widget n` which currently does the following:

1. Ask the game engine where the player is located in the world coordinates. This requires IO.
2. Calculate the visible area centered around the player. This requires `getContext`.
3. Determine which chunks are at least partially visible.
4. Ask the game engine to load or generate those chunks. This requires IO.
5. For each retrieved chunks, render its visible part as Vty `Image`.
6. Concatenate the rendered `Image`s and wrap it in `Result`.

But if I were to use extents, I would have a function `handleWorldViewEvent :: Event -> WorldView n -> EventM n (WorldView n)` which does the following:

1. Ask the game engine where the player is located. Uses IO.
2. Calculate the visible area centered around the player based on the recorded extent.
3. Ask the game engine to load or generate visible chunks. Uses IO.
4. Update the `WorldView` with the retrieved chunks and coordinates of the visible area. Then return it.

And `renderWorldView :: WorldView n -> Widget n` would do:

1. If the `WorldView` has no chunks saved because it was the first time it was rendered, then return `emptyWidget`.
2. Otherwise, for each retrieved chunks, render its visible part as Vty `Image`.
3. Concatenate the rendered `Image`s and wrap it in `Result`.
4. Apply `reportExtent` to the resulting `Widget`.

Yes this is indeed a viable solution. But I feel quite uncomfortable because the rendering logic is now split into two parts and they need to communicate with each other, just to overcome the limitation of `RenderM` which can't do IO.

**Comment by jtdaugherty** [comment]
Thanks for elaborating! That's very helpful.

Fundamentally, using `brick` means rethinking how the UI is separated from the application state changes. For example, your first steps 1-6 above would be implemented more idiomatically in a `brick` application as follows:

> Ask the game engine where the player is located in the world coordinates. This requires IO.

Typically a `brick` application, the application state should contain this information readily available without the need for I/O. So in this case, I suggest using an application state which is essentially a snapshot of the needed information for rendering. (In this case, player location.) Then the question becomes: when does that snapshot get obtained? The answer is: in an event handler or in a thread.

> Calculate the visible area centered around the player. This requires getContext.

This would still happen at rendering time in an idiomatic approach.

> Determine which chunks are at least partially visible.
> Ask the game engine to load or generate those chunks. This requires IO.

This is where things have to change. In an idiomatic Brick application design, the chunks shouldn't be loaded at *rendering* time, but at the time of an input event that triggers a change in which chunks should be loaded.

> For each retrieved chunks, render its visible part as Vty Image.
> Concatenate the rendered Images and wrap it in Result.

These would be done at rendering time either way.

I suggest this alternate design because your current design is going to make using `brick` an uphill battle. The entire design of `brick` is about making rendering a pure function of the application state and forcing the application to make state changes asynchronously or in an event handler only. This is why I recommended using extents. In an extent-based approach the idea is to ask Brick to record the extent of a section of the UI, and then obtain that extent information in `EventM`, at which point you'd use it to make decisions, load chunks, etc. - but after that point the renderer's job should be easy, because the application state will have been updated to make it clear what should be rendered. Still, that approach hinges on what might be a significant change from your current design. I recognize that that might not be palatable to you.

Now, to comment on your specific request: I'm afraid that I'm unwilling to make `RenderM` support I/O, for two reasons:

1) It essentially breaks the library's design and what I set out to do, namely to make rendering mostly a pure function of the application state. That design decision is one of the library's biggest strengths and results in applications with a *very* clean design.

2) There is *no guarantee* about the order in which I/O actions in the rendering code will be evaluated, and there is also *no guarantee* that they will be evaluated at all (in the case of using `cached`). Increasing the amount of potential side effects of rendering will not help in the long run.

I'm happy to leave this ticket open to continue discussing how you might approach your problem differently, but adding I/O to `RenderM` is not an option. I recognize that you may not agree and may feel frustrated by this response, but if you want to use `brick` then I would really encourage you to rethink how your design could be adjusted to work with the `brick` model. I am happy to provide any help that I can along those lines!

**Comment by depressed-pho** [comment]
Thank you so much for your detailed explanation. Now I understand the rationale behind the design of `brick`, and will probably rewrite my code according to your advise.

> There is no guarantee about the order in which I/O actions in the rendering code will be evaluated, and there is also no guarantee that they will be evaluated at all (in the case of using cached). Increasing the amount of potential side effects of rendering will not help in the long run.

Oh yeah... that's very problematic indeed. In my case all of the I/O actions are idempotent so such an guarantee is not necessary, but in general case that can easily cause troubles.

I'm going to close the ticket. Thank you again for taking the time.

**Comment by jtdaugherty** [comment]
Okay. Good luck, and please let me know if I can help!
