### ISSUE TITLE
Unable to capture some modified key strokes.

### ISSUE THREAD

**Issue by AndrewRademacher** [jtdaugherty/brick#32]
I have a small demo using the following event loop

```haskell
event :: State -> Event -> EventM (Next State)
event st e = do
    liftIO $ print e
    continue st
```

and the following draw function

```haskell
draw :: State -> [Widget]
draw st = [str "Hello World!"]
```

There are several cases like `Ctrl+,`, `Ctrl+.`, and `Ctrl+/` that do not fire an event. Additionally there is at least one case of sending the wrong event. For example you would expect `Ctrl+m` to read...

```
EvKey (KChar 'm') [MCtrl]
```

however it actually reads...

```
EvKey KEnter []
```

**Comment by jtdaugherty** [comment]
Unfortunately this behavior depends almost entirely on your terminal emulator of choice and the active termcap settings; to see what I mean you might consider trying different terminal emulators and different modifier key combinations.

In the particular case of `C-m` and `Enter`, the value for `C-m` is *equivalent* to `Enter` so there isn't a way to distinguish.  This is also true of `Tab` and `C-i`.  So from that perspective, seeing `KEnter` when `C-m` is pressed is expected behavior.

As examples of this kind of behavior, these pages might be illuminating:

http://askubuntu.com/questions/441744/pressing-enter-produces-m-instead-of-a-newline
http://stackoverflow.com/questions/598113/can-terminals-detect-shift-enter-or-control-enter

Sadly, terminal application programmers typically need to select control-key combinations that are likely to work on a wide variety of terminal emulators to avoid this problem.

**Comment by AndrewRademacher** [comment]
Sad indeed. Thanks for the heads up.

**Comment by hramrach** [comment]
Thanks for looking into this.

Regarding the key mapping - aren't key mappings in some database so applications know what to expect on which terminal?

If not how is anything ever supposed to work on a terminal?

Or is that why vi uses key sequences rather than modifiers most of the time? 

Because the modifiers break?

**Comment by jtdaugherty** [comment]
@hramrach - yes, `termcap` is the database you mentioned.  Still, that is not necessarily enough to make this work for all emulators and all modifier key combinations.  It might be something that @coreyoconnor could address by making changes to `vty` (which `brick` uses to handle keyboard input events), though.
