### ISSUE TITLE
A way to render a state to _bytes_ for golden tests

### ISSUE THREAD

**Issue by NorfairKing** [jtdaugherty/brick#323]
I'd like to make a golden test that checks whether (and tracks how) my app's startup state is rendered. Is there any way to turn a `[Widget n]` into a `ByteString`?

**Comment by jtdaugherty** [comment]
You might consider using `mockTerminal` from Vty as your output interface when building your Vty handle. I have not used it myself (and I did not write it) but it sounds like it might be close to what you want, if not an exact match:

http://hackage.haskell.org/package/vty-5.33/docs/Graphics-Vty-Output-Mock.html

There is some testing code that uses it here:

https://github.com/jtdaugherty/vty/blob/master/test/VerifyUsingMockTerminal.hs

Since I haven't tried this before, I'm not sure whether there will be issues with doing it. In order to use this with Brick you'll need to use `customMain`, provide a custom `Vty` builder function, and have that function override the `outputIface` field of the `Vty` handle with the `Output` returned by `mockTerminal` (as well as shut down the old `Output` interface that was in its place). Another thing to be aware of is that Vty does a diff of the prior terminal output before emitting any new bytes, which probably means that for testing you want to create a new mock terminal state for each test to avoid any previous renderings sticking around and messing up your checks.

**Comment by NorfairKing** [comment]
Thanks for the quick response and the pointers! I'll look into this and reopen if necessary.
