### ISSUE TITLE
Leave last appDrawn on screen on exit

### ISSUE THREAD

**Issue by omnibs** [jtdaugherty/brick#325]
Brick clears the screen on exit, and it makes it hard to debug failures in some programs.

Is there a way to make it so the last appDraw remains on exit?

**Comment by jtdaugherty** [comment]
Hi @omnibs. Since `brick` always wants to ensure that the screen state is restored (which includes various other terminal modes like mouse mode), `brick` always calls the Vty `shutdown` method, even in the event of exceptions. Since `shutdown` is what is responsible for restoring the screen state, I think your best option is to just override the `shutdown` value of the `Vty` handle that `brick` uses so that it does nothing.

To do that, you'll need to:

* Use [`customMain`](https://hackage.haskell.org/package/brick-0.62/docs/Brick-Main.html#v:customMain) so that you can pass your own `Vty` builder, and
* Make a `Vty` builder that uses [`mkVty`](https://hackage.haskell.org/package/vty-5.33/docs/Graphics-Vty.html#v:mkVty) and then overrides the [`shutdown` field](https://hackage.haskell.org/package/vty-5.33/docs/Graphics-Vty.html#t:Vty), e.g. `vty { shutdown = return () }`.

I hope that helps! Let me know if you have any other questions, and let me know if that works out.

**Comment by jtdaugherty** [comment]
@omnibs Let me know if that helped so we can figure out whether to close this. Thanks!

**Comment by jtdaugherty** [comment]
I'm closing since I presume this can be considered resolved, but please follow up if you'd like to discuss more!

**Comment by omnibs** [comment]
Gosh, sorry for the delay, and thanks so much for the answer, it worked beautifully!

**Comment by jtdaugherty** [comment]
Great!
