### ISSUE TITLE
possible to flush mouse scroll events ?

### ISSUE THREAD

**Issue by simonmichael** [jtdaugherty/brick#348]
I'm posting here since the issue tracker seems to be the main support/discussion forum, please let me know if it's too much.

When using a brick app with mouse scroll wheel support, it's hard not to over scroll, causing a huge backlog of scroll events which effectively freezes the app until they are cleared. What workarounds might be feasible for a brick app dev, or for brick itself, eg to flush or limit such pending events ? Or is it completely outside brick's control ?

[Sorry, I should have rechecked the readme first. Perhaps <https://groups.google.com/g/brick-users> would have been better.]

**Comment by jtdaugherty** [comment]
Thanks for posting, no problem - I'm happy to respond to email on the list or discuss things here.

I don't know what Brick itself can do about this, just because we don't know (from the library's perspective) what is considered "too many events." If anything it seems to me like a thing that has to be decided at the application level. With that said, if the huge backlog of events is causing noticeable latency in the application, then perhaps the task is to improve the latency rather than reducing the events. (Or set a timer to ignore scroll events coming in too rapidly, for whatever your definition of "rapidly" is.)

If you need to reduce latency, the most common way to do that is to use render-caching of elements of your UI that are not likely to change much (and that are relatively expensive to draw). Have you looked into that? I don't know whether your application could benefit from it, but I've needed to employ that pretty aggressively in some applications I've written where latency was noticeable even for keyboard input.

**Comment by jtdaugherty** [comment]
Here is some material on render-caching: https://github.com/jtdaugherty/brick/blob/master/docs/guide.rst#the-rendering-cache

**Comment by simonmichael** [comment]
Some great ideas, thanks Jonathan! Indeed it's likely that hledger-ui is not using latest practices and could possibly run faster to keep up.

**Comment by jtdaugherty** [comment]
Well, to be fair, render-caching may help but it can be hard to get right (like any caching behavior). So if you've been able to get far without it, I see that as a good thing. Needing to worry about what is cached and when to invalidate the cache can introduce some mental overhead and complexity that is probably best avoided if possible. 😊

**Comment by jtdaugherty** [comment]
Also, with that said, it's still possible that with caching your event can still be overwhelmed by a very full event queue. So I'll be curious to see what kind of mileage you get out of any caching-related changes.

**Comment by simonmichael** [comment]
Indeed, I am guessing that some app-level event pruning is probably the easiest and most effective first fix.

**Comment by simonmichael** [comment]
(I'll report results back here if any.)

**Comment by simonmichael** [comment]
For the record: I was testing in a terminal with small font, ie large dimensions, which helps make the symptom visible. In a 80x25 terminal there's essentially no scroll lag (the app keeps up), though this is probably machine-dependent.

**Comment by jtdaugherty** [comment]
Thanks for the update. That makes sense. I've done similar things to test whether render-caching really was helping (by increasing the terminal dimensions and reducing the font size).
