### ISSUE TITLE
adjust viewport scroll position before first render

### ISSUE THREAD

**Issue by simonmichael** [jtdaugherty/brick#349]
Moving the conversation here: I think I have the same issue as #170. I'd like to use a viewport, I'd like to adjust the scroll position before showing it to the user, and I'm not quite seeing how to apply your comments from #170. 

Here's a real-world example: in hledger-ui I navigate from the accounts screen to an account's register screen [here](https://github.com/simonmichael/hledger/blob/master/hledger-ui/Hledger/UI/AccountsScreen.hs#L323), using helpers 
[asEnterRegister](https://github.com/simonmichael/hledger/blob/master/hledger-ui/Hledger/UI/AccountsScreen.hs#L374), 
[rsCenterAndContinue](https://github.com/simonmichael/hledger/blob/master/hledger-ui/Hledger/UI/RegisterScreen.hs#L415),
[scrollSelectionToMiddle](https://github.com/simonmichael/hledger/blob/master/hledger-ui/Hledger/UI/UIUtils.hs#L322),
[screenEnter](https://github.com/simonmichael/hledger/blob/master/hledger-ui/Hledger/UI/UIState.hs#L316).
But scrollSelectionToMiddle has no effect the first time through, since it finds no viewport for the new screen's list, which has not been rendered yet.
Concretely: here's an account `a` containing a list of transactions, on first entering the selection is down at the bottom of the window, rather than scrolled to the middle as I'd like.

![51057](https://user-images.githubusercontent.com/10144/142737503-64c1554a-0691-4f0a-b03d-d8b2d1580976.gif)

I see it's easy to call the draw function from an event handler. I know this won't cause visible output, but I'm hoping it might evaluate whatever code path in brick generates the viewport ? 

On that assumption, I tried this, but I think it's probably not forcing enough evaluation:

```haskell
rsCenterAndContinue :: UIState -> EventM Name (Next UIState)
rsCenterAndContinue ui = do
  traceShow (length $ rsDraw ui) $  -- force a render in case this is the first time, to ensure there's a viewport we can scroll
    scrollSelectionToMiddle $ rsList $ aScreen ui
  continue ui
```
and Widget doesn't have the right instances for deepseq.

I hope this makes sense.

**Comment by jtdaugherty** [comment]
To clarify: when you say "I want the viewport to scroll to the middle", do you mean "I want the bottom of the list to appear in the middle of the viewable (viewport) area"?

**Comment by jtdaugherty** [comment]
Also, in your animation above, it looks like it eventually gets into the state that it sounds like you want (where the "30" element is in the middle of the screen), if I understand correctly. Is that right? If so, what brought that about?

**Comment by simonmichael** [comment]
Yes, sorry. The animation loops so it's hard to tell, but: 

1. I start the app in "screen 1", which shows a list of one account (`a`).
2. I press RIGHT to enter "screen 2", which shows a list of 30 transactions, with the last one selected and positioned at the bottom of the viewable area.  
3. I press LEFT to return to screen 1, the RIGHT to enter screen 2 again. This time the last element is scrolled to the middle of the viewable area. This is the behaviour I want to see every time I enter screen 2.

**Comment by simonmichael** [comment]
...and the thing that makes that scrolling to the middle happen is rsCenterAndContinue, which I call as part of moving from screen 1 to screen to with asEnterRegister. And it calls scrollSelectionToMiddle, inlined here to save you following a bunch of links:
```haskell
-- | Scroll a list's viewport so that the selected item is centered in the
-- middle of the display area.
scrollSelectionToMiddle :: List Name e -> EventM Name ()
scrollSelectionToMiddle list = do
  let mselectedrow = list^.listSelectedL
      vpname = list^.listNameL
  mvp <- lookupViewport vpname
  case (mselectedrow, mvp) of
    (Just selectedrow, Just vp) -> do
      let
        itemheight   = dbg4 "itemheight" $ list^.listItemHeightL
        vpheight     = dbg4 "vpheight" $ vp^.vpSize._2
        itemsperpage = dbg4 "itemsperpage" $ vpheight `div` itemheight
        toprow       = dbg4 "toprow" $ max 0 (selectedrow - (itemsperpage `div` 2)) -- assuming ViewportScroll's row offset is measured in list items not screen rows
      setTop (viewportScroll vpname) toprow
    _ -> return ()
```
And it has no effect the first time screen 2 is entered, because lookupViewport finds Nothing.

**Comment by simonmichael** [comment]
PS it may require more thought by me, and ultimately restructuring my app. But I'm curious if forcing the viewport to be created from within the event handler sounds possible. If so, I'll pursue that. And I guess I can study brick's internals to find out when exactly that gets triggered.

**Comment by jtdaugherty** [comment]
First, I want to explain why this is happening. Then I'll offer an alternative that I think will work.

Why this is happening: `lookupViewport` looks in `EventM` to get the *last rendered state of a viewport*. That state came from the most recent screen redraw. So if that redraw did not render the desired viewport, no viewport state will be found. I suspect you already figured this part out, but I wanted to be explicit. There is no way around this, because the viewport state *is computed during rendering* and cannot be known in advance without first attempting to draw it. It can't be known in advance because the viewport state is a function of the layout of the rest of your UI, which is in turn a function of the window size, and all of that except the window size cannot be known in advance because it is all the result of the rendering computation.

With that said, I think the way to get what you want is to exploit your knowledge of your UI's layout so that you can call `setTop` *without* depending on the viewport state. In your UI's case I think the math is simple enough that you could infer your viewport size by looking at the window size itself and doing a little bit of math. The window size can be gotten by calling [`getVtyHandle`](https://hackage.haskell.org/package/brick-0.65/docs/Brick-Main.html#v:getVtyHandle) and then calling `liftIO . displayBounds . outputIface` on the handle to get the window size. From there, you have a value very close to `vp^.vpSize._2` above; you just need to use what you know about your UI layout to subtract a little from the total screen height to get your viewport height. From there, the rest of your math would still apply and you can call `setTop` without needing the viewport state. Let me know if that makes sense.

(As an aside, the reason why calling `setTop` works at all is because that queues up a *scrolling request* within `EventM` that gets consulted and applied during the next rendering pass. That's why it doesn't need foreknowledge about the viewport in `EventM`.)

I also want to say a few things about your comments about evaluating/forcing the drawing results. Fundamentally, that will not do anything at all because `Widget`s are made up of `State` monad computations. So forcing the drawing function will just cause those `State` monad computation terms to get built, *but not evaluated*. It's the evaluation of those terms at rendering time that does all the work: setting the rendering context, building up Vty images, offsetting coordinates, gathering up extents, dealing with the rendering cache, and computing (new) viewport states (possibly based on states from the previous render). So forcing or otherwise encouraging the evaluation of the drawing function's value won't do anything because it doesn't actually cause the state monad within the resulting `Widget` to get evaluated in terms of the current (previous) rendering state. Does that make sense?

**Comment by simonmichael** [comment]
Thanks for your explanations, they are very clear. So, no hope of forcing the viewport to be created during the event handler - got it. Your alternative idea is great, and having it laid out by you will save me a lot of additional thinkering. Thanks!

**Comment by simonmichael** [comment]
If this were to be in the FAQ, do you think this would work ?

Q. How do I set the viewport's scroll position before the widget is rendered for the first time ?

A. You can't get the actual viewport until the widget has been rendered at least once.
But you can send a scroll request to it by name, even before it exists, eg `setTop (viewportScroll name) row`, which will be applied during the rendering pass.

**Comment by jtdaugherty** [comment]
I can see that being useful, but I hesitate to make it a FAQ entry because it's very specific to a use case that I haven't seen come up before. But I now wonder: are there any documentation updates I could make in the API docs or user guide that would help clarify any of the concepts here, or that you think would have helped make this easier? I'm just trying to think about ways to fold your FAQ entry material into the existing docs in a useful way.

**Comment by simonmichael** [comment]
Sorry, I don't know the docs well enough to suggest a better change.

**Comment by jtdaugherty** [comment]
No problem! I just made a commit along these lines (mentioned just above this comment). What do you think?

**Comment by jtdaugherty** [comment]
(And another commit as well.)

**Comment by simonmichael** [comment]
Great!

**Comment by jtdaugherty** [comment]
Okay, great. Is there anything else we should discuss before we close this?

**Comment by simonmichael** [comment]
@jtdaugherty I've now actually looked up the [viewportScroll](https://hackage.haskell.org/package/brick-0.65/docs/Brick-Main.html#g:2) you mentioned. I didn't find it in recent researches; I found the Viewport stuff in Widgets.Core and thought that was it. Is there any reason for them to be separated ? (I have been re-learning the API mainly via multiple hoogle/hackage browser tabs, which is not that easy as there's a lot in brick.) 

Separately, perhaps things are clearer in the user guide, but I discovered that late, so didn't come via that route. Perhaps it would make sense to include more linkage from the haddocks to that guide ? It's pretty great and worth highlighting.

**Comment by jtdaugherty** [comment]
The main reason that both `lookupViewport` and `viewportScroll` are in `Brick.Main` rather than `Brick.Widgets.Core` is because they run in `EventM`, which is sorta the language of `Brick.Main`. The stuff that lives in `Brick.Widgets.Core` is all stuff that builds or modifies `Widget`s.

If I linked from the Haddock docs to the user guide, that would make for a lot of links to keep from going stale. I mention both in the README in hopes that the User Guide will get some attention, but I know that most Haskell programmers are conditioned to check the API docs first and probably not even expect something like the User Guide here.

How about I mention the `Brick.Main` stuff from `Brick.Widgets.Core`? Would that help?

**Comment by jtdaugherty** [comment]
(Just pushed a commit)

**Comment by simonmichael** [comment]
Ok your call, personally I would consider one more user guide link at https://hackage.haskell.org/package/brick-0.65/docs/Brick.html, even thought it's right above in the readme.. people don't always come in that way or read through all the hackage boilerplate. 

Links between the two viewport-ish sections will be great.

Close at will - thanks @jtdaugherty !

**Comment by jtdaugherty** [comment]
Okay, I'll one to that root module. Thanks for the discussion!

**Comment by jtdaugherty** [comment]
(Commit pushed)
