### ISSUE TITLE
Layers in Widget

### ISSUE THREAD

**Issue by ts468** [jtdaugherty/brick#35]
Hi Jonathan,

thank you very much for the amazing "brick" library! It's great working with it. :)

I'm looking for a way to have layers within a "Widget", not just within an "App". I wondered if it would be possible to change the "image" in "Result" from "Image" to "[Image]", and then change "renderFinal" to flatten the "List" before passing it to "picForLayers"? Do you see any problems with that approach, and if not, would you be interested in integrating a patch if I would come up with the necessary changes?

Many thanks!

**Comment by jtdaugherty** [comment]
I'm glad to hear that the library is working well for you.  Thanks!

As for layers, this is something I have wanted myself. At present, more is needed from the underlying `vty` library to support this.  The reason is that the `vty` library's `Picture` type is where layers are kept and where "compositing" of those layers into a final `Image` is performed, including dealing with cursor location info.  You can read a bit more in the `vty` issue I filed about this very feature back in June:

https://github.com/coreyoconnor/vty/issues/73

**Comment by jtdaugherty** [comment]
(Needless to say, I have not had time to make patching `vty` for this a priority, but if this is something you want to tackle, you could coordinate with Corey about it on that ticket. I would also be interested to stay abreast of any developments.)

**Comment by jtdaugherty** [comment]
Since this isn't something we can do much about in `brick` at the moment, I'm going to close this.  However, if/when it becomes feasible I'm happy to re-open this and resume discussion about it!

**Comment by ts468** [comment]
Hi Jonathan,

thank you very much for your detailed explanation, and sorry for the late reply.
I indeed had a look into `vty`, and it seems as one would have to write a function that converts `DisplayOps` back into `Image`, so more or less the reverse  for `displayOpsForImage`. Unfortunately, that's quite some work. So I'll probably stay with a list of `Widget`s for now that I somehow `concat` along the drawing pipeline.

Many thanks for  your help!
Thomas
