### ISSUE TITLE
List scrolling is not working when mouse is enabled

### ISSUE THREAD

**Issue by yaitskov** [jtdaugherty/brick#354]
Hi,

List widget doesn't handle MouseDown events with BScrollUp/BScrollDown.
Once mouse support is enabled events used for scrolling by List widget stop occurring.

**Comment by jtdaugherty** [comment]
Can you provide more details on both of the statements you made above? Or a demo program that has undesirable behavior? That would help me understand what is going on.

**Comment by yaitskov** [comment]
Take ListDemo.hs with a list taller than terminal window.
Roll mouse wheel - current item changes.

Replace defaultMain with:

```
let buildVty = do
        v <- V.mkVty =<< V.standardIOConfig
        V.setMode (V.outputIface v) V.Mouse True
        return v
  initialVty <- buildVty
  void $ M.customMain initialVty buildVty Nothing theApp initialState 
```

With this changes spinning mouse wheel doesn't change current list item.

**Comment by jtdaugherty** [comment]
Thanks, that helps. You're right that the List doesn't have a built-in handler for the mouse wheel events. I'd rather not add one because that behavior is likely to be application-specific. But you can handle those events in your own event handler and use the List API to manipulate the selected item as you see fit.

If you're seeing different behavior with mouse mode disabled, that is likely because your terminal emulator is converting the mouse wheel events into the equivalent of arrow keys or Page Up and Down, which the List does support. Different terminal emulators (and `screen`/`tmux`) handle that differently, so you'll have to figure out what you want the behavior to be.

If you need any help with that, let me know!

**Comment by refaelsh** [comment]
I have exactly the same issue.

> I'd rather not add one because that behavior is likely to be application-specific.

This is a string statement. When would want the mouse wheel to NOT scroll the list up and down?

> But you can handle those events in your own event handler
Could you please point me in the documentation for that? Or, maybe one of the examples?
Because I can't find anything, and I can't figure it out myself.

**Comment by jtdaugherty** [comment]
> Could you please point me in the documentation for that?

I recommend exploring to see what events Brick receives and reports to the application when the mouse wheel is used. Once you know which events are going to be delivered, it ought to be pretty easy to write an event handler for each one that manipulates your list in the way that you desire.

**Comment by refaelsh** [comment]
> I recommend exploring to see what events Brick receives and reports to the application when the mouse wheel is used. 

Found it: https://hackage.haskell.org/package/vty-5.38/docs/Graphics-Vty-Input-Events.html#t:Button.
Thanks! :-)
