### ISSUE TITLE
Wide characters taking up more space than needed on border labels

### ISSUE THREAD

**Issue by iogrt** [jtdaugherty/brick#356]
Using emojis inside border labels is making the box take up 1 more character than needed.

Example:
![2021-12-26_19:41:52](https://user-images.githubusercontent.com/39342422/147419569-5f776035-7de5-4d1c-b28a-6bbd9c8274de.png)

```hs
simpleMain (borderWithLabel (str "🌀 test string") (vBox $ str <$> inits "HelloWorld"))
```

**Comment by jtdaugherty** [comment]
Thank you for the report! The state of wide unicode characters in terminals is not great. Brick (and its driver library, Vty), only have a little bit of control over how this works, unfortunately. You can read some details about this [here](https://github.com/jtdaugherty/vty/issues/175). Brick does its best to calculate the column width of Unicode characters, but it gets many of them wrong (because Vty gets them wrong). And Vty can't always get them right because even the terminal emulator must agree with Vty, and many terminal emulators do not even get the widths right.

So for now, I encourage you to stick to characters that don't suffer from this problem. (Everywhere in Brick UIs, not just border labels.)

**Comment by iogrt** [comment]
Thanks for the quick response, and sorry for the duplicate issue. I've been reading the threads that you have mentioned and understand why it's such a hard thing to get right.

Since I'm developing these scripts for myself, and for anyone who comes across this, I've found a way to tell Brick what size I have for my emojis (which is 2 width instead of one, for `ghci`):
```hs
-- imports
import qualified Graphics.Vty.Image.Internal as VI (Image (HorizText))
-- code
emoji s = raw $ VI.HorizText V.defAttr (L.pack s) 2 1
myApp = simpleMain (borderWithLabel (emoji "🌀" <+> str "test string") (vBox $ str <$> inits "HelloWorld"))

```

**Comment by jtdaugherty** [comment]
Thanks! That seems like it could work well for specific characters. Be sure to test on different terminal emulators, though; the width that you hard-coded must agree with what the emulator thinks, and that may vary, especially for characters more recently added to the Unicode standard.

**Comment by jtdaugherty** [comment]
(Also, since you used an "internal" Vty API, that is not guaranteed to be stable.)
