### ISSUE TITLE
Displaying ANSI-escaped text from another library

### ISSUE THREAD

**Issue by thomasjm** [jtdaugherty/brick#377]
I'm looking at integrating Hedgehog (a QuickCheck-like library) with my test framework [Sandwich](https://codedownio.github.io/sandwich/). 

Hedgehog already has the ability to produce nicely formatted output with ANSI colors and bars and stuff, and I'd like to find the easiest way to embed it into a Brick app. As you can see in the picture below, the naive approach of including the ANSI-formatted string directly messes up the formatting, as Brick seems to count the escape characters as having "width" (as described in #181).

![image](https://user-images.githubusercontent.com/1634990/178616918-c224f3cb-6921-4a2d-ad30-f77b12904dab.png)

This can probably be solved at the Brick level, but I'm considering the following ideas and looking for advice:

1) Rewrite all the Hedgehog formatting logic in Brick/Vty style. Downsides: there's kind of a lot of code, and it would be a maintenance burden, see [here](https://hackage.haskell.org/package/hedgehog-1.1.1/docs/src/Hedgehog.Internal.Report.html#ppResult).
2) Change Brick to ignore ANSI escape chars when calculating widths
3) Write my own preprocessing step of some kind to convert ANSI-formatted text to Brick widgets
4) Use some external took like this `ansiImage` mentioned in #181? (Not sure if this still exists, I couldn't find it right away.)

Would love to know what you think might make the most sense. Thanks!

**Comment by jtdaugherty** [comment]
> Change Brick to ignore ANSI escape chars when calculating widths

This is actually a Vty behavior. Since Vty makes the assumption that it (naturally) is in charge of layout, it also makes the assumption that the text to be displayed does not contain layout-affecting characters. Changing Vty to work with text that contains escapes essentially requires implementing a reverse transformation `recoverImage :: Text -> Image` that knows enough about layout control characters to reconstruct an `Image`. (And that's more than just simple escapes; it requires a fully general parser for all control sequences to properly scrub them from the input stream at best, or semantically interpret them at worst.) It looks like `ansiImage` is an attempt at that, but detecting things like bold text is easier than recovering layout information. For now, it is just the case (and it is documented, too) that Vty and Brick should only be given text that is free of escape sequences.

> Rewrite all the Hedgehog formatting logic in Brick/Vty style

My advice, for what it's worth, would be to *just* rewrite Hedgehog to use an abstract output backend interface, one implementation of which would be its current behavior. That way, you could tack on Vty-only or Brick-and-vty implementations. So in other words, make Hedgehog care even less (not more) about precisely how the output implementation works.

**Comment by jtdaugherty** [comment]
> it would be a maintenance burden, see [here](https://hackage.haskell.org/package/hedgehog-1.1.1/docs/src/Hedgehog.Internal.Report.html#ppResult).

Looking over that code, I suspect the maintenance burden would indeed be reduced by loosening the coupling between output representation and internal format. Much of that module could probably get easier to express and maintain with a Brick implementation, too. (A non-Brick implementation could still have its uses, but I bet a Brick implementation would be shorter since it provides a lot of high-level layout functionality.)

**Comment by jtdaugherty** [comment]
`ppFailureLocation` is a good example of a function that currently does a bit of book-keeping that would almost certainly go away entirely with a Brick implementation, FWIW.

**Comment by thomasjm** [comment]
Thanks for the fast and thorough response!

Actually now that I look at it, it seems that this [Text.PrettyPrint.Annotated.WL](https://hackage.haskell.org/package/wl-pprint-annotated-0.1.0.1/docs/Text-PrettyPrint-Annotated-WL.html) is already pretty abstract. It may be that I just need to write (or find) a Brick renderer for that...

FWIW, in my normal daily usage of Sandwich I sometimes encounter other random ANSI color escapes that cause output glitches in the TUI. This is just because a lot of software and tools I happen to be testing sometimes decide to introduce color into their output. I totally agree with you that handling all possible escape codes would be hairy, especially the layout-affecting ones -- but I think a little bit of work handling the "simple" ones like color would go a long way. Maybe if there were a function in `Brick.Util` that did some simple preprocessing of such codes?

**Comment by jtdaugherty** [comment]
> Maybe if there were a function in Brick.Util that did some simple preprocessing of such codes?

I am reluctant to add such a thing to the library; I would rather emphasize the importance (to me) of using the Brick and Vty APIs, and encourage upstream application developers to not just assume they can dump ANSI escapes willy-nilly. If someone wanted to write a third-party package providing something like `ansiImage`, that would be another way for such a thing to exist without me needing to take on maintenance of it. 😊

**Comment by thomasjm** [comment]
Got it, makes sense! I'll try solving the Hedgehog issues with `Text.PrettyPrint.Annotated.WL`.

**Comment by jtdaugherty** [comment]
Okay, cool. Let me know if I can help!

**Comment by emilaxelsson** [comment]
I have an implementation of `ansiImage` [here](https://github.com/emilaxelsson/trackit/blob/master/src/TUI.hs). It only supports basic colors ATM, but it could easily be extended. I wouldn't mind extracting it as a library if there's demand.

**Comment by thomasjm** [comment]
Ooh, thanks for pointing that out @emilaxelsson! I'll have to do a little exploration but I think that could be useful.

**Comment by refaelsh** [comment]
> TADA (using a `Text.PrettyPrint.Annotated.WL` renderer):
> 
> ![image](https://user-images.githubusercontent.com/1634990/178942051-822e3a5b-bb4d-47af-836a-c612bc3159ba.png)
> 
> Next step is to explore whether `ansiImage` can help with general purpose stray color codes...

Could you please elaborate on your solution?
I am having exactly the same problem with escape codes as you.

**Comment by thomasjm** [comment]
The solution was, if you're trying to render something that comes in some abstract form like [Text.PrettyPrint.Annotated.WL](https://hackage.haskell.org/package/wl-pprint-annotated-0.1.0.1/docs/Text-PrettyPrint-Annotated-WL.html), then you can write a function to convert that to the proper Brick primitives.
