### ISSUE TITLE
More flexibility in border attributes

### ISSUE THREAD

**Issue by saltzadam** [jtdaugherty/brick#404]
This is inspired by https://github.com/jtdaugherty/brick/issues/389, hope I'm not breaking etiquette!

As I understand it, the 'default' border attribute is `borderAttr`. This can be overridden for a particular widget using the method in the issue above. But this will change all of the borders in that widget. My particular use case is to have something like [Swarm's](https://github.com/swarm-game/swarm/blob/71403e9393b957d7f9a010e2d430e0962cfa0ffb/src/Swarm/TUI/Panel.hs#L35) `Panel` wrapped around other Widgets with borders. I could `freezeBorders` of the "child" widgets but now they can't be changed later.

We could get more flexibility by adding

`hBorderWithAttr :: AttrName -> Widget n`

`vBorderWithAttr :: AttrName -> Widget n`

etc so that `hborderWithAttr = hBorderWithAttr borderAttr`. Now one could redefine `panel` to use `panelBorderAttr` and let other Widgets use `borderAttr` (or another variant).

What do you think? Happy to put together a pull request but wanted to raise it here first.

**Comment by jtdaugherty** [comment]
If what you specifically want is to change the borders of only vertical or horizontal borders, then what I'd like to do instead is add `hBorderAttr` and `vBorderAttr` that specialize `borderAttr`. That way, the current attribute management API can be used to customize those borders for a particular widget but otherwise border attribute semantics will be unchanged and the API will not need to be extended. (Those new attributes will inherit from `borderAttr` so if they aren't customized then all existing applications will not change behavior.)

**Comment by jtdaugherty** [comment]
(And adding these attributes doesn't prevent you from doing exactly as you did above, but instead you'd use the various attribute override functions from `Brick.Widgets.Core`.)

**Comment by jtdaugherty** [comment]
This is now implemented on `master` in the commit linked above.

**Comment by jtdaugherty** [comment]
This change is now released in `1.4`.

**Comment by saltzadam** [comment]
Thank you!!
