### ISSUE TITLE
Widgets in State and specifaclly the List example

### ISSUE THREAD

**Issue by refaelsh** [jtdaugherty/brick#406]
I need help please :-)

Lets say I have the followign signature of `theApp` thingy:
```haskell
theApp :: App [String] e ()
```

Here is how my `appDraw` function looks like:
```haskell
myAppDraw :: [String] -> [Widget ()]
myAppDraw codedLines =
  [ borderWithLabel
      (str "Tree")
      (renderList renderingFunction True createList)
  ]
  where
    renderingFunction _ codedLine = -- some not important code goes here
    createList = list () (fromList codedLines) 1
```

Several questions I need help with:
1. If I understand correctly, the list gets re-created every time there is a state change? Right? Its bad, right? How can this be avoided?
2. This way, how can I handle list events using `handleListEvent` (from here: https://hackage.haskell.org/package/brick-1.4/docs/Brick-Widgets-List.html#g:3), since I dont have `List` in my state.

And in general, according to the List example (and probably several others) I am supposed to keep GUI (or this case TUI) widgets in my State. Uncle Bob's `Seperation Of Thingies` teaches us that GUI (Brick's List) stuff and buiesness logic stuff (Application State) should be seperate.

P.S.
I am aware that I am goining against the List example (https://github.com/jtdaugherty/brick/blob/master/programs/ListDemo.hs).

**Comment by jtdaugherty** [comment]
> If I understand correctly, the list gets re-created every time there is a state change? Right? Its bad, right? How can this be avoided?

In the code you provided, this is correct: the list gets re-created from your `codedLines` on each rendering. And yes, this is to be avoided and will in fact just be broken because it completely loses the benefit of the list, which is that the list you create contains state that tracks, for example, the list scrolling position.

The right way to do this is to make the *list* your state (or part of your state), meaning that instead of `App [String] e ()` you would have something like
```haskell
data Name = TheList
data MyState =
    MyState { _theList :: List Name String }
makeLenses ''MyState

myApp :: App MyState e ()
myApp = ...

main = defaultMain myApp $ MyState $ list TheList (fromList codedLines) 1
```
Once you have that, we can answer your second question,
> This way, how can I handle list events using handleListEvent, since I dont have List in my state.

To handle list events, you *must* have a list in your state so that the list event handler has a list to update.
```haskell
myHandler ::  BrickEvent Name e -> EventM Name MyState ()
myHandler e =
    zoom theList $ handleListEvent e
```

**Comment by jtdaugherty** [comment]
Also, you can see a complete working example of how to use the list in the way that I described above by looking at the list demo program:

https://github.com/jtdaugherty/brick/blob/master/programs/ListDemo.hs

There are many demo programs; they should be helpful in illustrating how to make complete working programs!

**Comment by jtdaugherty** [comment]
I should point out that the list demo program uses a `List` as the application state so it doesn't need the `zoom`/lens update that I used in the example above. (But any application of any sophistication *will* need that.)

**Comment by refaelsh** [comment]
Thank you very much for you answer @jtdaugherty. I understand all your answers, but: what about seperation of concerns? It feels wrong to me to have a widget (List) as part of the State.

**Comment by jtdaugherty** [comment]
The "widget" is the part that gets drawn; the "state" here is the `List` value that you create with the `list` function. The separation of concerns here is that the `List` is kept in your state, updated by event handlers, and then used to create a drawing (a "widget"). It's possibly confusing because the term "widget" is used by other frameworks to mean *both* the thing you see on the screen *and* its underlying state. In brick, those are separated. Does that make sense?

**Comment by jtdaugherty** [comment]
Another thing I wanted to point out: note that the `Widget` get gets created by the drawing function *never* gets stored in your state. It is constructed by your drawing function and then rendered immediately. In Brick, a `Widget` is basically a set of drawing instructions constructed *from* some state value.

**Comment by kquick** [comment]
You might also be interested in the `brick-panes` package (https://hackage.haskell.org/package/brick-panes), @refaelsh .  Although the widget state still must be part of your global state, it does provide one approach to keeping those more "separated" from each other.  Using the brick-panes package, the `List` Widget would be the internal state for a `Pane` and the visual representation of your application would be a `Panel` consisting of a number of independent Panes, which are composed with your applications core state at the outermost definition.  You would then have something like:

```
data MyAppMainState = MainState { ... }

data ListingPane

instance Pane Name e ListingPane where
    data (PaneState ListingPane e) = LP (List Name String)
    drawPane (LP l) _  = renderList (const str) False l
    handlePaneEvent _ e (LP l) = LP $ nestEventM' l (handleListEvent ev)
    ...

type AppState = Panel Name e MyAppMainState '[ ListingPane, ...]
```

In this way, the implementation of the `ListingPane` is separated from the remainder of your application (and could be in a separate module).  If, for example, you later choose to switch from a `List` to an `Editor` (or a list and an editor to support a search box, etc.), the changes will likely be limited to the `Pane` instance for the `ListingPane`.

**Comment by refaelsh** [comment]
> You might also be interested in the `brick-panes` package (https://hackage.haskell.org/package/brick-panes), @refaelsh . Although the widget state still must be part of your global state, it does provide one approach to keeping those more "separated" from each other. Using the brick-panes package, the `List` Widget would be the internal state for a `Pane` and the visual representation of your application would be a `Panel` consisting of a number of independent Panes, which are composed with your applications core state at the outermost definition. You would then have something like:
> 
> ```
> data MyAppMainState = MainState { ... }
> 
> data ListingPane
> 
> instance Pane Name e ListingPane where
>     data (PaneState ListingPane e) = LP (List Name String)
>     drawPane (LP l) _  = renderList (const str) False l
>     handlePaneEvent _ e (LP l) = LP $ nestEventM' l (handleListEvent ev)
>     ...
> 
> type AppState = Panel Name e MyAppMainState '[ ListingPane, ...]
> ```
> 
> In this way, the implementation of the `ListingPane` is separated from the remainder of your application (and could be in a separate module). If, for example, you later choose to switch from a `List` to an `Editor` (or a list and an editor to support a search box, etc.), the changes will likely be limited to the `Pane` instance for the `ListingPane`.

Interesting. Thank you. I will go read it. UPDATE: I've read it -> It seems like it should be part of Brick.

**Comment by refaelsh** [comment]
> Another thing I wanted to point out: note that the `Widget` that gets created by the drawing function _never_ gets stored in your state. It is constructed by your drawing function and then rendered immediately. In Brick, a `Widget` is basically a set of drawing instructions constructed _from_ some state value.

I understand a bit better now. But:
1. It still does not quites my "Separation of Concern" concern. Tommorow, I will change Brick for something else, but it would be hard because the State of my application is defined in terms of Brick's thingies (e.g., List). This kind of problem does not exists in other GUI (TUI) frameworks (if one uses MVVM offcourse). I think.
2. Why do I have to take care of List's event outside of List? The `handleListEvent` function should be hidden from the user somewhere inside the List widget and always enabled/called. This is how its done in any other GUI/TUI fram,ework I've ever used.

**Comment by kquick** [comment]
> It seems like it should be part of Brick.

I appreciate the endorsement, but I think it's better as a separate library.  The brick-panes library uses specific approaches to encapsulation, including design choices such as class dispatch, type-level lists, data families, and other elements that are not necessarily appropriate to all situations, whereas brick itself is more conventional and builds the basic elements ("bricks") to support many different TUI approaches (as a framework provides more conveniences, it also makes more decisions on your behalf, which partly answers your second item in your post above).  I highlighted the brick-panes library because it seemed like it might be of interest regarding your concerns, but that's not necessarily the case for other brick users or even for your ultimate application design.  If it is, that's wonderful, but if not, you can still use other techniques on top of brick.

**Comment by jtdaugherty** [comment]
> It still does not quites my "Separation of Concern" concern. Tommorow, I will change Brick for something else, but it would be hard because the State of my application is defined in terms of Brick's thingies (e.g., List). This kind of problem does not exists in other GUI (TUI) frameworks (if one uses MVVM offcourse). I think.

I'm not sure what definition of "separation of concerns" you are using, but SoC does not mean "have no application state." Brick does make particular design choices in *how* to separate concerns, and those choices could be made in other ways. The Brick approach is the opposite of most graphical UI frameworks that combine state, presentation, and event handling in objects (usually called "widgets"). Brick separates those in the draw/event handling functions and decouples the state representation from how drawing and event handling are done. This is a particular approach to separating concerns. The problem Brick solves is *much* worse in other frameworks (e.g. GTK, QT, etc.). However, I would happily encourage you to use other frameworks if they take an approach that works better for you!

> Why do I have to take care of List's event outside of List? The handleListEvent function should be hidden from the user somewhere inside the List widget and always enabled/called. This is how its done in any other GUI/TUI framework I've ever used.

This is a consequence of how Brick is designed, and is a deliberate choice. The `vty-ui` package that I wrote before I writing `brick` actually took this approach, but it was just as difficult to use as other UI frameworks. The separation you're describing is actually a consequence of exactly the separation of concerns you are asking for. Still, I would say that if you don't share that perspective, it might be best to consider other frameworks that meet your needs better or take an approach that works better for you!

With all that said, I'm curious if there's anything else I can help with as far as your original inquiry is concerned. If not, please close this - or let me know what else I can help with.

**Comment by refaelsh** [comment]
I understand abit more now. Thank you very much. I will close this for now. But I reserve the right for continue question in the future :-)

**Comment by jtdaugherty** [comment]
Thanks, @refaelsh - please feel free to open issues whenever you need help.

**Comment by refaelsh** [comment]
> The right way to do this is to make the list your state (or part of your state)

Can this be avoided? I do not want to make List part of my state.
I will explain.
I am well proficient in OOP (or at least I think so), and in the MVVM design pattern, which is most suitable for GUI/TUI desktop applications. One of the main tenants of the MVVM design pattern, is that the ViewModel should be completely separate from the View. The main reason for that is that tomorrow, when the GUI/TUI framework changes, the ViewModel does not need to change. Now, if I put List as part of my state, e.g., a field in a record that represents the state of the ViewModel, I am coupling the ViewModel with the View framework - I wish to avoid this. In any OOP framework it's very easy, but here, in Brick, I don't know how to achieve this since what I understand from you is that List has to be part of the state.

**Comment by jtdaugherty** [comment]
I'm not really that sure that it makes sense to apply the MVVM design pattern *in Haskell* because Haskell is not an OO language. With that said, I don't know enough about what a ViewModel *should* be to say how to implement "proper" MVVM in Haskell.

> I don't know how to achieve this since what I understand from you is that List has to be part of the state.

Are you clear on the fact that the "List" here is the list's "model"? I'm saying you'll need to embed that "model" in the bigger "model" of the application, i.e., the application state. It's unavoidable here, and it's no different than what you'd do in an OO language. In other words, for every thing visible on the screen there is some underlying state that represents that thing. It must be tracked somewhere, and in Brick applications the place to track it is in the application state that is kept separate from what is drawn on the screen, the `Widget`.

The separation in a Brick application is not all that different from what you might be used to in MVVM or MVC or whatever. In the Brick context, you have three distinct components in the application design: the state, the drawing routine, and the event handling routine. Naturally, though, each of those will be a reflection of the structure of the other two! There's no way around that, and there doesn't need to be. But *within* the state or the handler routines, in a functional language like Haskell we use functional abstraction to make it easier to abstract over some bits of state to make the drawing routine and event handler routine more flexible.

So to some extent it may be necessary for you to set aside your existing ways of thinking and think about things the way a functional programmer would; it's something we all have to do when using a language like Haskell, and often those of us who learn to think that way find that it actually helps us think more clearly about our programs in *other* languages. In Haskell, the basic unit of program organization is the function, but in OO languages the emphasis is much more on classes, interfaces, and inheritance. That gives rise to design patterns that work best *in those languages*.

**Comment by jtdaugherty** [comment]
Another thing to mention is that OO languages combine state and the functions that operate on that state, i.e., they combine it into classes. Design patterns that work well for state/function combinations usually rely heavily on localized mutation and a way of dividing up state along responsibility lines. In Haskell we don't use that kind of organizational scheme, which is why the application state in a Brick application must contain *everything* that is mutable.

**Comment by refaelsh** [comment]
Wow! :-) Thank you very much for the very thought out answer. I will go meditate on it.

**Comment by refaelsh** [comment]
> I'm not really that sure that it makes sense to apply the MVVM design pattern in Haskell because Haskell is not an OO language. 

I beg to differ. The 2 main benefits of MVVM are as follows:
1. Loose coupling between View and ViewModel so that the View can be freely changed without changing the ViewModel.
2. Using MVVM it is possible to Unit Test the ViewModel, otherwise, Unit Test would be near impossible.
All of the above states nothing about OOP, these are general rules that should apply regardless of the paradigm being used - be it OOP, Functional, Procedural.

But, and there is always a but, having said all of the above, after reading your answer, I am starting to have doudts... Need more meditating.

**Comment by refaelsh** [comment]
> Are you clear on the fact that the "List" here is the list's "model"?

Yes.

**Comment by refaelsh** [comment]
> It's unavoidable here,

I understand. Bummer, but I understand.

**Comment by refaelsh** [comment]
> and it's no different than what you'd do in an OO language.
I beg to differ. In WxWidgets, you are right, but in macrosoft's WPF, you would be wrong.

**Comment by refaelsh** [comment]
> in Brick applications the place to track it is in the application state that is kept separate from what is drawn on the screen, the Widget

Every GUI framework I know, its not like this. But, they are all OOP...

**Comment by refaelsh** [comment]
> in a functional language like Haskell we use functional abstraction to make it easier to abstract over some bits of state to make the drawing routine and event handler routine more flexible.

I dont understand a word of you are saying here.

**Comment by refaelsh** [comment]
> think about things the way a functional programmer would

I have no idea how to do it. How can I teach my self to think like a Functional Programmer?

**Comment by refaelsh** [comment]
I am done venting :-)

I will now go and think more deeply about this:
> In the Brick context, you have three distinct components in the application design: the state, the drawing routine, and the event handling routine.

I think there lies my answer. Or dragons.

**Comment by jtdaugherty** [comment]
> The 2 main benefits of MVVM are as follows:

I'm glad you're off thinking about this, and I want to respond a bit more. MVVM is a design pattern, but that doesn't mean it's always the best or most appropriate way to do things. And even if it was, at the end of the day, *brick is not an MVVM framework*. I don't intend for it to be. It takes the design approach that made the trade-offs I wanted to make, in a language I wanted to use. It uses an approach that is pretty familiar to people who have used other, similar Haskell libraries (like `gloss`). So with all that said, I can't really defend the use of MVVM. That would be like someone going to a Lebanese restaurant and asking why there aren't any cheeseburgers on the menu. :)

> How can I teach my self to think like a Functional Programmer?

Write code in functional languages, study code in functional languages, learn about how functional language design trade-offs differ from the languages you are used to, and think deeply about what other functional programmers say about using functional languages. Be open to looking at programming differently. It takes time!

**Comment by refaelsh** [comment]
Thank you. Thank you very much.

**Comment by refaelsh** [comment]
> I will now go and think more deeply about this:
> 
> > In the Brick context, you have three distinct components in the application design: the state, the drawing routine, and the event handling routine.
> 
> I think there lies my answer. Or dragons.

Can you please take a look here: https://gitlab.com/refaelsh/giter/? The `master` branch.
I want to ask you, please, if this is an idiomatic `Brick` wise code? Not Haskell wise, but Brick wise.
Haskell wise, It's probably not idiomatic - I am still learning :-)

Especially, did I get this: `three distinct components in the application design: the state, the drawing routine, and the event handling routine` right?

**Comment by jtdaugherty** [comment]
@refaelsh - is there a specific bit of code or module you'd like me to take a look at?

**Comment by jtdaugherty** [comment]
I ask because Brick's API basically *forces* you to at least "get right" the bit I said above in the sense that you must declare a drawing function, an initial state, and an event handler, but I don't know if you're looking for more specific feedback.

**Comment by refaelsh** [comment]
> @refaelsh - is there a specific bit of code or module you'd like me to take a look at?

Yes, I should have specified it.

Main.hs file:
1. Ignore the `appStartEvent` - it's still a work in progress.
2. Concentrate please on the `appDraw` and `appHandleEvent` functions.

View folder:
1. Files that end in *View.hs: contain only Brick's `draw` functions.
1. Common.hs - ignore it please.

ViewModel folder:
1. Every *View.hs file has a corresponding *VM.hs file (VM stands for ViewModel).
The *VM.hs files are responsible to mutate the state.

P.S.
Please ignore everything in the Model folder: it's the main logic part of the program and deals mainly with string parsing.

**Comment by refaelsh** [comment]
> That would be like someone going to a Lebanese restaurant

I have a good one I enjoy just around the corner from where I live.

**Comment by refaelsh** [comment]
Aside question please.


> study code in functional languages

Sound advice. Can you please specify, out of here: https://github.com/jtdaugherty/brick#featured-projects, which one is most idiomatic, Brick's wise?

**Comment by jtdaugherty** [comment]
> Can you please specify, out of here: https://github.com/jtdaugherty/brick#featured-projects, which one is most idiomatic, Brick's wise?

I don't know since I haven't looked at the source for almost all of them. But one application to look at is [tart](https://github.com/jtdaugherty/tart).

**Comment by jtdaugherty** [comment]
As for your code, the various drawing functions look about like I would expect. My only feedback on the event handler code is that it would be vastly simplified by using lenses in a few places. The "view model" modules follow the pattern I would expect as well: constructors like `new` to initialize bits of state and event handlers to modify those bits of state.

One thing I want to point out is that code like [this](https://gitlab.com/refaelsh/giter/-/blob/master/src/ViewModel/TreeVM.hs#L54) that does possibly expensive things in the event handler will not scale in the long run because the event loop and the renderer are paused while the event handler is running. If it takes a while (more than a few tens of milliseconds) then that may be very noticeable UI latency for the user. In the long run it'll be best to move that I/O into some asynchronous machinery to avoid that problem.

**Comment by refaelsh** [comment]
Thank you very much for your answer!!! It puts my mind at ease.


> My only feedback on the event handler code is that it would be vastly simplified by using lenses in a few places.

Agreed. I will get to it. Lenses are currently still too advanced for me (there be dragons!), I am, still wrapping my head around Monads.

> One thing I want to point out is that code like [this](https://gitlab.com/refaelsh/giter/-/blob/master/src/ViewModel/TreeVM.hs#L54)

Yes, yes. Off course - this is just my temporary oversight, it will be fixed. I've already fixed a very similar situation using `forkIO` here: https://gitlab.com/refaelsh/giter/-/blob/master/src/ViewModel/TerminatorVM.hs#L74.

**Comment by refaelsh** [comment]
> But one application to look at is [tart](https://github.com/jtdaugherty/tart).

I will definitely take a close and personal look at that.
