### ISSUE TITLE
Complex state and the `handleListEvent` function

### ISSUE THREAD

**Issue by refaelsh** [jtdaugherty/brick#407]
Here is my state:
```haskell
data State where
  State ::
    { listWidget :: List () String
    } ->
    State
```

Here is my `appDraw` function:
```haskell
draw :: State -> [Widget ()]
draw state =
  [ borderWithLabel (str "Tree") $
      renderList (\_ b -> str b) True (listWidget state)
  ]
```

And here is my `appHandleEvent` function:
```haskell
handleEvents :: BrickEvent () e -> EventM () State ()
handleEvents (VtyEvent e) = do
  state <- get
  let bla = listReplace (fromList ["some_thing", "1", "2", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "3", "ooo"]) (Just 2) (listWidget state)
  (_, ()) <- nestEventM (listWidget state) $ do
    handleListEvent e
  put state {listWidget = bla}
handleEvents _ = return ()
```

The problem is in `handleListEvent` usage, I dont know why but no events are passed to the list: pressing HOME or END does nothing for example.

Please help :-)

**Comment by jtdaugherty** [comment]
In this code,
```haskell
handleEvents :: BrickEvent () e -> EventM () State ()
handleEvents (VtyEvent e) = do
  state <- get
  let bla = listReplace (fromList ["some_thing", "1", "2", ..., "ooo"]) (Just 2) (listWidget state)
  (_, ()) <- nestEventM (listWidget state) $ do
    handleListEvent e
  put state {listWidget = bla}
handleEvents _ = return ()
```
the events are not having any effect for two reasons: first, because the result of `nestEventM` is being thrown away in `(_, ())` since the *new* list state in the `_` position is not being bound to anything and used. Second, the application state is being updated with `bla` *after* the event is handled, so `bla` becomes your final list state; even if we fix the `nestEventM` call, in the code above, `bla` would be the state value used anyway, so it wouldn't matter that an event was handled.

Here's how to write it (without the `listReplace`, which isn't really doing anything here that couldn't be done the first time the list is created; if you want to populate the list). This also uses the simpler `nestEventM'` which allows you to just bind the new state value.

```haskell
handleEvents :: BrickEvent () e -> EventM () State ()
handleEvents (VtyEvent e) = do
  state <- get
  newListState  <- nestEventM' (listWidget state) $ do
    handleListEvent e
  put $ state { listWidget = newListState }
handleEvents _ = return ()
```

**Comment by jtdaugherty** [comment]
I also wanted to mention that the implementation I gave above,
```haskell
handleEvents :: BrickEvent () e -> EventM () State ()
handleEvents (VtyEvent e) = do
  state <- get
  newListState  <- nestEventM' (listWidget state) $ do
    handleListEvent e
  put $ state { listWidget = newListState }
handleEvents _ = return ()
```
becomes even simpler if you generate lenses for your state fields:
```haskell
handleEvents :: BrickEvent () e -> EventM () State ()
handleEvents (VtyEvent e) = do
  zoom listWidget $ handleListEvent e
handleEvents _ = return ()
```
If you're interested in going that route, I'd be happy to provide pointers/info.

**Comment by refaelsh** [comment]
> (without the listReplace, which isn't really doing anything here that couldn't be done the first time the list is created)

But I need to completly repopulate the list with fresh data upon every `(VtyEvent e)` - in the future it will be upon certain key hit.

**Comment by refaelsh** [comment]
> In this code,
> 
> ```haskell
> handleEvents :: BrickEvent () e -> EventM () State ()
> handleEvents (VtyEvent e) = do
>   state <- get
>   let bla = listReplace (fromList ["some_thing", "1", "2", ..., "ooo"]) (Just 2) (listWidget state)
>   (_, ()) <- nestEventM (listWidget state) $ do
>     handleListEvent e
>   put state {listWidget = bla}
> handleEvents _ = return ()
> ```
> 
> the events are not having any effect for two reasons: first, because the result of `nestEventM` is being thrown away in `(_, ())` since the _new_ list state in the `_` position is not being bound to anything and used. Second, the application state is being updated with `bla` _after_ the event is handled, so `bla` becomes your final list state; even if we fix the `nestEventM` call, in the code above, `bla` would be the state value used anyway, so it wouldn't matter that an event was handled.
> 
> Here's how to write it (without the `listReplace`, which isn't really doing anything here that couldn't be done the first time the list is created). This also uses the simpler `nestEventM'` which allows you to just bind the new state value.
> 
> ```haskell
> handleEvents :: BrickEvent () e -> EventM () State ()
> handleEvents (VtyEvent e) = do
>   state <- get
>   newListState  <- nestEventM' (listWidget state) $ do
>     handleListEvent e
>   put $ state { listWidget = newListState }
> handleEvents _ = return ()
> ```

Yes, yes. I understood most of it. Now I go and meditate :-)

**Comment by jtdaugherty** [comment]
> But I need to completly repopulate the list with fresh data upon every (VtyEvent e) - in the future it will be upon certain key hit.

I wouldn't recommend doing this, but if you can share a bit more about what you are trying to accomplish, perhaps I can help with a way to handle this.

**Comment by refaelsh** [comment]
> I also wanted to mention that the implementation I gave above,
> 
> ```haskell
> handleEvents :: BrickEvent () e -> EventM () State ()
> handleEvents (VtyEvent e) = do
>   state <- get
>   newListState  <- nestEventM' (listWidget state) $ do
>     handleListEvent e
>   put $ state { listWidget = newListState }
> handleEvents _ = return ()
> ```
> 
> becomes even simpler if you generate lenses for your state fields:
> 
> ```haskell
> handleEvents :: BrickEvent () e -> EventM () State ()
> handleEvents (VtyEvent e) = do
>   zoom listWidget $ handleListEvent e
> handleEvents _ = return ()
> ```
> 
> If you're interested in going that route, I'd be happy to provide pointers/info.

No lenses for me in the meantime. Still learning Haskell and lenses feels (probably wrongly so) like somethig too heavy for a newby.

**Comment by jtdaugherty** [comment]
> No lenses for me in the meantime. Still learning Haskell and lenses feels (probably wrongly so) like somethig too heavy for a newby.

I totally understand. In that case I would definitely recommend skipping the lenses for now.

**Comment by refaelsh** [comment]
> > But I need to completly repopulate the list with fresh data upon every (VtyEvent e) - in the future it will be upon certain key hit.
> 
> I wouldn't recommend doing this

Why please? :-)

**Comment by refaelsh** [comment]
> > But I need to completly repopulate the list with fresh data upon every (VtyEvent e) - in the future it will be upon certain key hit.
> 
> but if you can share a bit more about what you are trying to accomplish, perhaps I can help with a way to handle this.

I am afraid to bore you with details. But basically, upon certain key hit, I need to go to a data base and bring new lines and completly repopulate the list with those new lines from the database.

**Comment by jtdaugherty** [comment]
> But basically, upon certain key hit, I need to go to a data base and bring new lines and completly repopulate the list with those new lines from the database.

That makes sense to me. This is a pretty common thing to want to do (i.e. go talk to external stuff like a database or network when an event occurs). In that case it makes sense that you would want to use `listReplace` (or even `list`!) to repopulate your list or reset your list state.

Here is something to keep in mind: while the event handler is running your database operation to repopulate the list, the event loop will not be able to handle more input events from the keyboard. That means that if your database query and list repopulation take more than a few milliseconds (which is likely), you will experience UI latency as you enter keystrokes because the event handler will not be able to run fast enough to keep up with your keystrokes and the UI will lag behind the input events.

This is a pretty common problem, and the equally common solution is to handle the database query asynchronously rather than doing the database query in the event handler itself. Doing it in the event handler is going to be a good way to get things working initially, but I wanted you to be aware of this issue so that if it happens, you know that your application will need to be designed a bit differently.

In Haskell, a very common way to deal with this sort of thing is to set up a [channel](https://hackage.haskell.org/package/base-4.17.0.0/docs/Control-Concurrent-Chan.html) between the event handler and a thread that takes care of the database queries. I don't know if you have experience with concurrent programming in other languages, but this is a way to send messages between threads. The idea is that you'd spawn a thread (at the start of your program, before Brick runs) that will be responsible for waiting for requests to get updates from the database. Your event handler would send that thread a message over the channel (which is very fast) and this would avoid UI latency. The thread would then receive the message and do the database query, then send the results back to the event handler using a custom event, at which point you'd use `listReplace` to update your state with the results. This approach avoids the UI latency issue I mentioned, and it also helps with separation of concerns!

If you would like more info on how to go about doing all that, I am happy to help, provide pointers, example code, etc.

**Comment by jtdaugherty** [comment]
You can see a simple example of this technique in [the custom event demo program](https://github.com/jtdaugherty/brick/blob/master/programs/CustomEventDemo.hs). Instead of running database queries, that program just sends counter update events to trigger state updates.

**Comment by jtdaugherty** [comment]
Anyway, I also wanted to mention that I'm happy to get more details from you because it helps me understand what you are trying to accomplish. That helps me help you better, since then I can suggest approaches or alternatives!

**Comment by refaelsh** [comment]
> In that case it makes sense that you would want to use listReplace (or even list!) 

Which one is better in my case? It feels they are the same.

**Comment by jtdaugherty** [comment]
`listReplace` will replace the elements of the list without changing other underlying state of the list like the viewport scrolling offset. This might be a better choice for your event handler since it means that if the list is scrolled way down, it will stay that way if you replace the list contents with a similar number of elements. But the `list` function creates a totally new list that will be scrolled up to its top, which may or may not be jarring to the user if you use it in your event handler. You'll need to experiment and see which one gives you the UI behavior you want the most.

Mostly I was thinking that I wouldn't recommend replacing the list on every keypress just because that could be jarring, but sometimes that will definitely be what you need to do. The things to think about are 1) the latency of the event handler like I talked about above and 2) how to maintain the selection of the desired list element once the replacement is done. `listReplace` will keep the selection index the same if it can, but that may not be the element you want selected, depending on what your database query is all about.

**Comment by refaelsh** [comment]
> Here is something to keep in mind: while the event handler is running your database operation to repopulate the list, the event loop will not be able to handle more input events from the keyboard. That means that if your database query and list repopulation take more than a few milliseconds (which is likely), you will experience UI latency as you enter keystrokes because the event handler will not be able to run fast enough to keep up with your keystrokes and the UI will lag behind the input events.

Yes yes. Understood and agreed.

**Comment by refaelsh** [comment]
> `listReplace` will replace the elements of the list without changing other underlying state of the list like the viewport scrolling offset. This might be a better choice for your event handler since it means that if the list is scrolled way down, it will stay that way if you replace the list contents with a similar number of elements. But the `list` function creates a totally new list that will be scrolled up to its top, which may or may not be jarring to the user if you use it in your event handler. You'll need to experiment and see which one gives you the UI behavior you want the most.
> 
> Mostly I was thinking that I wouldn't recommend replacing the list on every keypress just because that could be jarring, but sometimes that will definitely be what you need to do. The things to think about are 1) the latency of the event handler like I talked about above and 2) how to maintain the selection of the desired list element once the replacement is done. `listReplace` will keep the selection index the same if it can, but that may not be the element you want selected, depending on what your database query is all about.

Understood.

**Comment by refaelsh** [comment]
> In Haskell, a very common way to deal with this sort of thing is to set up a [channel](https://hackage.haskell.org/package/base-4.17.0.0/docs/Control-Concurrent-Chan.html) between the event handler and a thread that takes care of the database queries. I don't know if you have experience with concurrent programming in other languages, but this is a way to send messages between threads. The idea is that you'd spawn a thread (at the start of your program, before Brick runs) that will be responsible for waiting for requests to get updates from the database. Your event handler would send that thread a message over the channel (which is very fast) and this would avoid UI latency. The thread would then receive the message and do the database query, then send the results back to the event handler using a custom event, at which point you'd use listReplace to update your state with the results. This approach avoids the UI latency issue I mentioned, and it also helps with separation of concerns!

Understood and agreed.

> If you would like more info on how to go about doing all that, I am happy to help, provide pointers, example code, etc.

I got this covered already. Thank you.

**Comment by refaelsh** [comment]
Thank you very much for all the help. I will go and meditate on it now :-)

**Comment by jtdaugherty** [comment]
You're welcome, thanks for providing the extra info so we can discuss!

**Comment by jtdaugherty** [comment]
Also, please close this issue if you have what you need or let me know what else I can do to help.

**Comment by refaelsh** [comment]
It works. Like this:
```haskell
handleEvents :: BrickEvent () e -> EventM () State ()
handleEvents (VtyEvent e) = do
  state <- get
  case e of
    EvKey (KChar 'r') [] -> do
      let bla = listReplace (fromList ["some_thing_from_db", "some_thing_from_db"]) (Just 2) (listWidget state)
      put $ state {listWidget = bla}
    event -> do
      newListState <- nestEventM' (listWidget state) $ do
        handleListEvent event
      put $ state {listWidget = newListState}
```
Thank you very much for all you answers. I will close now.

P.S.
I still dont understand everything (or anything?) about the `nestEvent` thingy, even after reading the docs several times.
I will chuck it off to my Haskell newbieness.

**Comment by jtdaugherty** [comment]
Great! This could be shortened just a little bit to avoid some duplication:
```haskell
handleEvents :: BrickEvent () e -> EventM () State ()
handleEvents (VtyEvent e) = do
  state <- get
  let prevListState = listWidget state
  newListState <- case e of
    EvKey (KChar 'r') [] -> do
      return $ listReplace (fromList ["some_thing_from_db", "some_thing_from_db"]) (Just 2) prevListState
    event -> do
      nestEventM' prevListState $ do
        handleListEvent event
  put $ state {listWidget = newListState}
```

**Comment by jtdaugherty** [comment]
> I still dont understand everything (or anything?) about the nestEvent thingy, even after reading the docs several times.

This makes sense to me if you are relatively new to Haskell; the documentation does assume a certain amount of familiarity. Understanding `nestEventM` well would require some pretty strong understanding of monads in general, and of state monads in particular.
