### ISSUE TITLE
StateT insinde EventM

### ISSUE THREAD

**Issue by refaelsh** [jtdaugherty/brick#414]
Please consider the following function:
```haskell
handleUpWasPressed :: EventM String TerminatorState ()
handleUpWasPressed = do
  bla <- Historian.next
  writeToPromptLine bla

writeToPromptLine :: String -> EventM String TerminatorState ()
writeToPromptLine datum = ... -- some code goes here, not relevant to the question.
```

The above does not compiles. The error is:
```
src/ViewModel/TerminatorVM.hs:119:10: error:
    • Couldn't match type: Control.Monad.Trans.State.Lazy.StateT Int IO
                     with: EventM String TerminatorState
      Expected: EventM String TerminatorState String
        Actual: Control.Monad.Trans.State.Lazy.StateT Int IO String
    • In a stmt of a 'do' block: bla <- Historian.next
      In the expression:
        do bla <- Historian.next
           writeToPromptLine bla
      In an equation for ‘handleUpWasPressed’:
          handleUpWasPressed
            = do bla <- Historian.next
                 writeToPromptLine bla
    |
119 |   bla <- Historian.next
    |          ^^^^^^^^^^^^^^
```

I understand that it is a type mismatch (I think I understand).
I can probably change the sifnature of `Historian.next` to make it compile,
but I dont want to. I want the Historian module to be separate from the Brick framework,
I wanna reuse it in the future in other frameworks. Please help :-)

Here how the Historian module is written in the Historian.hs file:
```haskell
module Model.Historian
  ( next,
  )
where

import Control.Monad.IO.Class (liftIO)
import Control.Monad.Trans.State
import Data.List (genericIndex)

next :: StateT Int IO String
next = do
  modify $ \s -> s + 1
  contents <- liftIO $ readFile "/home/refaelsh/.giter_history"
  return $ genericIndex (lines contents) (2 :: Int)
```

P.S.
I was not sure if I should ask this here or on Stackoverflow.
On the one hand it feels to me as a general Haskell question ("how to transform Monads"),
on the other hand it involves `EventM` and that is a purely Brick thingy.

**Comment by refaelsh** [comment]
I you agree it is a Stackoverflow question, then please ignore me and close this issue.

**Comment by refaelsh** [comment]
Thank you very much! I will close this for now, since it will take me a while to read this and re-read this and re-read this...

**Comment by jtdaugherty** [comment]
Happy to help. Please feel free to follow up here with other questions as they come up; staring at it until it makes sense may eventually work, but I might be able to help you get there faster if you ask questions!

**Comment by refaelsh** [comment]
I think I understand, mostly. This `runStateT` thingy is new to me (need to google some more about it).
But I do have a question - I need to have the Historian module to be self containted - OOP style (I come from a heavy OOP background to Haskell):
1. Comprise state and functions that work on that state in one module.
2. The module should be reusable - just like we strange OOP people like :-)
3. The Bricks application should be oblivious to the implementation details of the Historian module.
4. The state of the Historian should be in Historian and not "a field your Brick application state".
5. The `initialState` thingy should be part of Historian implementation details and the Bricks application should not be aware of it.

**Comment by refaelsh** [comment]
> Assuming the Historian state integer was a field your Brick application state

No, I want it to be a field in some state struct in the Historian module.

**Comment by jtdaugherty** [comment]
> Comprise state and functions that work on that state in one module.



> The module should be reusable - just like we strange OOP people like :-)
> The Bricks application should be oblivious to the implementation details of the Historian module.
> The state of the Historian should be in Historian and not "a field your Brick application state".
> The initialState thingy should be part of Historian implementation details and the Bricks application should not be aware of it.

**Comment by jtdaugherty** [comment]
> Comprise state and functions that work on that state in one module.

This is typically how one would strive to do it in Haskell.

> The module should be reusable - just like we strange OOP people like :-)

Nothing at all OOP-specific about that, but a sensible goal to me.

> The Bricks application should be oblivious to the implementation details of the Historian module.

I would also strive for this, and I would even go so far as to hide the details of the use of `StateT` at all so that the Brick application doesn't even have to call `runStateT`. (E.g. `runHistorian` would be in the historian module and I'd add a `newtype` for `StateT Int IO`.)

> The initialState thingy should be part of Historian implementation details and the Bricks application should not be aware of it.

Well, that's the part that's basically impossible; how else are you going to call the historian API to give it the data it needs to operate on? It needs to come from somewhere. You could leave it out of your Brick application state just fine as long as you're willing to get it some other way, such as via `IO` in `EventM`, but that's not a good idea in general because `EventM` handlers should do as little IO as possible to avoid UI latency. You could make the *details* of the state be hidden from the application, yes, but you'll still have to expose some information (its type) and provide an initial value, unless somehow your historian API is going to hide that and use a default value.

**Comment by refaelsh** [comment]
> unless somehow your historian API is going to hide that and use a default value.

Yes, that. Thats the point. Is this possible in Haskell?

**Comment by refaelsh** [comment]
I just want a single function in the Historian module that would be called `next` and would get the next line of text from a file.
I need to keep and Int value as a state for this - to hold the current place in the file.
There will be in the future a `prev` function.
The Brick application should not be aware of the fact that Hostorian even has a state, maybe in the future the implementation will change and Historian would not have a state.

**Comment by jtdaugherty** [comment]
> I just want a single function in the Historian module that would be called next and would get the next line of text from a file.
> I need to keep and Int value as a state for this - to hold the current place in the file.
> The Brick application should not be aware of the fact that Hostorian even has a state, maybe in the future the implementation will change and Historian would not have a state.

Without exposing the state to the calling application *at all*, this is equivalent to a global variable. Those are possible in Haskell but highly discouraged as global state tends to be a design mistake in the long run. If you really wanted to maintain non-global state that was hidden from the calling application I think the most common approach is to export the state but make it *opaque*, i.e. expose the state *type* but not its internals. This is basically equivalent to the OOP approach to make member fields and methods private. This is often done by making a wrapper type to store your state, e.g.,
```haskell
data Historian = Historian { ... }
```
and then exporting `Historian` but not its data constructor. The way I would imagine a historian API would be designed is with the following types:

```haskell
-- | Historian data structure (state). We won't export the inner fields
-- of this to the module user; we'll just export the type. That hidesthe details of the state from the user.
data Historian =
    Historian { counter :: IORef Int
              }

next :: Historian -> IO String
prev :: Historian -> IO String
```

**Comment by refaelsh** [comment]
What you are suggesting looks great, I even understood it all from first reading (my Haskell Foo is growing!).
But, question: I see that you are passing `Historian` state into `next` and `prev`, you are basically passing state around, was it not that the State Monad was invented to prevent passing state aroud explicitly? The State Monad passes it implicitly.

**Comment by refaelsh** [comment]
> new :: IO Historian

I really like this idea :-)

**Comment by refaelsh** [comment]
> The caller still needs to hold onto a Historian and provide it to the API

Yes! That took a while, but now I get it.

**Comment by jtdaugherty** [comment]
> But, question: I see that you are passing Historian state into next and prev, you are basically passing state around, was it not that the State Monad was invented to prevent passing state around explicitly? The State Monad passes it implicitly.

In case it helps to follow up on this: the state monad does help implicitly pass state around, but *only between computations that all operate on that state*. When you "exit" those computations into a monad that does not operate on that state, explicit passing of the value is required. You can think of it as "entering" into the state monad and then exiting again. And in general we don't want to go in and out of such monads a lot as part of the public interface for a module since that could be cumbersome or even involve exposing the `StateT` monad as part of the public interface; as I believe you pointed out, it would be better to hide the fact that the state monad is even being used, but not because want to hide the *state itself*, but rather because we do not want the *state monad* to be part of the public interface. So that means we still need to pass in a value (here of type `Historian`) but we don't want the caller to have to care what's inside, just that it represents the state of the service that the module is providing. That state has to be kept somewhere, and since global variables are not a good design choice, holding the value somewhere else until it is needed by the caller is the way to go.

With that said, there is another way to hide state that sometimes gets used in some application designs in Haskell, which is that we spawn a thread that is responsible for handling a bit of state. Instead of invoking operations like `next` and `prev` directly on the state, those operations would send messages over channels (like `Chan` and `TChan`) to the thread. The thread would wait for messages, read a message, do the work requested in the message, and possibly return a response over another message channel back to the caller. That approach hides the state and its use in another thread and exposes an interface in the form of message request and response types. In that approach, a `Historian` type would contain a pair of `Chan`s for sending and receiving messages rather than an `IORef` to store the state itself. This approach is best when there needs to be a worker thread running all the time and possibly doing work requested by multiple callers at once; for your application I suspect it's overkill.

**Comment by refaelsh** [comment]
> When you "exit" those computations into a monad that does not operate on that state, explicit passing of the value is required. 

Please correct me if I am wrong, but Google teaches me that something called "Monad Transforms" is exactly made for such situations: when you need to "transform" (change) Monad A to Monad B.

**Comment by refaelsh** [comment]
> That state has to be kept somewhere
Why cant be kept in the Historian module? Since I am coming from OOP, this seems the most logical.

**Comment by jtdaugherty** [comment]
> Please correct me if I am wrong, but Google teaches me that something called "Monad Transforms" is exactly made for such situations: when you need to "transform" (change) Monad A to Monad B.

This is right, except that the monad being transformed is the one being *wrapped*. So in the case of `StateT s m a`, the monad `m` is the one being transformed. But the issue arising in your situation is that you wanted to use `StateT` code in some *other* monad, `EventM`. It's the process of evaluating those `StateT` values in the context of `EventM` that requires an explicit passing of your state.

> Why cant it be kept in the Historian module? Since I am coming from OOP, this seems the most logical.

When I say "kept", I mean "stored in memory at runtime." Unlike in OOP, where the *runtime storage location* of the state is directly connected to the classes that use that state, in Haskell, the question of where to store the state (i.e. where it is in scope) is separated from the question of *who can mutate or access it*. So the careful exporting of types (but not their constructors) is what controls how the state can be accessed (or mutated) but that is separate from the question of where the *value* of the state should be kept at runtime. Does that make sense?

**Comment by jtdaugherty** [comment]
Even in OOP, the issue arises: if I have an object `o` and need to give it to you, I need to be holding a reference or pointer to `o` to be able to do that. I could use a global variable to avoid that, in which case you could access `o` without my help. But in Haskell (avoiding global variables), I have to hold a reference to `o` and pass it to you in order for you to ever access it.

**Comment by refaelsh** [comment]
> Even in OOP, the issue arises: if I have an object `o` and need to give it to you, I need to be holding a reference or pointer to `o` to be able to do that. I could use a global variable to avoid that, in which case you could access `o` without my help. But in Haskell (avoiding global variables), I have to hold a reference to `o` and pass it to you in order for you to ever access it.

Yes. Agreed and understood.

**Comment by refaelsh** [comment]
> Does that make sense?
Yes!

**Comment by refaelsh** [comment]
I finally got it working. Thank you very much!

```haskell
module Model.Historian
  ( Historian,
    new,
    next,
    -- prev,
  )
where

import Data.IORef (modifyIORef')
import Data.List (genericIndex)
import Numeric.Natural (Natural)
import System.Directory.Internal.Prelude (IORef, newIORef, readIORef)

newtype Historian = Historian
  { lineNumber :: IORef Natural
  }

new :: IO Historian
new = do
  initialValue <- newIORef 0
  return $ Historian {lineNumber = initialValue}

next :: Historian -> IO String
next state = do
  contents <- readFile "/home/refaelsh/.giter_history"
  currentLine <- readIORef $ lineNumber state
  modifyIORef' (lineNumber state) (+ 1)
  return $ genericIndex (lines contents) currentLine
```

And this is how it is used:
```haskell
handleUpWasPressed :: EventM String TerminatorState ()
handleUpWasPressed = do
  state <- get
  bla <- liftIO $ Historian.next $ historian state
  writeToPromptLine bla
```

And I now store the Historian state in Brick's state:
```haskell
data TerminatorState = NewTerminatorState
  { bricksEditor :: Editor String String,
    isFocused :: Bool,
    historian :: Historian
  }
```

**Comment by sim590** [comment]
I might be a little late, but I thought that I would add my experience about this topic after trying to find a solution I liked best.

So, I'm working on a game which is split in two parts: the library and the executable. The library defines the core mechanics and the executable defines the user interface. Therefore, all the logic of my game is inside the library and is independent of the user interface code (using Brick).

Here's an example of signature of my game logic:

```haskell
winner :: MonadState GameState m => m (Maybe PlayerState)
```

In this function I'm able to do stuff like:

```haskell
do
  players . cards %= someFunction
```

in order to apply and mutate the cards of the players for example.

So, since Brick event code is written inside `EventM () ProgramState ()` and that my game logic rather uses `MonadState GameState m`, I was looking for how to write the code that would call my game's logic in the most a natural way. Here's a partial definition of the program state:

```haskell
data ProgramState = ProgramState { _gameState        :: GameState
                                 , ...
                                 , _mainMenuState    :: MainMenuState
                                 , _gameViewState    :: GameViewState
                                 ...
                                 }
```

As you can see, I have embeded the game state inside the program state.

I didn't like the fact to have to wrap a state monad using my game state inside the user interface's state monad.

So I finally wrote this class:

```haskell
class GameStated a where
  getGameState :: a -> GameState
  setGameState :: a -> GameState -> a
```

and this lens:

```haskell
gameStateLens :: (GameStated s, Functor f)
              => (GameState -> f GameState) -> s -> f s
gameStateLens g s = fmap (setGameState s) (g $ getGameState s)
```

That enabled me to write this signature which is independant of the definition of `ProgramState`:

```haskell
winner :: (MonadState s m, GameStated s) => m (Maybe PlayerState)
```

which in turn, just required me to change the previous example of lens mutation for:

```haskell
do
  gameStateLens . players . cards %= someFunction
```

In my user interface code, I then have to define the instance for `GameStated ProgramState` and I can just magically use my game's mechanics functions!

```haskell
startGame :: T.EventM () ProgramState ()
startGame = do
  gs <- initialize playerList
  gameState .= gs
  -- ...
  w <- winner   -- <------- this function uses and may alter the state of the game!
  -- ...
```

actually, I'm writing this and all I did was write what I told about here, plug it inside my user interface code and compile it. I didn't test yet... :rofl: but it looks good.
