### ISSUE TITLE
Different colors in different terminals

### ISSUE THREAD

**Issue by refaelsh** [jtdaugherty/brick#419]
Here is a picture: ![picture](https://user-images.githubusercontent.com/2750775/208263752-1f177c85-e888-43ae-ac52-6edb9318fa9a.png).
On the left side you see my app in [Termonad](https://github.com/cdepillabout/termonad), on the right side its in [Kitty](https://github.com/kovidgoyal/kitty).
Notice the different colors? Its the same binary.
Please help :-)

**Comment by jtdaugherty** [comment]
How are you specifying colors in your attributes? Are you using the base colors like black/white/red/etc. or are you specifying them as RGB colors?

**Comment by refaelsh** [comment]
Like this:
```haskell
theMap :: AttrMap
theMap =
  attrMap
    (white `on` black)
    [ (attrName "red", red `on` black),
      (attrName "bright_red", brightRed `on` black),
      (attrName "green", green `on` black),
      (attrName "bright_green", brightGreen `on` black),
      (attrName "yellow", yellow `on` black),
      (attrName "bright_yellow", brightYellow `on` black),
      (attrName "blue", blue `on` black),
      (attrName "bright_blue", brightBlue `on` black),
      (attrName "magenta", magenta `on` black),
      (attrName "bright_magenta", brightMagenta `on` black),
      (attrName "cyan", cyan `on` black),
      (attrName "bright_cyan", brightCyan `on` black),
      (attrName "white", white `on` black),
      (attrName "bright_white", brightWhite `on` black)
    ]
```

**Comment by jtdaugherty** [comment]
Okay, thanks. In that case, I am not surprised by the difference in colors in the screenshots you provided. The reason is that the colors that your attribute map is using are are basically ANSI color palette indices, not colors. Those indices map to the 16 ANSI color palette that the terminal is using, and *usually* those colors are mapped onto color values that would typically mach their English names (black, red, etc.). However, there is nothing at all to keep any given terminal emulator from choosing particular shades of red, black, green, white for those various entries in the palette. As you can see in the following image, my iTerm2 configuration is currently using the "solarized" color palette for its ANSI colors. So the application might say "please use red" but the terminal emulator looks up the ANSI palette entry corresponding to "red" and uses whatever color is there:

<img width="575" alt="Screenshot 2022-12-18 at 2 15 50 PM" src="https://user-images.githubusercontent.com/427221/208322272-8a1e50bd-832c-4457-a2cd-d1b876b12ed3.png">

That basically means that if you use the 16 ANSI colors, you have *no* control over what colors actually get used, although most of the time the results will look reasonable because most of the time terminal emulators will use colors that are appropriate for the ANSI palette names.

If it matters for your application that you get an exact color match, you'll need to use [RGB color values](https://hackage.haskell.org/package/vty-5.37/docs/Graphics-Vty-Attributes-Color.html#v:rgbColor) instead of the ANSI ones, and that also means that your application will require users to use a terminal emulator that supports higher-resolution colors. Some may not. If they don't, I don't know what they'll do instead. Some may just render the results in grayscale; you'd need to experiment.

**Comment by refaelsh** [comment]
Can you please explain what is the difference between the following 3 functions:
1. `linearColor`
2. `srgbColor`
3. `rgbColor`

**Comment by jtdaugherty** [comment]
`rgbColor` uses `color240` internally and that maps the input arguments to the best matching entry in the 240-color palette as shown [here](https://rich.readthedocs.io/en/stable/appendix/colors.html).

`srgbColor` maps an input tuple (with values in the `0..255` range) into the sRGB color space as described [here](https://en.wikipedia.org/wiki/SRGB).

`linearColor` takes an input tuple (with values in the `0..255` range) and creates a color directly from it without doing any transformations.

I'll update the Haddock for those functions with this information.

**Comment by refaelsh** [comment]
Got it. Thanks!
