### ISSUE TITLE
Padding doesn't affect available width/height

### ISSUE THREAD

**Issue by mitchellwrosen** [jtdaugherty/brick#42]
Hi,

When a widget is padded, its available width and height don't seem to change. Is this intended? Presumably widgets need correct information.

Examples:

```haskell
w :: Widget
w = Widget Fixed Fixed $ do
    c <- getContext
    render (str (show (availWidth c)))

-- shows "123"
main = simpleMain w

-- shows "          123"
main = simpleMain (padLeft (Pad 10) w)
```

**Comment by mitchellwrosen** [comment]
That was fast :)

**Comment by mitchellwrosen** [comment]
Ah, I'm still seeing some unintuitive behavior. Other widgets don't seem to affect width/height like I'm expecting. Example:

```haskell
w :: Widget
w = Widget Fixed Fixed $ do
    c <- getContext
    render (str (show (availWidth c)))

-- shows "123"
main = simpleMain w

-- shows "          113"
main = simpleMain (padLeft (Pad 10) w)

-- shows "hello          113"
main = simpleMain (str "hello" <+> padLeft (Pad 10) w))
```

I'd expect the last width to be `108` to account for the `hello`, no?

**Comment by jtdaugherty** [comment]
Try with a47f924d6fd2c731e90aa6eb203258b5ffb8b589.

**Comment by mitchellwrosen** [comment]
Looks good!

**Comment by jtdaugherty** [comment]
If you use this technique in a custom widget with a `Greedy` policy in the relevant dimension (greedy horizontally in a horizontal box) then the value you get for the available width will be the available width divided by the number of remaining widgets in the box since when boxes render greedy children they give each greedy child the same amount of space.  That ends up being reasonable more often than not.  In your case you'll get the exact remaining space because your widget takes priority due to its `Fixed` policy.  I just bring this up so you know that what you're seeing will/should vary depending on the layout conditions.
