### ISSUE TITLE
Type parameters of the "n" thingy

### ISSUE THREAD

**Issue by refaelsh** [jtdaugherty/brick#423]
Please help :-)
Here is the code:
```haskell
data WidgetName = TreeWidgetName | TerminatorWidgetName
  deriving (Show, Eq, Ord)

data TerminatorView n = TerminatorView
  { bricksEditor :: Editor String n,
    borderColor :: Color,
    isFocused :: Bool
  }

draw :: TerminatorView n -> Widget n
draw state = clickable TerminatorWidgetName (str "sdfsdfd")
```

And here is the error:
```
     • Couldn't match expected type ‘n’
                   with actual type ‘WidgetName’
       ‘n’ is a rigid type variable bound by
         the type signature for:
           draw :: forall n. TerminatorView n -> Widget n
         at src/View/TerminatorView.hs:32:1-36
```

Thank you in advance :-)

P.S.
I was not sure if I should ask this here or on Stackoverflow.
On the one hand, it feels to me as a general Haskell question ("how to use type parameters"),
on the other hand, it involves Bricks's stuff.

**Comment by jtdaugherty** [comment]
The issue is here:
```haskell
draw :: TerminatorView n -> Widget n
draw state = clickable TerminatorWidgetName (str "sdfsdfd")
```

The problem is that `draw` is constructing a `Widget` that is polymorphic in `n` (which could be a very good thing if you want it to be abstract) but you are using `TerminatorWidgetName :: WidgetName` in the call to `clickable` whose result is `Widget n` for whatever `n`-typed argument you gave it. So there are two possible fixes: make the name an argument to `draw` or make `draw` use a concrete `n`. So either
```haskell
draw :: n -> TerminatorView n -> Widget n
draw n state = clickable n (str "sdfsdfd")
```
or
```haskell
draw :: TerminatorView WidgetName -> Widget WidgetName
draw state = clickable TerminatorWidgetName (str "sdfsdfd")
```

**Comment by refaelsh** [comment]
Thank you very much for the answer. I will close the issue while I am meditating on what you wrote.

**Comment by refaelsh** [comment]
Your answer gave me an idea. I solved it like this:
I've added `widgetName :: n,` to the `TreeView` record.
```haskell
data TreeView n = TreeView
  { widgetName :: n,
    bricksList :: List n String,
    isFocused :: Bool,
    borderColor :: Color
  }
```
And then use it like this:
```haskell
draw :: TerminatorView n -> Widget n
draw state = clickable (widgetName state) str "asdasd"
```

The above part of the code now compiles. But:
1. I still don't understand completely what you said: "The problem is that draw is constructing a Widget that is polymorphic in n but you are using TerminatorWidgetName :: WidgetName in the call to clickable whose result is Widget n for whatever n-typed argument you gave it".
2. Now I have a similar problem in another part of the code:
```haskell
handleEvents :: (Eq n) => BrickEvent n Common.CustomEvent -> EventM n (MainView n) ()
handleEvents (MouseUp TreeWidgetName (Just BLeft) _) = do
    -- some code goes here
handleEvents (AppEvent Common.TreeRefreshEvent) = do
  -- some code goes here
handleEvents e = do
  -- some code goes here
```
And here is the error:
```haskell
src/View/MainView.hs:44:23: error:
    • Couldn't match expected type ‘n’
                  with actual type ‘WidgetName’
      ‘n’ is a rigid type variable bound by
        the type signature for:
          handleEvents :: forall n.
                          Eq n =>
                          BrickEvent n Common.CustomEvent -> EventM n (MainView n) ()
        at src/View/MainView.hs:43:1-85
    • In the pattern: TreeWidgetName
      In the pattern: MouseUp TreeWidgetName (Just BLeft) _
      In an equation for ‘handleEvents’:
          handleEvents (MouseUp TreeWidgetName (Just BLeft) _)
            = do state <- get
                 (newState, ()) <- nestEventM (treeView state)
                                     $ do TreeView.mouseClicked
                 modify $ \ s -> ...
    • Relevant bindings include
        handleEvents :: BrickEvent n Common.CustomEvent
                        -> EventM n (MainView n) ()
          (bound at src/View/MainView.hs:44:1)
   |
44 | handleEvents (MouseUp TreeWidgetName (Just BLeft) _) = do
   |       
```

**Comment by jtdaugherty** [comment]
> I still don't understand completely what you said: "The problem is that draw is constructing a Widget that is polymorphic in n but you are using TerminatorWidgetName :: WidgetName in the call to clickable whose result is Widget n for whatever n-typed argument you gave it".

Here's an example. Let's say you have some function
```haskell
foo :: a -> a
foo val = val
```
What this says is that `foo` works for *any* type `a`, and given an argument of type `a`, it always returns a result of type `a`. But if we write
```haskell
foo :: a -> a
foo val = True
```
then this will generate exactly the same kind of error that you are getting because although the type of `foo` promises that it will work for any type `a`, the *implementation* of `foo` breaks that promise and returns *only* a result of type `Bool`. This doesn't agree with the stated type of `foo`, hence the compiler error. This is essentially the same problem you encountered with `draw` because it was polymorphic in `n` according to the type signature (i.e. it had a type variable `n`) but the *implementation* of `draw` used a *specific* type for `n`, thus failing to type check.

> Now I have a similar problem in another part of the code

Perhaps my answer above will help you understand the problem in `handleEvents`.

**Comment by refaelsh** [comment]
Oh! That explanation does help! Thank you very much :-)
I now understand what was wrong in my `draw` function with the help of your `foo` function explanation.

But, I still don't understand my `handleEvents` problem, it's different, it appears to be what I have there is pattern matching on a polymorphic parameter (does that even makes sense what I just said? I hope so :-)). It's different from the `foo` and `draw` functions.

**Comment by jtdaugherty** [comment]
The `handleEvents` error *is* the exact same kind of error. The problem is that the name type in the type signature for `handleEvents` is `n` — it’s polymorphic in `n` — but the pattern match on line 44 for the `MouseUp` case matches on `TreeWidgetName`, which is of type `WidgetName`, a concrete type. Does that make sense?

**Comment by jtdaugherty** [comment]
A way to think about this that I find helpful is that when we write polymorphic functions (I.e. using some type variable, like `n` here) often what we are saying is “this function will work for any `n` and will not care what `n` is.” But your situations above all state that the functions are polymorphic in `n` but use a specific concrete type for `n` in their implementations (and pattern matches). So that usually means that the functions either aren’t polymorphic at all or that some work would be needed to make them work independent of any particular choice of `n`. In your case I suspect the right way to go is to replace `n` with `WidgetName` in your type signatures.

**Comment by refaelsh** [comment]
> The `handleEvents` error _is_ the exact same kind of error.

I agree, the error is indeed the same.

> Does that make sense?

Yes.

**Comment by refaelsh** [comment]
> In your case I suspect the right way to go is to replace n with WidgetName in your type signatures.
No, I want it to be polymorphic, because tomorrow the `WidgetName` type will be completely different type.

**Comment by refaelsh** [comment]
> A way to think about this that I find helpful is that when we write polymorphic functions (I.e. using some type variable, like `n` here) often what we are saying is “this function will work for any `n` and will not care what `n` is.” But your situations above all state that the functions are polymorphic in `n` but use a specific concrete type for `n` in their implementations (and pattern matches). So that usually means that the functions either aren’t polymorphic at all or that some work would be needed to make them work independent of any particular choice of `n`. In your case I suspect the right way to go is to replace `n` with `WidgetName` in your type signatures.

So, correct me if I am wrong, pattern matching of function parameters is impossible when it's a polymorphic parameter?

**Comment by jtdaugherty** [comment]
> So, correct me if I am wrong, pattern matching of function parameters is impossible when it's a polymorphic parameter?

It is impossible to pattern-match on specific constructors from a concrete type, yes.

**Comment by refaelsh** [comment]
> > So, correct me if I am wrong, pattern matching of function parameters is impossible when it's a polymorphic parameter?
> 
> It is impossible to pattern-match on specific constructors from a concrete type, yes.

Oh, bummer. Well, thank you very much.
