### ISSUE TITLE
Some Alt keyboard shortcuts trigger escape key.

### ISSUE THREAD

**Issue by amano-kenji** [jtdaugherty/brick#436]
Pressing Alt+PageUp or Alt+PageDown kills my demo program. It seems these Alt keyboard shortcuts triggered `VtyEvent (EvKey KEsc []) -> halt`. Other brick programs also trigger escape key when I press Alt+PageUp or Alt+PageDown. `htop`, a C program written with ncurses, doesn't trigger escape key when I press Alt+PageUp or Alt+PageDown. I think brick should handle Alt shortcuts better.

By the way, Alt+Ins and Alt+Del also trigger escape key.

**Comment by jtdaugherty** [comment]
What terminal emulator are you using, and what is the value of `TERM`?

**Comment by jtdaugherty** [comment]
And have you found *any* key combination involving `Alt` to not have this behavior?

**Comment by kquick** [comment]
Generally most function keys and ALT keys generate a sequence of bytes starting with an ESC character.  There is some special logic in TTY handling to essentially wait a little bit when an an ESC is received to see if it is a raw ESC or part of one of these sequences (see: termio vtime).

If your particular settings are not quite in alignment with your terminal then this could result in the type of thing you are seeing.  It might be useful to try other terminal UI programs to see what their behavior is (for me, `ESC` does nothing in `htop`, and neither does Alt-PgUp/Alt-PgDown so that doesn't tell me much... you would want to test with an application that does have specific expected responses to all three of those key sequences).

**Comment by amano-kenji** [comment]
1. Alacritty // TERM=alacritty. Alt+h and Alt+l are recognized properly by brick. Alt+PageDown, Alt+PageUp, Alt+Ins, and Alt+Del trigger escape key in brick.
2. st // TERM=st-256color. Alt+h and Alt+l are recognized properly by brick. Alt+PageDown, Alt+PageUp, Alt+Ins, and Alt+Del have the same keycodes as PageDown, PageUp, Ins, and Del.
3. foot // TERM=foot. Alt+h and Alt+l are recognized properly by brick. Alt+PageDown, Alt+PageUp, Alt+Ins, and Alt+Del trigger escape key in brick.

Alt+PageUp, Alt+PageDown, Alt+Home, and Alt+End all work fine in weechat to scroll the current buffer in alacrity and foot. In st, Alt+PageUp, Alt+PageDown, Alt+Home, and Alt+End are the same as PageUp, PageDown, Home, and End.

**Comment by jtdaugherty** [comment]
@amano-kenji for what it's worth, this is a `vty` problem, not a `brick` problem, but we can keep discussing it here. You should also be aware that while I definitely want to understand and improve the situation you have encountered, terminal input is a mess and usually more hacks are needed to make it work well. Some key combos are not supported at all, some are not supported by some terminal emulators, `terminfo` is usually incomplete, and new terminal emulators usually don't help the situation. I want to set your expectation about this because terminals are a huge mountain of accumulated ancient technology and making things work the way we would like can often be difficult. You should expect to run into terminal input handling issues in most programs and most terminals, and I recommend assuming a mentality that it is amazing that it works at all. :)

**Comment by amano-kenji** [comment]
In tmux, I had to tweak escape-time. The tmux documentation for escape-time says

> escape-time
Set the time in milliseconds for which tmux waits after an escape is input to determine if it is part of a function or meta key sequences.  The default is 500 milliseconds.

I set escape-time to 10 milliseconds. vty may have set escape-time to something like 1 millisecond or 1 microsecond. But, I haven't looked at the code, yet.

**Comment by amano-kenji** [comment]
vty's escape-time seems to be 100 milliseconds which is enough time.

* If I press Ctrl+V and Ctrl+h, I get `^H` in alacritty, st, and foot.
* If I press Ctrl+V and Backspace, I get `^?` in alacritty, st, and foot.
* If I press Ctrl+V and Ctrl+Backspace, I get `^H` in alacritty, st, and foot.

However, `EvKey KBS [MCtrl]` is not triggered when I press Ctrl+h or Backspace or Ctrl+Backspace. `EvKey KBS []` is triggered when I press Ctrl+h or Backspace.

**Comment by jtdaugherty** [comment]
> However, EvKey KBS [MCtrl] is not triggered when I press Ctrl+h or Backspace or Ctrl+Backspace. EvKey KBS [] is triggered when I press Ctrl+h or Backspace.

I wouldn't expect this one to work; there are definitely some modifier and key combinations that just generally don't work in terminals. I don't understand the details about that case, though; perhaps @kquick does.

**Comment by jtdaugherty** [comment]
(I mean, `C-h` *is* backspace, essentially; I just wouldn't expect anything to generate `KBS` + `[MCtrl]`.)

**Comment by amano-kenji** [comment]
Okay, let's move the discussion to vty.
