### ISSUE TITLE
Does renderBox need to crop its contents to the context?

### ISSUE THREAD

**Issue by amano-kenji** [jtdaugherty/brick#437]
hBox calls renderBox which calls cropResultToContext.

I tried to render columns that are wider than the available context and crop the left side so that a specific column is shown at the center. The end result was that the right side of columns that goes beyond the visible context was cropped by hBox.

```
cropLeftBy offset $ hBox $ columns
```

In the above code, if columns are wider than the available context, then the right side would be cropped.

I overcame this with

```
cropLeftBy offset $ setAvailableSize (totalWidthsOfColumns, listItemHeight) $ hBox $ columns
```

Calculating total widths of columns was already done in my grid tabular list's rendering algorithm, but I would like to omit `setAvailableSize` if possible for simplicity.

What happens if renderBox doesn't call cropResultToContext?

**Comment by jtdaugherty** [comment]
> In the above code, if columns are wider than the available context, then the right side would be cropped.

This is the expected behavior; a box only gets so much space to render in, and thus it gives its children only so much space. To respect screen space constraints, the child rendering results are cropped to ensure that they fit in the allowed space. It is up to the child widget to decide how to render itself to avoid this cropping, but it must respect the space constraint in the context.

In any case, using `setAvailableSize` is probably the best way to do what you want. The code you have above should be fine and I don't think `setAvailableSize` is a wart there. `renderBox` is not going to change to avoid the cropping of its individual child widgets; the appropriate thing to do is to give the box more space, as you have done.
