### ISSUE TITLE
Question: entering text from user

### ISSUE THREAD

**Issue by refaelsh** [jtdaugherty/brick#446]
Hello,

I have the following need: upon pressing 'c' on the keyboard, a widget should appear that would accept a text entered by the user.
It should be modal.

I looked here: https://github.com/jtdaugherty/brick/blob/master/programs/FormDemo.hs.

But I don't understand how can I make it a modal dialog that would appear when pressing 'c'? And be dismissed when pressing 'Esc` or something.

Perhaps I should make it part of my app's State record? But still, how do I make it appear/disappear at will?

Please help :-)

**Comment by refaelsh** [comment]
Or maybe I should be looking here: https://github.com/jtdaugherty/brick/blob/master/programs/DialogDemo.hs?
Since I need only a simple input field from user.

**Comment by jtdaugherty** [comment]
The built-in dialog box would help a little bit, but you'd still need to do a lot of the steps I described above.

**Comment by refaelsh** [comment]
Thank you very much!
I understand what you are saying.

Just to clarify to my self: you're suggesting Dialog and not Form? Am I correct?

**Comment by jtdaugherty** [comment]
I'm not making any suggestion about whether to use Dialog or Form; both could work as the "editor state" in the design I outlined above. Form would probably be a bit nicer because it gives you a lot more of an API than Dialog in terms of handling input, but it might be too much for what you want to do; I don't know.

**Comment by refaelsh** [comment]
Understood. Thank you :-)
