### ISSUE TITLE
How to debug Brick applications

### ISSUE THREAD

**Issue by refaelsh** [jtdaugherty/brick#451]
Hi,

I usually like to debug with prints to stdout, but since Brick is a TUI thingy, I don't see the stdout.
What is the idiom to debug Brick applications?

Thanks.

**Comment by jtdaugherty** [comment]
I usually use one of two approaches.

1. For print-style debugging from the *drawing* function, I use [Debug.Trace](https://hackage.haskell.org/package/base-4.18.0.0/docs/Debug-Trace.html) to print out messages to `stderr`. This just involves wrapping some value with `trace` so that when the value gets evaluated, the trace message is printed. For example, `draw = trace "drawing the thing!" someWidget` instead of `draw = someWidget`. This approach can be tricky just because it depends on evaluation, and if you instrument a value with `trace`, the message will never get printed if the value never gets used (evaluated). But usually that isn't a problem since the value you're interested in will be one that gets used. A good companion to this is to turn on the `-Wall` compiler option in the Cabal file so that you get compiler warnings about unused bindings.
2. For print-style debugging from the *event handler* function, I use `liftIO $ hPutStrLn stderr msg`.

For both approaches, the program's `stderr` must therefore be redirected to a file, e.g. `my_program 2>log.txt`. I then run `tail -f log.txt` in another window to watch what appears in the log file as the program runs.

I hope that helps! Let me know whether there's something else I can help with in this area, or if not, feel free to close the ticket when you have enough info.

**Comment by kquick** [comment]
You can also write directly to the log file:  `liftIO $ appendFile "debug.log" msg`

**Comment by refaelsh** [comment]
> You can also write directly to the log file: `liftIO $ appendFile "debug.log" msg`

Yeah, that is what I've been doing up until now.
