### ISSUE TITLE
Linux only?

### ISSUE THREAD

**Issue by Heather** [jtdaugherty/brick#46]
brick-0.5 depends on unix-2.7.1.0 which failed to install

Is windows support planned?

**Comment by jtdaugherty** [comment]
`brick` depends on `vty` which depends on `unix`.  `brick` doesn't do anything very *nix-specific so I think this issue boils down to `vty`'s dependency on `unix`. @coreyoconnor - thoughts?

**Comment by jtdaugherty** [comment]
@Heather - are you attempting to build on Cygwin?

**Comment by Heather** [comment]
@jtdaugherty no thanks

**Comment by simonmichael** [comment]
Here's the issue tracking vty windows support: https://github.com/coreyoconnor/vty/pull/1

**Comment by jtdaugherty** [comment]
@Heather - can you elaborate? I don't understand your recent comment. What is your build environment?

**Comment by Heather** [comment]
@jtdaugherty I'm not attempting to build on cygwin and don't plant it

**Comment by jtdaugherty** [comment]
Okay. `brick` doesn't support Windows, as @Heather found, but only because `vty` doesn't - and `brick` won't work on Windows until that is addressed.  It also isn't clear what @Heather's build environment is.  I'm closing this since there isn't much else we can do, but feel free to re-open when it becomes relevant again.

Thanks!
