### ISSUE TITLE
Is there any way to wait for an input? For example, wait for confirmation.

### ISSUE THREAD

**Issue by lsmor** [jtdaugherty/brick#476]
I am trying to buil the following use case:

- There is an action in the TUI the user can trigger with two different modes
- A simple dialog pops "Do you want Action in mode: X or Y"?
- Use the result of the dialog to continue the trigger.

The way I am trying this is using a `Widget.Dialog` stored in my `appState`, together with a `dialogSelectedValue :: Maybe ActionMode` , `isDialogVisible :: Bool` and other state values. The `appDraw` function draws different layers, depending on `isDialogVisible` value, and it works fine. The problem comes from the event handler, I'd like to write something like the one below

```haskell
-- pseudocode
eventHandler event = case event of
  KEnter | isDialogVisible     -> captureDialogSelectedValue
  VtyEvent e | isDialogVisible -> Micro.zoom dialogL (Brick.handleDialogEvent e)
  KeyA  | not isDialogVisible -> do 
        makeDialogVisible
        dialog_decision <- waitForDialogPressEnter
        triggerAction dialog_decision
```

I am not very experienced with brick, maybe this is a noob question

**Comment by jtdaugherty** [comment]
Hi @lsmor - it looks like you want to do something similar to something I've found myself doing quite a bit. What I typically do in a situation like this is to branch on the relevant state value to an event handler for each application mode. In your case the mode flag is represented by `isDialogVisible`. So I'd do something like this:
```haskell
eventHandler :: BrickEvent n e -> EventM n s ()
eventHandler ev = do
    vis <- gets isDialogVisible
    case vis of
        True -> handleDialogEvent ev
        False -> handleMainEvent ev

handleDialogEvent :: BrickEvent n e -> EventM n s ()
handleDialogEvent KEnter = captureDialogSelectedValue
handleDialogEvent (VtyEvent e) = zoom dialogL (Brick.handleDialogEvent e)
handleDialogEvent _ = return ()

handleMainEvent :: BrickEvent n e -> EventM n s ()
handleMainEvent (VtyEvent (EvKey (KChar 'a') [])) =  do
    makeDialogVisible
    dialog_decision <- waitForDialogPressEnter
    triggerAction dialog_decision
handleMainEvent _ = return ()
```
Doing it that way avoids the repetition of the `isDialogVisible` guard in a bunch of places and helps keep the logic more straightforward.

By the way, you don't need to import `zoom` from `microlens` because Brick re-exports it for convenience.

**Comment by lsmor** [comment]
Hi! sorry, I completely miss the question. My main difilculty is to define function `waitForDialogPressEnter`. I have tried many things (For example: using Haskell's thread system like `threadDelay`), but function `waitForDialogPressEnter` essentially returns inmediately with the default `dialog_decision` (`False`) or blocks (due to `threadDelay`, etc...). I couldn't find any `Brick` function which allows you to stop the execution waiting for some input. Maybe I have to play with the focus or something I am not aware of.

**Comment by jtdaugherty** [comment]
It seems like you might need to understand how Brick event handling works a bit better.

As you have described it, the event handler would wait for the user to press a key and then continue. But the event handler *only* ever handles one key input event at a time. That means that if you want to "wait" like you described, you just need to process more events, changing the application state as you go. So, for example:

1. application starts
2. The Vty/Brick library waits for the user to press a key.
3. user presses a key to show the dialog, then your event handler runs and sets a flag to show the dialog.
4. The draw routine runs, rendering the dialog.
5. Step 2 is repeated.
6. At this point the next event arrives, but since step (3) changed the application "mode" to "showing dialog", the key is interpreted by a *different* handler. The "waiting" has already been done for you by the library's event loop; now that the key has arrived, you get to handle it and then decide whether to put the application back into a different mode where the dialog is not rendered.

Using that approach, no explicit "waiting" is needed since all waiting happens automatically in the library while we wait for the user to press any key. Once a key has been pressed, your event handler is run with that key (or other event) and you get to decide how to handle it. But you have to do the book-keeping to know how to interpret the event, which is why I recommended the `Mode` type and handler approach that I described above.

Does that make sense?

**Comment by lsmor** [comment]
Ok, I think I kind of get it. Definetively I have to understand Brick better

**Comment by jtdaugherty** [comment]
Okay. Here's my previous example expanded a bit more to clarify how it might work. This assumes a new state field, `mode :: Mode`, with a lens `modeL`, and it also assumes a new state field `dialogResult :: Maybe DialogResult`, where the user's decision is stored. I don't know what kind of question you're asking so I don't know what goes in `DialogResult`, but hopefully you get the idea. I've just made something up here. Notice how the initial "showing" of the dialog just sets the application mode to `ShowingDialog`; you'd also need a `case` in your drawing function to use the mode to decide when to draw the dialog layer, as you are already doing. Then, as key events arrive while the dialog is showing, the `handleDialogEvent` stores the user's decision in `dialogResult` and then returns the application mode to `Main`.

```haskell
data Mode = Main | ShowingDialog

data DialogResult = Yes | No

eventHandler :: BrickEvent n e -> EventM n s ()
eventHandler ev = do
    mode <- gets modeL
    case mode of
        ShowingDialog -> handleDialogEvent ev
        Main -> handleMainEvent ev

handleDialogEvent :: BrickEvent n e -> EventM n s ()
handleDialogEvent (VtyEvent (EvKey KEnter [])) = do
    dialogResultL .= Just Yes
    modeL .= Main
handleDialogEvent (VtyEvent (EvKey KEsc [])) = do
    dialogResultL .= Just No
    modeL .= Main
handleDialogEvent (VtyEvent e) =
    zoom dialogL (Brick.handleDialogEvent e)
handleDialogEvent _ =
    return ()

handleMainEvent :: BrickEvent n e -> EventM n s ()
handleMainEvent (VtyEvent (EvKey (KChar 'a') [])) = do
    modeL .= ShowingDialog
    dialogResultL .= Nothing
handleMainEvent _ =
    return ()
```

**Comment by lsmor** [comment]
Very kind to dedicate time for the example. I think I finally understand how to do it. The main difference is that I have `IO` action which can be executed in two different ways. I was binding `KeyA` to the action but I guess I have to implement the transition from `ShowingDialog` to the action execution itself after pressing `KEnter`. Just in code

```haskell
action :: Maybe DialogResult -> IO ()
action = \case 
  Just Yes -> action >> extra_stuff
  _        -> action

data Mode = Main | ShowingDialog

data DialogResult = Yes | No

eventHandler :: BrickEvent n e -> EventM n s ()
eventHandler ev = do
    mode <- gets modeL
    case mode of
        ShowingDialog -> handleDialogEvent ev
        Main -> handleMainEvent ev

-- after Showing the dialog the action must be executed
-- if user select any option. The option only indicates how the action
-- will be executed.
handleDialogEvent :: BrickEvent n e -> EventM n s ()
handleDialogEvent (VtyEvent (EvKey KEnter [])) = do
    d <- gets (view dialogL)
    let selection = snd <$> dialogSelection d
    liftIO (action selection)
    dialogResultL .= selection -- probably this is not necessary, as we use the dialog selection right away and does not affect the state of the app
    modeL .= Main
handleDialogEvent (VtyEvent (EvKey KEsc [])) = do
    modeL .= Main -- Just return to normal mode but do not execute the action
handleDialogEvent (VtyEvent e) =
    zoom dialogL (Brick.handleDialogEvent e)
handleDialogEvent _ =
    return ()

handleMainEvent :: BrickEvent n e -> EventM n s ()
handleMainEvent (VtyEvent (EvKey (KChar 'a') [])) = do
    modeL .= ShowingDialog
    dialogResultL .= Nothing
    -- I was placing the (liftIO action ...) here; which isn't the right place.
handleMainEvent _ =
    return ()
```

Again, thanks a lot for your explanations

**Comment by jtdaugherty** [comment]
That makes sense, @lsmor - and as long as your `action` is very fast, this approach will work well. Keep in mind that the longer `action` takes, the longer your UI will be unresponsive because the event handler will be running and that will prevent further user input and redrawing. So, for example, if `action` downloads a large file, this approach will result in the UI being unresponsive until the download is complete. If `action` needs to be allowed to take a lot of time, you'll need to run it in a separate thread. If so, I'm happy to talk about approaches to integrate that into a Brick application.

Let me know if there's anything else you need here, or please close this issue if you have what you need at this point!
