### ISSUE TITLE
There should be something like `fmapState`.

### ISSUE THREAD

**Issue by amano-kenji** [jtdaugherty/brick#477]
```
form' <- nestEventM' form $ handleFormEvent be
modify $ set #uiState $ PositionSizeCalc $ PositionSizeCalcState form'
```
Lines like this are quite common in my codebase.

I'd like to condense it into something like

```
fmapState :: (s -> s') -> EventM n s () -> EventM n s' ()

zoom #uiState $ fmapState (PositionSizeCalc . PositionSizeCalcState) $ handleFormEvent be
```

**Comment by jtdaugherty** [comment]
Hi @amano-kenji. I'm not quite sure I understand, but it sounds like you are saying you want something like `zoom` but for state fields that cannot be accessed with a lens. Is that the case?

**Comment by amano-kenji** [comment]
```
newtype NestedState = NestedState (Form ...)

data State =
  State1 (Form ...) |
  State2 (Form ...) |
  State3 (NestedState)

fmapState State1 $ handleFormEvent be
fmapState State2 $ handleFormEvent be
fmapState (State3 . NestedState) $ handleFormEvent be
```

**Comment by jtdaugherty** [comment]
I think I can sorta see what you might want here, but one thing that is missing is that even if `fmapState` could work as you described above, it can't *get* the state first in order to update it. The thing that makes `zoom` work is that since it is given a lens, the lens is used to get the value of the state to be manipulated, and then it is used to *put it back* when finished with it. As written above, `fmapState` can only wrap up the result of, say, `handleFormEvent`, but there needs to be a way to get the `Form` out of the `State1` (for example) in order to do anything with it.

In general, though, a sum type is going to be troublesome to work with in Brick applications because this pattern is not easy to deal with in a clean way, even if you had something like `fmapState`. I had an application where I thought of designing my state that way, but it turned out to be a real mess. If possible, I recommend taking an approach where those extra bits of state (like your `Form`s above) are in the top-level state, but ignored when they aren't being used. Instead of dispatching based on the `State` constructors like `State1`, I recommend dispatching based on a `State` field of type `Mode`, e.g.
```haskell
data Mode = Main | ShowingForm1 | ShowingForm2 | ...

data State = State { ... , appMode :: Mode, ... }
```
That's very close to using a sum type, but it avoids all of the difficulty of needing to pattern-match on your various `State` constructors which will make things a big pain in the long run. I don't think there's anything I could do in the Brick API to make that nicer.

Another reason I am suggesting taking the approach I described is that, at least in my experience, there are often a *lot* of state fields that end up being common across those sum type constructors, so if your state type is a sum type at the top level, one thing you might immediately run into is that there will be "common" state that needs to be carried around in each application mode. Once that happens, the duplication that inevitably ensues becomes very error-prone to manage.

**Comment by amano-kenji** [comment]
What about
```
newtype NestedState =
  NestedState1 (Form ...) |
  NestedState2 (Form ...)

data State =
  State1 (Form ...) |
  State2 (Form ...) |
  State3 (NestedState)

case state of
  State1 form -> fmapState State1 form $ handleFormEvent be
  State2 form -> fmapState State2 form $ handleFormEVent be
  ...
```

**Comment by jtdaugherty** [comment]
I don't see how that is any different from what you had, and I don't think it addresses any of the issues I raised above.

**Comment by amano-kenji** [comment]
Right now, my approach is a hybrid of common fields and sum types in application state.

```
data Mode = Normal | Error Text | Processing Text

data UIState = State1 Form | State2 Form | ...

data State = State {
  mode :: Mode
, uiState :: UIState
}
```

> I don't see how that is any different from what you had

The difference is that the second version has one more argument.

```
fmapState :: (s -> s') -> s -> EventM n s () -> EventM n s' ()
```

This is basically a one-line version of

```
form' <- nestEventM' form $ handleFormEvent be
modify $ set #uiState $ PositionSizeCalc $ PositionSizeCalcState form'
```

An example code is

```
case state of
  StateX form -> zoom #uiState $ fmapState (PositionSizeCalc . PositionSizeCalcState) form $ handleFormEvent be
```

**Comment by amano-kenji** [comment]
If application state contains all application modes simultaneously, then I would have to either initialize all modes simultanouesly or turn them into `Maybe ThisAppMode1`, `Maybe ThisAppMode2`, ...

**Comment by amano-kenji** [comment]
I think I figured out the right name for the function, `zoomOut`.

`zoom` zooms in. `zoomOut` zooms out.

**Comment by jtdaugherty** [comment]
I have no idea how to actually implement `zoomOut`. But if you do, I suggest that you implement it and use it in your application. Once you've figured out how it will work, then it will be easier for me to tell whether it would be a good addition to the library. Right now I am not sure of that.

**Comment by jtdaugherty** [comment]
Also, I would like to share that if you would like help, I am always happy to discuss things in tickets or the discussion forum. But when you open issues saying something "should" be done, I often find that I feel frustrated in such situations because I would rather arrive at a change to the library (if any!) by first understanding your *problem*, not starting by debating a *solution*. It would really help me if tickets can be used to pose questions like "Is there some way I can achieve outcome X?"
