### ISSUE TITLE
Consider adding `zoomOut` for saving lines when dealing with sum types.

### ISSUE THREAD

**Issue by amano-kenji** [jtdaugherty/brick#479]
```
data Mode = Normal | Error Text | Processing Text

data UIState = State1 Form | State2 Form | ...

data State = State {
  mode :: Mode
, uiState :: UIState
}

handleEvent :: BrickEvent n e -> EventM n State ()
handleEvent be = do
  State { mode, uiState } <- get
  case uiState of
    State1 form -> do
      form' <- nestEventM' form $ handleFormEvent be
      modify $ set #uiState $ State1 form'
```

In this case, `nestEventM'` results in two lines. I came up with `zoomOut` which compresses two lines into one line.

```
zoomOut :: (s -> t) -> s -> EventM n s () -> EventM n t ()
zoomOut constructor intState eventM = do
  intState' <- nestEventM' intState eventM
  put $ constructor intState'

handleEvent :: BrickEvent n e -> EventM n State ()
handleEvent be = do
  State { mode, uiState } <- get
  case uiState of
    State1 form -> do
      zoom #uiState $ zoomOut State1 form $ handleFormEvent be
```

`zoom` and `zoomOut` can be mixed freely.

**Comment by jtdaugherty** [comment]
Thanks for your suggestion! I hope you'll understand, but I'm going to decline to include it in the library for three reasons. The first is that merely saving lines of code is not a compelling reason to me to add this to the API. The second reason is that `zoomOut` is (to my mind) a strange thing to add to the API because it tells users "you will probably need this." I really don't encourage Brick application designers to use sum types for their state fields for exactly the reason that motivated you to write `zoomOut`: it gets to be a pain to unpack and repackage everything when the state gets updated. The third reason is that `zoomOut` more or less goes around the state monad abstraction because it requires that you pass in the input state (here, `intState`).

There is probably a way to do what you're doing by using lenses and/or traversals instead of `zoomOut`, although I don't know what that would be at the moment.

**Comment by amano-kenji** [comment]
I don't know a way to convert sum types into a product type without tradeoffs.

If I convert a sum type to a product type, I think I will have to initialize every state I'm not using.

Do you know a clean way to not initialize unused states?

**Comment by jtdaugherty** [comment]
> If I convert a sum type to a product type, I think I will have to initialize every state I'm not using.

Yeah, that's right. If by "clean" you mean only initializing what you'll be using, then I don't know of a different way to do it. Sometimes when I've dealt with this, I might use `Maybe` to wrap the state fields that don't always need to be filled in. But usually I populate them all, and that ends up being harmless because they get reset whenever the application transitions into the mode that will use those fields anyway. Both approaches have trade-offs; as you're seeing, the sum type approach, while in some sense more "correct" because it only requires you to construct state values that you need for each mode, has the drawback that you then need to pay the price for that correctness that is modeled in the data structure. The other approach where all of the state fields are populated (and then some are unused) has the drawback that some state fields need to be populated early, although due to lazy evaluation that is harmless from a performance standpoint. It also has the drawback that you can more easily forget to reset some fields when needed. But it has the enormous practical advantage that lenses become usable for all state updates regardless of mode, and at least in my experience that has been nicer overall and worth the drawbacks.
