### ISSUE TITLE
Add version of customMain that doesn't require a Vty handle

### ISSUE THREAD

**Issue by frasertweedale** [jtdaugherty/brick#488]
Now that `mkVty` has been split from *vty* to *vty-crossplatform*, it seems impossible (without superfluous dependencies at least) to support versions of *brick* spanning pre-2.0 and post-2.0.  There is no way to conditionally depend on *vty-(crossplatform|unix|windows)* based on the version of *brick* that would satisfy the constraint solver.

However, if *brick-2.something* would export `mkVty`, then, without an explicit dependency on *vty-crossplatform*, it is possible to use a CPP directive to import either `Graphics.Vty (mkVty)` (for brick < 2.0), or `Brick (mkVty)` (for brick >= 2.something).

**Comment by frasertweedale** [comment]
Alternatively, something in between `defaultMain` and `customMain` would be useful (and would also enable me to work around the dependency problem).  We use `customMain` because we use custom events, but we use the default vty config same as `defaultMain` does.

For example:

```haskell
defaultMainWithEvents
  :: (Ord n)
  => Maybe (BChan e)
  -> App s e n
  -> s
  -> IO s
```

**Comment by jtdaugherty** [comment]
Can you help me understand why supporting multiple major versions of brick is important in your situation?

**Comment by frasertweedale** [comment]
Hm... I must be the library author in me defaulting to supporting the widest feasible version range of each dependency.  I guess it doesn't really matter ^_^

Still, what do you think of the second idea?  It would be nice not to have to deal with `mkVty` at all, because all we need is to pass in the `BChan`.

**Comment by jtdaugherty** [comment]
> Hm... I must be the library author in me defaulting to supporting the widest feasible version range of each dependency. I guess it doesn't really matter ^_^

Okay, thanks - that makes sense. I figure applications can usually lock down their supported versions with a lot more freedom than libraries where one would understandably want to support a wider array of versions. I assumed your request was originated from an application context.

> Still, what do you think of the second idea? It would be nice not to have to deal with mkVty at all, because all we need is to pass in the BChan.

I have run into that myself so I can see how this would be nice to have. I'll add something to this effect. I already don't like how that API is a bit combinatorial in what it tries to provide so I'm not excited about adding another version of the function, but at the same time I don't see how it could grow at all beyond the function you're proposing since the ones that are there will then cover all the possible cases.

**Comment by jtdaugherty** [comment]
@frasertweedale I just pushed a commit; check it out let me know if that doesn't meet your needs.

**Comment by frasertweedale** [comment]
@jtdaugherty it's perfect.  Thanks!

**Comment by jtdaugherty** [comment]
Okay. It's now released in 2.1.

**Comment by frasertweedale** [comment]
Nice, thanks for the quick release?  Any chance you could cut a new release of *vty-crossplatform* with the additional unix platforms?  As a FreeBSD user, that's the last step before I can update purebred to brick-2.1.

**Comment by jtdaugherty** [comment]
Done, that's now released in `vty-crossplatform-0.2.0.0`.

**Comment by frasertweedale** [comment]
Many thanks!

**Comment by jtdaugherty** [comment]
I'm happy to help, and thanks for your patch!
