### ISSUE TITLE
Provide absolute coordinates on brick mouse event

### ISSUE THREAD

**Issue by goosedb** [jtdaugherty/brick#504]
Now `MouseDown` and `MouseUp` provide only coordinates relative to clicked extent. Sometimes it not convenient so I had to translate coordnites something like this:
```haskell
translateToAbsolute name (B.Location (c, r)) = do
  B.Extent{extentUpperLeft = B.Location (ec, er)} <- fromJust <$> B.lookupExtent name
  mbViewport <- B.lookupViewport name
  pure $ B.Location (ec + c - maybe 0 B._vpLeft mbViewport, er + r - maybe 0 B._vpTop mbViewport)
``` 
Can we attach to event absolute coordinates too?

**Comment by jtdaugherty** [comment]
I'm afraid that's not possible right now. Right now the only way I can think to expose the absolute coordinates would be to make an API-breaking change, and I'm not sure I want to do that. In the mean time, it would appear that you have a workaround for your particular situation, though.

Perhaps if you could say more about why you are needing absolute coordinates, it's possible I might be able to help in some other way.

**Comment by goosedb** [comment]
So, we can at least add something like `translateToAbsolute` to library

**Comment by jtdaugherty** [comment]
If you're suggesting that Brick itself provide this, I'm not ready to add it. I'm not confident that this is general enough to be useful in many cases. I'm glad to see that you found a way to get what you want, though!

As I said above, I'd like more context on what is motivating this because it's possible there are better ways to do what you want (but I don't know what you want yet). For example, it's possible to use [relativeTo](https://hackage.haskell.org/package/brick-2.3.1/docs/Brick-Widgets-Core.html#v:relativeTo) to do things that would otherwise only be possible by knowing absolute coordinates. But `relativeTo` is going to result in much more portable code.

**Comment by goosedb** [comment]
In monalog I've implemented ability to move boundaries. Since _border_ is extent between two other extents, moving mouse to left or right causes the coordinates to change not by 1 or -1, but in a generally unpredictable way. So, to find out movement direction I need to know absolute coordinates

https://github.com/jtdaugherty/brick/assets/27814653/56ef11f1-6b84-4aca-a3f5-5bd9c2d562dc

**Comment by jtdaugherty** [comment]
Very cool, thanks for the demo! One tip: you might consider using [joinBorders](https://hackage.haskell.org/package/brick-2.3.1/docs/Brick-Widgets-Core.html#v:joinBorders) around your whole UI widget to improve border-drawing connections.

Given your use case, I can't think of another way to do what you're doing. The unpredictability of the coordinate changes has to do with the relationship between when the terminal sends a mouse event and when a redraw occurs, combined with how far the mouse has moved since the last redraw. If the mouse events come in faster than redraws occur (which is very likely) or if the mouse moves more than once terminal cell between redraws (also very possible) then some of the mouse events will seem to have erratic locations. Given that we can't do anything about that, I have found that workarounds like the one you're using are necessary to handle mouse dragging in a usable way.

I'm going to close this on the grounds that I would prefer not to modify the mouse event API (which would break existing programs) or add a new function (since `lookupExtent` already does what you want, but in your case you need more due to involving a viewport). I'm glad you got this working, though!
