### ISSUE TITLE
Still need import for `liftA2`

### ISSUE THREAD

**Issue by kquick** [jtdaugherty/brick#519]
When compiling brick master with https://github.com/jtdaugherty/brick/commit/aeeee31e49de3e8a10955dd82354397d39243b29#diff-7fcd880a6e5d374a64e039c31c6f5831718ba254e6897611c168a2e860c6fb83R20 present, I get undefined errors for `liftA2` with GHC 8.10 through GHC 9.4 (and possibly earlier versions) unless I change this check to `#if !(MIN_VERSION_base(4,18,0))`.  I know this changed from a function to a class method in 4.10, but I'm not sure what warnings you were getting that let to this change, so I'm not sure of the proper fix needed here.

**Comment by jtdaugherty** [comment]
Hey, thanks for reporting this. I was getting a redundant import warning on newer GHCs (9.6? I forget precisely which). So I looked and found that this seems to have become redundant at the time that the type class change in 4.10, which is why I added the conditional import. But if you are seeing errors, then the import should be enabled but may just be wrong; do you know whether there is an additional state we need to allow for? E.g.,

* At some point `liftA2` needed to be imported from somewhere else than `Control.Applicative`
* Then it was importable there, but still a function
* Then in 4.10 it became a type class method, rendering the import redundant

**Comment by jtdaugherty** [comment]
Okay, here's something: from the `base` changelog [here](https://hackage.haskell.org/package/base-4.20.0.1/changelog), `liftA2` was added as a `Prelude` export in base 4.18.0.0 (GHC 9.6.1). So I guess the import only became redundant very, very recently.

**Comment by jtdaugherty** [comment]
This should be fixed now!
