### ISSUE TITLE
Stack lts version is 0.4.1

### ISSUE THREAD

**Issue by anfelor** [jtdaugherty/brick#60]
This is not necessarily a bug, I just wanted to notify you, that the brick version on stackage lts is 0.4.1, for which most examples don't work. The nightly version is up to date, however, but you might want to include a note about this in the manual.

Thanks for this library!

**Comment by jtdaugherty** [comment]
Ultimately I don't have any control over the version of my library that goes into various versions of Stackage.  Your report made me remember that I actually intended to remove my packages from Stackage entirely.  (I realize that's kinda the opposite of what you wanted, but they have now been removed.)  I recommend just using the version that's on Hackage.

I'm glad you're getting value out of the library!

**Comment by anfelor** [comment]
Wait a moment, that is indeed the opposite of what I intended. I know, that I can use stack with hackage packages, but I have always thought, that that was mainly for less stable packages, which shouldn't be used with production code. Could you at least explain that move?

**Comment by jtdaugherty** [comment]
Nothing about hackage is specifically about less stable packages.  Stackage is one way to get a stable collection of packages, but it is not necessary to use Stackage to do this.  (`cabal freeze`, for example, is a perfectly good way to deal with reproducible builds for production purposes.)

My decision to add my packages to Stackage was experimental at best, and I'm finding out that "supporting" Stackage for my packages is awkward because I have no control over what Stackage does.  I also do not use it myself and have no intention of doing so for various reasons, so I have been planning on removing my packages from it because it's hard to claim I support it when I don't use it or follow it.

I understand this isn't what you wanted. You filed this issue at a strange time when I had been meaning to make this change but hadn't gotten around to it. :)  As you pointed out, if Stackage is important to you then you can use it with Hackage packages.  If you want to explore just using Hackage, the new `cabal new-build` features are a promising alternative and I think `cabal freeze` is definitely worth consideration.

**Comment by anfelor** [comment]
Thank you!

**Comment by simonmichael** [comment]
Drat! I hope someone adds brick to stackage again in future. It's a key piece of hledger-ui, and having it in stackage increases the likelihood that it's included and up to date in distro package systems, and increases the chance that a new haskeller trying to install a brick-based app from source will have a good experience.

**Comment by jtdaugherty** [comment]
Isn't it possible to install stack-enabled sources using sources that are only available on Hackage?

**Comment by jtdaugherty** [comment]
And for what it's worth, it would be awkward if someone other than me put one of my libraries in stackage. :)

**Comment by simonmichael** [comment]
Yes, that works when building from source, though it adds more possible failure modes (hackage downtime, less build plan testing, less screening of malicious uploads)

**Comment by simonmichael** [comment]
Not if you were ok with it.

**Comment by jtdaugherty** [comment]
I don't think the drawbacks you mentioned are likely/significant enough to outweigh my opposition to using and supporting stack and Stackage.  (And being opposed, I wouldn't want my packages added on my behalf because that represents a support promise that someone would be making on my behalf.)

**Comment by simonmichael** [comment]
@jtdaugherty: are you actually opposed to stackage, rather than just short of time ? That would make me sad.

On the up side for me, I see brick-0.6.4 landed in stackage nightly-2016-05-26 (GHC 7.10) and brick-0.7.1 in nightly-2016-05-28 (GHC 8.0). There's no entry for it in stackage's [build-constraints.yml](https://github.com/fpco/stackage/blob/master/build-constraints.yaml); I think it is included automatically because another stackage package depends on it, and because it builds, and in this situation the package maintainer has no responsibility for keeping it working in stackage.

**Comment by jtdaugherty** [comment]
I'm opposed to stackage and stack on both technical and social grounds.

**Comment by simonmichael** [comment]
I see, I'm sorry to hear that.
