### ISSUE TITLE
Question: scrolling view

### ISSUE THREAD

**Issue by geekingfrog** [jtdaugherty/brick#97]
I'm working on a chat application, and I was thinking of using a ringbuffer to hold the recent history of messages. I don't know how to render that though.
Is there a brick widget for such purpose? The only similar thing I saw is Brick.Widget.List but it seems built with a different purpose in mind.
Do I need to reach for a custom widget here?

**Comment by jtdaugherty** [comment]
The `List` widget is intended for use cases where you have a list of items and need to be able to use a cursor to select one. It has a restriction that all of its items have to have the same height, so even if you could turn off the cursor behavior, the height requirement would almost certainly make it unsuitable for your use case because your chat messages will have different heights, especially if you word-wrap them (which depends on the terminal width at the time).

There is not a built-in widget for what you want to do, but it is possible to do this. I'm also working on a chat application that does exactly this, so I've tried out a few approaches. My application renders chat messages with the most recent at the bottom of the window like many other clients do. What my application does is:
* Use a custom widget to render the message list
* In the custom widget rendering function, start rendering from the bottom, one message at a time, until we have rendered enough messages to fill the available space (by looking at the rendering context).
* Vertically concatenate the individual messages' Images together to form the final Image.
* Before returning the Image, crop it from the top so that its height is no larger than the `availHeightL` field of the rendering context, as required.

The function that does this is `renderLastMessages` at https://github.com/matterhorn-chat/matterhorn/blob/master/src/Draw/Main.hs#L278.

This approach *doesn't* deal with scrolling to look at older messages, though. For that, we use another approach which I can detail if needed.

**Comment by geekingfrog** [comment]
Very interesting, thanks for the write up and the code. Also, yes, I would be interested in the scrolling approach, since my app is going to have to deal with that as well.

**Comment by jtdaugherty** [comment]
Okay. The way I've handled scrolling is a little more involved. Here's what I did in this case:
* Beginning scrolling by pressing, say, Page Up switches the application to a mode where the above rendering I described is not used at all. Instead of rendering messages from the bottom up and stopping when we have filled the screen,
    * the event handler that handles the initial Page Up keypress resets the viewport (see below) by scrolling it all the way to the bottom, then up by one page, to result in the desired UI behavior for starting scrolling from the bottom;
    * all known messages are rendered irrespective of screen size;
    * the messages are rendered in a viewport;
    * the contents of the viewport are cached in the `brick` rendering cache using the `cached` function;
    * page-up and page-down events scroll the viewport, but since the contents are cached, we don't have to pay the cost of re-rendering all of the messages each time the user scrolls up or down;
    * when the user presses Esc we go back to rendering just a screen-full of messages without the scrolling viewport.

The drawing code that decides which of these approaches to take is at
https://github.com/matterhorn-chat/matterhorn/blob/master/src/Draw/Main.hs#L260

and the event-handling code that does the initial scrolling setup is at
https://github.com/matterhorn-chat/matterhorn/blob/master/src/Events/Main.hs#L78

You can also see that when scrolling begins, we invalidate the rendering cache entry for the messages because we don't want a cached copy from last time the user scrolled to be used.

**Comment by geekingfrog** [comment]
Thanks, that's very helpful. I'll probably end up with more or less the same code on my side :)
